### ISSUE TITLE
Gitter link does not work.

### ISSUE THREAD

**Issue by nesl247** [oh-my-fish/oh-my-fish#1]
The Gitter link results in a 404 "this is not the chat you were looking for" page. Assuming something wasn't updated when the repository was moved back, as it actually tries to look for `wa/oh-my-fish`.

**Comment by bpinto** [comment]
I'm trying to get it to work. Contacted @gitterHQ through here: https://gitter.im/gitterHQ/gitter

**Comment by bpinto** [comment]
@nesl247 It's working now. Thanks for bringing it up.

P.S.: Come and join us! :+1:
