### ISSUE TITLE
fish: Uknown command 'omf'

### ISSUE THREAD

**Issue by davidnknight** [oh-my-fish/oh-my-fish#104]
Hi,

I've done a clean install of Fish using Brew, then using the installer and both times I get `fish: Uknown command 'omf'`:

<pre>Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
David@Davids-MacBook-Pro ~> omf
fish: Unknown command 'omf'
David@Davids-MacBook-Pro ~> fish -v
fish, version 2.2.0
David@Davids-MacBook-Pro ~></pre>

**Comment by davidnknight** [comment]
FYI: Just installed using the command line `curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish omf help` and now works fine.

**Comment by bpinto** [comment]
Could you show us the output of the installation?

It's likely that the installation did work but you needed to open a new shell for omf to load properly.

**Comment by davidnknight** [comment]
I don't have the output anymore but I had opened countless new shells and even restarted the machine but to no avail, so that certainly wasn't the issue.

**Comment by derekstavis** [comment]
The line should be

```
curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
```

**Comment by davidnknight** [comment]
The above `curl` line that I used was copied from the read me. Either way, the `curl` method worked, it was the brew and installer methods that left me with an incomplete installation.

**Comment by bpinto** [comment]
I'm a little lost here, I don't know what happened nor which command you ran... So I don't even know if we have to do changes to the README page.

If you could share more information, that would be helpful. Thanks!

**Comment by tamoyal** [comment]
For example:
```
$ brew install fish
==> Downloading https://homebrew.bintray.com/bottles/fish-2.4.0.sierra.bottle.tar.gz
Already downloaded: /Users/tamoyal/Library/Caches/Homebrew/fish-2.4.0.sierra.bottle.tar.gz
==> Pouring fish-2.4.0.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
You will need to add:
  /usr/local/bin/fish
to /etc/shells.

Then run:
  chsh -s /usr/local/bin/fish
to make fish your default shell.
==> Summary
🍺  /usr/local/Cellar/fish/2.4.0: 837 files, 6.2M
$ fish --version
fish, version 2.4.0
$ omf
-bash: omf: command not found
```

Opening a new shell doesn't help. I'm on OSX 10.12.1

**Comment by oranja** [comment]
Ah ha! This explains everything.

Oh-My-Fish is _not_ bundled with the fish shell. Not in brew, nor anywhere else.
Oh-My-Fish is a package manager, written in fish, for fish, and we here like it the most, but it's not the only one. There are other such package managers, and each fish user is free to choose a package manager for him/herself, if any at all.

To use OMF, you'll need to install it first. See: https://github.com/oh-my-fish/oh-my-fish#installation

**Comment by tamoyal** [comment]
Yep that's the deal. I was thinking the installer took care of everything but the pipe makes it clear

**Comment by muslikhuladib0** [comment]
> The line should be
> 
> ```
> curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
> ```

thanks brow
