### ISSUE TITLE
Personal Functions

### ISSUE THREAD

**Issue by rrosson** [oh-my-fish/oh-my-fish#106]
I have a collection of functions (mainly aliases) that I wrote that I want to retire since transitioning to OMF. What do I need to do to be able to use them with OMF.

I did not see anything in the guide for this. If I missed it please point me in the correct direction.

TIA

**Comment by bpinto** [comment]
I'd advise creating a plugin for your personal functions

Example:

`omf new pkg rrosson` and the add your personal functions to the `functions` folder inside the plugin.

**Comment by bobthecow** [comment]
@bpinto It feels a bit weird adding a plugin for things like this. It wouldn't be a bad idea to support autoloading functions and completions out of `$OMF_CONFIG/{functions,completions}`.

**Comment by bpinto** [comment]
I honestly prefer the plugin. It's how I handle personal functions. However we do already load functions defined on `$OMF_CONFIG/functions`

**Comment by bobthecow** [comment]
I use personal plugins as well, but it's nice to support a "dump things here" bucket for when the friction of adding a plugin seems too high.

And it turns out we already support it :P

**Comment by bobthecow** [comment]
Let's add completions as well?

**Comment by rrosson** [comment]
Ok, You guys are awesome. I had just finished making a dumping ground pkg for my small collection of functions and two completions when you guys gave me the answer I was looking for. I created a functions and completions directory inside of ~/config/omf/ and copied my files there. restarted with a new shell and everything works.
