### ISSUE TITLE
Themes.md has the wrong screenshot for bobthefish 

### ISSUE THREAD

**Issue by bobthecow** [oh-my-fish/oh-my-fish#116]

**Comment by bpinto** [comment]
The `[screenshot]` link is being replaced, we need to add a namespace to each theme link.

**Comment by derekstavis** [comment]
I'd prefer having a sparse list in form of:

* [__Theme Name__]() - Theme description fetched from github repository

Instead of pulling the whole README into our respository.

**Comment by bobthecow** [comment]
If prefer to have screenshots as well, just to give it some more context :)

**Comment by bpinto** [comment]
Screenshots are a must. :+1:

**Comment by bpinto** [comment]
Hey @Pyppe do you think you could to work on this?
