### ISSUE TITLE
Problem with installation.

### ISSUE THREAD

**Issue by t04d-11th** [oh-my-fish/oh-my-fish#117]
This is output :
Installing Oh My Fish to /home/t04d/.local/share/omf...
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Adding startup code to fish config file...
An error occurred while redirecting file '/home/t04d/.config/fish/config.fish'
open: Permission denied
Building Oh My Fish configuration...
Standard input: omf install
                ^
Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues

I Tried 
curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install > install; and fish install
env OMF_CONFIG=~/.omf curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
After deleted each time omf dir.

**Comment by bobthecow** [comment]
It looks like a permissions issue on your current `config.fish`. Just for fun, run `chown -R (whoami) ~/.config/fish/` and see if you can install after that?

**Comment by t04d-11th** [comment]
bobthecow
Thank you for support
Resolved with:
`sudo chown -R (username) ~/.config/fish/`

**Comment by bobthecow** [comment]
Might be worth adding a check or something to installer so it's smarter about this going forward?

**Comment by derekstavis** [comment]
There was such check, I think I forgot to add it back when refactoring install script.

**Comment by bobthecow** [comment]
:cool:
