### ISSUE TITLE
Move text colorising stuff into a embedded plugin

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/oh-my-fish#12]
Currently `omf` plugin uses its own `omf::` series of functions to colorize output. I have stumbled upon oh-my-fish/theme-bobthefish#7 and a possible universal solution would be the framework providing output colorisation as a embedded plugin so that both themes and plugins get more compatible with the running environment.

Comments? Ideas?

**Comment by bpinto** [comment]
I like the idea, and most terminals do not have as many colors as `bobthefish` theme.

I see them using these [default colors](https://github.com/fish-shell/fish-shell/blob/5f080fcfc990ad6673f15c0382c7d6468c1b083e/share/functions/__fish_config_interactive.fish#L50-L85).

---

We should also improve the color functions. We always need to do this: `(omf::color)$text(omf::off)` it would much easier if we could achieve the following: `(omf::color $text)`.

**Comment by ohspite** [comment]
In case you're still interested, @derekstavis, that issue you referenced is wrapped up now and `bobthefish` has multiple color schemes.

**Comment by derekstavis** [comment]
This was done as part of [oh-my-fish/plugin-technicolor](https://github.com/derekstavis/plugin-technicolor)
