### ISSUE TITLE
Replace image logos by an optimised SVG version

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/oh-my-fish#131]
We are currently using a PNG-based logo which weights 18.80k. I have redrawn our logo in fully vectorised SVG, which brings benefits in scalability -- we need just one file and can abuse on dimensions -- and in load time -- I optimised it down to just 0.7k.

Please give a look below and tell what you guys think about:

![SVG Optimised Logo](https://dl.dropboxusercontent.com/u/56336/omf/omf-logo-optimised.svg)

**Comment by scorphus** [comment]
I think it's bit too *roundy*. The original is more angular:

![Oh-My-Fish](https://avatars3.githubusercontent.com/u/11728505)

**Comment by scorphus** [comment]
Remarkable job btw, @derekstavis, :+1:

**Comment by derekstavis** [comment]
It's a downside of optimising the SVG file. If we remove floating point things get roundy :stuck_out_tongue:

**Comment by scorphus** [comment]
I think there still going to be two points in each those curves. Are you using Inkscape? Or what?

**Comment by derekstavis** [comment]
But yeah, in the tail things got more roundy, but also more concise, as rounding was applied homogeneously through the polygons.

**Comment by derekstavis** [comment]
Adobe Illustrator, always!

![screen shot 2015-10-18 at 7 24 51 pm](https://cloud.githubusercontent.com/assets/1611639/10566729/edb0aabe-75cd-11e5-8ceb-dfc3a21070b3.png)

**Comment by scorphus** [comment]
Argh... Let's keep it all open source, mate! Inkscape FTW!

**Comment by derekstavis** [comment]
I'm familiar with Inkscape, but as I've worked with Illustrator for a long time I'm more used to its commands and "its way". I have redrawn the logo in about 8 steps.

**Comment by scorphus** [comment]
![clip](https://cloud.githubusercontent.com/assets/2112697/10566753/8ecf7fc4-75ce-11e5-818d-1abb5b74688d.png)

**Comment by derekstavis** [comment]
The original version is disrespecting the rounding harmony:

![screen shot 2015-10-18 at 7 31 09 pm](https://cloud.githubusercontent.com/assets/1611639/10566760/db3ea718-75ce-11e5-8ada-e7ef437ea535.png)

Left side is very *roundy*, while right side is almost straight!!

**Comment by scorphus** [comment]
Perhaps @bucaran has the original SVG?

**Comment by scorphus** [comment]
> The original version is disrespecting the rounding harmony:

I completely disagree. IMHO that's the beauty of it :smile:

**Comment by derekstavis** [comment]
No, he doesn't. The original is here:

https://github.com/oh-my-fish/oh-my-fish-legacy/issues/380

And it's PSD. It's not nearly vector.

**Comment by scorphus** [comment]
Let's keep it ipsis litteris, in SVG format :smiley:

**Comment by derekstavis** [comment]
I've offered my version. Perhaps you can produce a better one?

**Comment by scorphus** [comment]
Absolutely.

**Comment by bpinto** [comment]
The SVG format in #380 is the same logo, he just removed the terminal window on issue #490.

**Comment by derekstavis** [comment]
There's no SVG version :stuck_out_tongue:

**Comment by derekstavis** [comment]
Have a taste of my SVG version here:

https://github.com/oh-my-fish/plugin-errno

**Comment by scorphus** [comment]
Perhaps @marcker might want to chime in as well and ![pdn35icons magicwandtoolicon](https://cloud.githubusercontent.com/assets/2112697/10567053/bb8be78e-75d6-11e5-9abc-7ecc93675aa4.png) magically attach an SVG version of his beautiful creation :smiley:

**Comment by bucaran** [comment]
Good job @derekstavis, looks good.

**Comment by derekstavis** [comment]
Thanks @bucaran :+1:

**Comment by marcker** [comment]
I support the work that @derekstavis did. The changes were to improve and there was no depreciation of work. Good job:sparkles:!

**Comment by derekstavis** [comment]
It's a honor for me @marcker!! And thanks for giving us an awesome logo :tada:

**Comment by coderstephen** [comment]
:+1:

**Comment by bpinto** [comment]
This has been done on #139
