### ISSUE TITLE
Git plugin from oh my zsh

### ISSUE THREAD

**Issue by Bartuz** [oh-my-fish/oh-my-fish#140]
Would be great to see these!

https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh

**Comment by bpinto** [comment]
There has been some people that converted these aliases to oh-my-fish plugins, but as aliases are very personal, we prefer not to add it to the official database.

I don't know of any external plugin URL though, perhaps someone else can indicate?

**Comment by Bartuz** [comment]
I couldn't find them.

I don't consider these aliases as 'personal'. They are widely used by zsh
community. It is as common as `ll` in any shell.

2015-10-23 14:47 GMT+01:00 Bruno <notifications@github.com>:

**Comment by bpinto** [comment]
We allow plugins and packages to be installed from any github repository, so if you convert these aliases to fish, just share the repository URL here and in case another issue like this is raised, people know where to find the plugin.

P.S.: If you are going to work on it, try not to use the `alias` command to create aliases, use `function` instead.

**Comment by czechboy0** [comment]
I'd love to see this as well. @Bartuz Are you working on something?

**Comment by Bartuz** [comment]
No, I'm not working on it.

 I've switched back to oh my zsh and installed fish like autosuggestion. Works like a charm

Wysłane z iPhone'a

Dnia 24.01.2016 o godz. 12:34 Honza Dvorsky <notifications@github.com> napisał(a):

**Comment by czechboy0** [comment]
Haha I went back too! Which plugin did you use for fish-like completion in zsh?

**Comment by Bartuz** [comment]
https://github.com/tarruda/zsh-autosuggestions

With a default installation it's not the same autosuggestion from fish but if you change few  variables in your zshrc it works almost the same. 

I don't have access to my computer now so I can't send it to you but if you read through their wiki/readme.md you should be able to tweak it on your own

Wysłane z iPhone'a

Dnia 24.01.2016 o godz. 12:43 Honza Dvorsky <notifications@github.com> napisał(a):

**Comment by czechboy0** [comment]
Thanks :+1:
