### ISSUE TITLE
System beep after certain commands

### ISSUE THREAD

**Issue by predmijat** [oh-my-fish/oh-my-fish#148]
Hey,

I don't know if this is desired behavior or not, but I can hear system beep after commands like `ls`, `touch`, `cat`, `cp`, `rm`, maybe some others...there is no beep on `cd` though. I've test both with and without my custom (before).init.fish, and result is the same.

Should it be like that? If yes, how do I turn it off? If not, how can I debug it?

Thanks!

**Comment by derekstavis** [comment]
Let's eliminate variables from your issue. Let's start with Oh My Fish.

Remove fish from initialization:

```fish
mv ~/.config/fish/config.fish{,.old}
```

Reload your shell:

```fish
exec fish
```

Check if the beeps stopped and report back

To restore Oh My Fish:

```fish
mv ~/.config/fish/config.fish{.old,}
```

**Comment by derekstavis** [comment]
If the beeps continue when you restore Oh My Fish, I would recommend you
to give a look at your current theme. If not already, try switching to default:

```fish
omf theme default
```

**Comment by predmijat** [comment]
It's the theme. I thought it wasn't, but I didn't do `exec fish` after switching themes while I was testing it...
No beep on the default one, no beep on agnoster, beeps on budspencer :)
Is there an easy way to figure out what is wrong?

**Comment by bpinto** [comment]
I'd recommend opening an issue on the theme repo, the author might be able to help you.

**Comment by predmijat** [comment]
I'll do that :)
