### ISSUE TITLE
Support an optional `omf-` prefix for repos?

### ISSUE THREAD

**Issue by bobthecow** [oh-my-fish/oh-my-fish#152]
When a package repo is in the omf org, it's namespaced: `oh-my-fish/theme-foo`. But when it's a user's repo, it's not: `fred/plugin-bar`. In this case, it's not super obvious what it's a plugin for. We should support an optional `omf-` prefix, which is removed just like the `plugin-` and `theme-` prefixes :)

**Comment by derekstavis** [comment]
I like the idea!

**Comment by bpinto** [comment]
I like the idea too (being optional).

**Comment by thecotne** [comment]
repository name should not matter at all for user repos 
plugin name can be taken from file name in `db/pkg`
or something like package.json can be created in repository or something like this can be done https://github.com/wbond/package_control_channel/blob/master/repository/a.json

i could contribute to this but i don't know fish language and also i can't understand how someone can write actual script in shell scripting languages i can't even use awk in my plugin

**Comment by bpinto** [comment]
> i can't understand how someone can write actual script in shell scripting languages i can't even use awk in my plugin

:joy: 

`package.json` is more complicated than what we need. All we need is to answer a simple question: is it a theme or a plugin?

Simple is better here. Supporting`omf` is a good solution.

**Comment by thecotne** [comment]
if i could write this in programming language i would lookup in db directory and there if repository is in pkg directory then it's plugin if in themes it's theme very simple

plugin/theme name is filename in db directory and repository name is never used anywhere 

i always like simple in use not in implementation (if you can't achieve both)

btw i managed to rewrite php script with awk and also simplify regex https://github.com/thecotne/omf-artisan/commit/c7142c3815099393c1bc40e063931eca8205cae6

i want to try implementing this but how can i test if change in script it worked or not? (debugging/testing)

**Comment by bpinto** [comment]
> if i could write this in programming language i would lookup in db directory and there if repository is in pkg directory then it's plugin if in themes it's theme very simple

You don't have this for plugins that are not on the database and we do support installing from any URL and soon folder on your computer.

> i always like simple in use not in implementation (if you can't achieve both)

It's very simple to use, we just add it to the name of the plugin.

Anyway, I don't think there is any point on discussing this, it's certainly not what I want to do nor you. We both want to improve the framework. So let's focus on how to improve it instead.

---

> i want to try implementing this but how can i test if change in script worked or not? (debugging/testing)

We check if the package is a theme or a plugin [here](https://github.com/oh-my-fish/oh-my-fish/blob/master/pkg/omf/cli/omf.install.fish#L10). See that we have a `grep theme-` we need to support `omf-theme` also.

That would mean: `omf-plugin-blabla`, `omf-blabla` or `blabla` would work and we support themes using `omf-theme-blabla` and `theme-blabla`.

**Comment by thecotne** [comment]
i have changed my repository name https://github.com/thecotne/oh-my-fish/commit/49a2fa02cab64a03026f4e48ae6cd34463b7ea47

if/when you add support for `omf-` prefix #178 can be merged 

i found 3 places where `plugin-` or `theme-` prefix is used 
oh-my-fish/pkg/omf/cli/omf.bundle.remove.fish
oh-my-fish/pkg/omf/cli/omf.bundle.install.fish
oh-my-fish/pkg/omf/cli/omf.install.fish

it looks like a very simple change

> You don't have this for plugins that are not on the database and we do support installing from any URL and soon folder on your computer.
i did not know about that
okey if not package metadata file then `omf-` prefix is best solution
