### ISSUE TITLE
How can I list the available packages with 'omf' command?

### ISSUE THREAD

**Issue by simonbcn** [oh-my-fish/oh-my-fish#162]
I can list the omf installed packages but how can I list the available packages with `omf` command?
It would be very useful. 
For example, I want to install the [balias package](https://github.com/oh-my-fish/plugin-balias) but `omf` doesn't find it, I've tried it with:
```
$ omf install balias
Installing package balias
fatal: repository 'balias' does not exist
Could not install package balias.
```
and with:
```
$ omf install plugin-balias
Installing package balias
fatal: repository 'plugin-balias' does not exist
Could not install package balias.
```
if `omf` has an option to display the available packages, it would be easier.

**Comment by derekstavis** [comment]
You can use completions. Just `omf install ` <kbd>TAB</kbd>

**Comment by derekstavis** [comment]
balias plugin is deprecated, as now you can use fish abbreviations to achieve the same effect:

abbr -a gs 'git status'

**Comment by simonbcn** [comment]
ok, thanks. :+1:
