### ISSUE TITLE
Reactivate 'balias' plugin

### ISSUE THREAD

**Issue by simonbcn** [oh-my-fish/oh-my-fish#164]
The `balias` plugin was very useful to me. It allows create an alias (like in bash) with completion. With `abbr` doesn't show the 'alias' in autocomplete.

**Comment by bpinto** [comment]
Fair. Could you open a PR adding it to the database?

**Comment by simonbcn** [comment]
PR:question:

**Comment by bpinto** [comment]
a Pull Request?

**Comment by simonbcn** [comment]
It seems already open by you: https://github.com/oh-my-fish/plugin-balias/commit/9fb134c097c0aaec15a5f5c79bca8aa6879b1473

**Comment by bpinto** [comment]
Oh, I was referring to this:

```
⋊> omf on suppress-basename-output ◦ omf install balias                                                                                                                   12:43:21
Installing package balias
fatal: repository 'balias' does not exist
Could not install package balias.
```

sorry about the confusion.

**Comment by bpinto** [comment]
This has been added. Thanks @oranja
