### ISSUE TITLE
as I uninstall? 

### ISSUE THREAD

**Issue by magdeoz** [oh-my-fish/oh-my-fish#169]
I would like to know how to uninstall this, this rather than help me with something, it makes me slow my terminal :-1:

**Comment by bobthecow** [comment]
You can run `omf destroy` to remove oh-my-fish.

But before you go: it doesn't make any of our terminals very slow, so we would be interested in knowing why it makes your terminal slow, if you don't mind helping us understand.

**Comment by magdeoz** [comment]
in my case, between each command it takes a few seconds to write the following

**Comment by bobthecow** [comment]
what theme did you use? what plugins did you enable?
