### ISSUE TITLE
omf error: 'Expected a command, but instead found a redirection'

### ISSUE THREAD

**Issue by simonbcn** [oh-my-fish/oh-my-fish#173]
I have updated `omf` now with `omf update`. All ok but now when I try to execute `omf` with any option:
```
omf -h
Expected a command, but instead found a redirection
~/.local/share/omf/pkg/omf/omf.fish (line 36): <<<<<<< Updated upstream
                                               ^
from sourcing file ~/.local/share/omf/pkg/omf/omf.fish
	called on standard input

in command substitution
	called on standard input

source: Error while reading file “/home/simon/.local/share/omf/pkg/omf/omf.fish”
```
And if I try to execute `omf` again it only says:
```
$ omf -h
fish: Unknown command 'omf'
```

**Comment by bpinto** [comment]
It seems like you have had an issue when running `git pull`:

> <<<<<<< Updated upstream

These are git conflicts.

You could run `git checkout master; git reset --hard origin/master` to fix it, but it would delete all the changes you have done locally to your git repo.

**Comment by simonbcn** [comment]
:+1:
