### ISSUE TITLE
Question mark

### ISSUE THREAD

**Issue by sajt** [oh-my-fish/oh-my-fish#176]
I installed some themes (agnoster, bobthefish), but I get a question mark in my prompt (I think this is a rectangle). Here is a picture:
![1_____fish_](https://cloud.githubusercontent.com/assets/300659/11297802/25f28836-8f7b-11e5-989c-9e5bc4d14d16.png)

**Comment by lfiolhais** [comment]
Have you installed a powerline patched font?

**Comment by bucaran** [comment]
@sajt [Powerline Fonts](https://github.com/powerline/fonts)
