### ISSUE TITLE
what is the load order of packages

### ISSUE THREAD

**Issue by dfang** [oh-my-fish/oh-my-fish#177]
i have these contents on my bundle file:
```
package bundler
package nvm
package brew
package rbenv
```

no matter i change the order of package brew and rbenv, echo $PATH always indicates rbenv paths in front of brew paths.

but i want brew paths to be in front of rbenv paths.

thanks !

**Comment by bpinto** [comment]
We don't really use the order of that file to load the packages, we might want to do that.

I use both `brew` an `rbenv`, why do you require a specific order? I used to have this problem but I don't have anymore.

**Comment by dfang** [comment]
eg. i've installed chef by rubygems before, then i installed the new chefdk by brew cask, i want to run `knife solo ....`  instead of  `/usr/local/bin/knife solo ....`

thanks !

**Comment by dfang** [comment]
@bpinto i just need to add `eval "$(chef shell-init SHELL_NAME)"` to my ~/.config/config.fish. 

thanks !

**Comment by bpinto** [comment]
That's good to know! We should support loading orders though. :+1:
