### ISSUE TITLE
sed - Invalid character class name

### ISSUE THREAD

**Issue by jzsh2000** [oh-my-fish/oh-my-fish#184]
I got this error message after typing `omf theme`.

    ⋊> ~ omf theme
    sed: -e expression #1, char 45: Invalid character class name

### Additional infomation

    ⋊> ~ fish --version
    fish, version 2.2.0
---
    ⋊> ~ sed --version
    sed (GNU sed) 4.2.2
    Copyright (C) 2012 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Written by Jay Fenlason, Tom Lord, Ken Pizzini,
    and Paolo Bonzini.
    GNU sed home page: <http://www.gnu.org/software/sed/>.
    General help using GNU software: <http://www.gnu.org/gethelp/>.
    E-mail bug reports to: <bug-sed@gnu.org>.
    Be sure to include the word ``sed'' somewhere in the ``Subject:'' field.

**Comment by jzsh2000** [comment]
The error message described above is from a OSX (10.11.1) environment. `fish` and `gnu-sed` are installed through `brew install` command. I rebuilt `fish` and `gnu-sed` from source manually, but this error message remains.

I don't know why, but this problem was solved by alias `sed` to the system default version:

    ⋊> ~ alias sed /usr/bin/sed
    ⋊> ~ omf theme
    agnoster                fox                     plain
    agnoster-mercurial      gianu                   red-snapper
    ......

**Comment by bpinto** [comment]
I'll install `sed` on my computer using `brew` to see if I can find anything, but seems like the brew version is not compatible.

**Comment by derekstavis** [comment]
Are this issue still alive @jzsh2000 ?

**Comment by jzsh2000** [comment]
After running `omf update`, the `omf theme` command don't generate error message any more. It seems this issue was fixed. @derekstavis

**Comment by derekstavis** [comment]
Thanks @jzsh2000!
