### ISSUE TITLE
Changes to PATH and new shells

### ISSUE THREAD

**Issue by ViViDboarder** [oh-my-fish/oh-my-fish#186]
Inside a fish shell, any changes to the `PATH` are not reflected on any new shells. Eg:
```
$ set -x PATH /foo/bar $PATH
$ echo $PATH
  /foo/bar <rest of path>
$ fish
$ echo $PATH
  <rest of path>
```

Inside `init.fish` there is a block near the top with the following:
```
# Save PATH before oh my fish for reseting the PATH when we reload OMF.
if set -q ORIGINAL_PATH
  set PATH $ORIGINAL_PATH
else
  set -gx ORIGINAL_PATH $PATH
end
```

It seems that the intended functionality here is to prevent OMF scripts from duplicating additions to the `PATH` when reloading. The (likely) unintended functionality is that it blocks any edits to the `PATH` regardless of them originating from OMF.

For now I have added `set -e ORIGINAL_PATH` in my own `init.fish` script to prevent this behavior, but I'm thinking there should be a better way to accommodate the desired effect without sacrificing other edits.

**Comment by bpinto** [comment]
Perhaps do your PATH changes inside a plugin? Is there a reason why it needs to be dynamic?

As I like automating everything, I'd try to create a plugin for it.

**Comment by ViViDboarder** [comment]
That doesn't work for one off type changes. Granted, it's not often done, but if you use something like `virtualenv` with Python and you want to have a local path, it's impossible to do within a plugin because it's after init. You're just trying to change the path for the current and any sub shells.

**Comment by bpinto** [comment]
I don't know what is the best solution here...

You could change `$ORIGINAL_PATH` environment variable by adding the PATH you would like to have available on sub shells... 

If I'm not wrong though, newer versions of fish support changing another variable but PATH to add custom functions, omf could use this... Does anyone know anything about this?

**Comment by ViViDboarder** [comment]
Is the code I have highlighted here really needed? OMF itself does not make changes to the `PATH`, so why should OMF be resetting it? If a user wants to make path changes in their OMF init files, they should can still do so themselves.

For instance, in my OMF config I can set a variable for `IS_PATH_SET` as a boolean value and then skip setting my path twice in my own configuration.

This solution puts the control in the hands of the user as well as solves the problem I mentioned above. I will not see duplicate values on my path and any values I add in-between loads will stay there and not be reset.

I'm not sure what the best choice for the most users here, but it seems weird that this decision is made for the user in OMF and not up to the user to implement if they chose.

**Comment by bpinto** [comment]
This is required anytime we refresh the shell, e.g when installing a new package.

"More" information can be found on the commit message https://github.com/oh-my-fish/oh-my-fish/commit/2ac89b5a1cf11aace24eb5bfc1a1d11c50af3b7b

We are reducing the refresh calls, but we haven't found a way to remove it completely. It ends up duplicating PATH without that code...

For the framework, it's easy to add a check so that we don't add duplicated PATHs but it would be unexpected for uses I believe.

I'll play with it a little bit and reply here after.

**Comment by simonbcn** [comment]
I've same problem. There are an inexistent path and others unnecessary paths. I have to change  ORIGINAL_PATH to can change PATH. I think is a little absurd.

**Comment by simonbcn** [comment]
Moreover, `omf` blocks the behavior of   [$fish_user_paths universal variable](http://fishshell.com/docs/current/tutorial.html#tut_path).  It ignores this variable. `omf` shouldn't interfere in this environment variables.

**Comment by derekstavis** [comment]
As far as I know, currently Oh My Fish doesn't mess with `$fish_user_paths` variable.

**Comment by simonbcn** [comment]
Yes, it does. Fish shell appends the `$fish_user_paths` variable to `$PATH`  but `omf` updates the PATH with its `$ORIGINAL_PATH`.
I have comment these lines:
```
# Save PATH before oh my fish for reseting the PATH when we reload OMF.
if set -q ORIGINAL_PATH
  set PATH $ORIGINAL_PATH
else
  set -gx ORIGINAL_PATH $PATH
end
```
and now it works.

**Comment by iven** [comment]
I have the same problem. I use [pew](https://github.com/berdario/pew) to manage VirtualEnv, and it modifies $PATH internally.

**Comment by derekstavis** [comment]
Please give a try at PR #230 and report possible side-effects. If you do find duplication in `PATH`, please investigate and report the misbehaving plugins.
