### ISSUE TITLE
Make theme- prefix no longer required for theme packages

### ISSUE THREAD

**Issue by edouard-lopez** [oh-my-fish/oh-my-fish#191]
_Original title: How to install 3rd-party theme?_

---

I tried to install the fish-port of [`pure` theme](https://github.com/rafaelrinaldi/pure) without success. I tried the following commands:

```
omf install https://github.com/rafaelrinaldi/pure; omf theme pure
omf install https://github.com/rafaelrinaldi/pure.git; omf theme pure
omf install https://raw.github.com/rafaelrinaldi/pure/master/fish_prompt.fish; omf theme pure
```

all failed. What is the correct way to do that?

**Comment by bpinto** [comment]
Hi, I'm sorry but the package name does not conform to the rules. In order for omf to understand that the package is a theme, it needs to have a prefix theme-

So you would have to rename the repository from pure to theme-pure.

**Comment by bobthecow** [comment]
it seems like, for third party url-based installs, we should support no prefix at all as well.h

**Comment by derekstavis** [comment]
I agree, then we would need to support:

```fish
omf install --theme URL
omf install --plugin URL
```

**Comment by bobthecow** [comment]
Yep. Have it work as currently implemented for `omf install`, and if there's no prefix have it prompt the user to install with `--theme` or `--plugin`

**Comment by edouard-lopez** [comment]
Making the `theme-` prefix would solve [our situation](https://github.com/rafaelrinaldi/pure/issues/3) where we are wondering if you need to submodule the theme in a fork repo just to be omf compatible.

**Comment by bucaran** [comment]
Hi! @edouard-lopez Check out [Fisherman](https://github.com/fisherman/fisherman), there you can install any themes or plugins (including OMF) without restrictions.

```fish
fisher install rafaelrinaldi/pure
```

**Comment by bucaran** [comment]
https://github.com/oh-my-fish/oh-my-fish/issues/191

Hi! @edouard-lopez Check out [Fisherman](https://github.com/fisherman/fisherman), there you can install any themes or plugins (including OMF) without restrictions.

**Comment by bucaran** [comment]
Hi! @edouard-lopez You can also check out [Fisherman](https://github.com/fisherman/fisherman), there you can install any themes or plugins (including OMF) without restrictions.

```fish
fisher install rafaelrinaldi/pure
```

**Comment by bucaran** [comment]
Hi! @edouard-lopez You can also check out [Fisherman](https://github.com/fisherman/fisherman), there you can install any themes or plugins (including OMF) without restrictions.

```fish
fisher install rafaelrinaldi/pure
```

**Comment by sagebind** [comment]
Re-labeling as an improvement:

_Make the `theme-` prefix no longer required for themes._
