### ISSUE TITLE
porting theme to omf: sourcing utilities

### ISSUE THREAD

**Issue by edouard-lopez** [oh-my-fish/oh-my-fish#193]
I'm working to port the [`pure` theme](https://github.com/rafaelrinaldi/pure) to OMF but got a stupid error
    __parse_current_folder: command not found
    ~/.local/share/omf/themes/pure/fish_prompt.fish (line 1): __parse_current_folder
                                                              ^
    in command substitution
            called on line 31 of file ~/.local/share/omf/themes/pure/fish_prompt.fish
    
    in function “fish_prompt”
            called on standard input
    
    in command substitution
            called on standard input
    
    __parse_current_folder: command not found
    ~/.local/share/omf/themes/pure/fish_title.fish (line 1): __parse_current_folder
                                                             ^
    in command substitution
            called on line 5 of file ~/.local/share/omf/themes/pure/fish_title.fish
    
    in function “fish_title”
            called on standard input
    
    in command substitution
            called on standard input
    
### Question 

Could someone review why the [sourcing doesn't work](https://github.com/edouard-lopez/theme-pure/blob/b1e7e296a9a7bd6be9f7362a18b34deeb7440f81/fish_prompt.fish#L30)?

**Comment by derekstavis** [comment]
You just have to place one function per file, which name should match function's, with `.fish` extension and you are done!
