### ISSUE TITLE
Add key bindings from plugins

### ISSUE THREAD

**Issue by oranja** [oh-my-fish/oh-my-fish#211]
I ran into a problem while trying to port zsh's sudo plugin to Fish. Would like to hear your ideas.
The point of the sudo plugin is to provide a keyboard shortcut for toggling the `sudo` command in the beginning of the current (or last) command. For this matter, the plugin obviously needs to `bind` a key-sequence when it is loaded.
Alas, as noted in fish-shell/fish-shell#230, any `bind` called from within `config.fish` (and anything sourced by it, all the way down to the `init_{plugin}` event handler) gets overwritten shortly afterwards. So to set custom keybindings, the user must define a `fish_user_key_bindings` function (even from within `config.fish` is ok) and make the desired `bind`s there.

You can head over to my [repository](https://github.com/oranja/omf-plugin-sudope/blob/master/init.fish) and see how a possible workaround looks like, but I warn you: It is invasive. Fortunately, it won't be just a waste of time if a lesson is learned from all the messing around:

1. I suggest that OMF should emit an event which calls for plugins to set their keybindings. The hurdle here is that it should be done from the `fish_user_key_bindings` function, which may have already been set by the user (in `fish.config` or a custom function). Even if the only immediate solution is an ugly hack, I claim that it's better if it's in OMF's trusted hands than if it's left to each plugin author to solve. Ultimately, OMF should not settle with how things are. Asking for cooperation from the fish-shell people might provide a much better solution.
2. Due to how autoloading works in Fish, it's not enough to put an event handler inside the package. It has to be sourced in time (possibly from the init event handler). This should be dealt with somehow. Luckily, it can be as simple as a note for plugin authors to source the key binding function from the init function. Relevant: fish-shell/fish-shell#845
~~_Edit_: Maybe I am not doing it right, but sourcing from the plugin's `init` (file or function) also does not work properly. My current solution also involves querying the function `functions event_handler > /dev/null` in order for the event handler to be registered and invoked upon the corresponding `emit`.~~

**Comment by bpinto** [comment]
Your problem with the init function is probably due to how we are using events handlers.

For each plugin we source the init file and then we emit the init event. Every plugin that defines a init function overwites the previous plugin init function causing the event to no longer have a handler.

**Comment by oranja** [comment]
I know. I've seen the `require` code.
The init gets called, but sourcing another file doesn't always work. I think it's related to the working directory. Now when I think of it, the obvious way is to use $OMF_PATH. For some reason it didn't occur to me earlier and I gave up on absolute paths too soon.

In this regard, are all plugin init failures discarded on purpose or just out of laziness?

**Comment by bpinto** [comment]
I would say laziness. One might say simplification. 😅

**Comment by oranja** [comment]
OK, but perhaps we should stick to the original issue: How are you with the idea of emitting an `omf_bind_keys` event from `fish_user_key_bindings`? Does it fall in the scope of OMF's reasonable responsibilities (I think it clearly does)? Can you think of viable alternatives or good ways to implement it? (because what I have in mind and as a temporary workaround is not pretty)

(See slack message about `require`)

**Comment by bpinto** [comment]
I will play with during the week in order to have an opinion. I have never used any key binding.

**Comment by oranja** [comment]
Adding a note here to prevent future frustration:
If implementing in `init.fish` and checking for existing `fish_user_key_bindings`, the check must come before these lines:
```fish
41: set -l user_function_path $fish_function_path
42: set fish_function_path[1] $OMF_PATH/lib
```
Because `fish_user_key_bindings.fish` can be expected to reside in `~/.config/fish/functions/` and these two lines take it out of the autoload list.

**Comment by derekstavis** [comment]
Please check 6295973 for native key bindings support in OMF

**Comment by Ramblurr** [comment]
Did this commit get merged?

**Comment by oranja** [comment]
Not exactly 6295973, but setting key-bindings through plugins is supported in the awesome #260 PR by @derekstavis, which was merged two weeks ago.

From the merge comment:

> Also supports key bindings by sourcing
$OMF_CONFIG/key_bindings.fish and also key_bindings.fish in
packages (plugins and themes) root directories. This is done
when fish_user_key_bindings is called.

So if you're authoring a plugin and you need to set some key-bindings with it, you can simply create a `key_bindings.fish` file in the plugin's top folder and put your `bind` commands in this file.

**Comment by coderstephen** [comment]
Closing since this feature has landed!

**Comment by derekstavis** [comment]
I'd like to add that since #334 even themes get correct key bindings loaded when switching themes!

Check the awesome themes and plugins which already implement key bindings:
* https://github.com/oh-my-fish/theme-budspencer
* https://github.com/oh-my-fish/theme-dangerous
* https://github.com/oh-my-fish/plugin-expand
