### ISSUE TITLE
omf describe: Some plugins lack descriptions

### ISSUE THREAD

**Issue by simonbcn** [oh-my-fish/oh-my-fish#212]
There are several plugins without any info with `omf describe`: 

```
$ omf describe composer
null
$ omf describe mix
$ omf describe stamp
$ omf describe vundle
null
```

**Comment by unusedPhD** [comment]
i've started adding issues to the plugins that currently lack descriptions with recommendations.

**Comment by oranja** [comment]
:+1:

btw, `stamp` points to a 'wa' repository which no longer exist. Does anyone has any idea what the plugin was for?
https://github.com/wa/pkg-stamp

**Comment by derekstavis** [comment]
You can ignore the wa namespaced repositories. They were inherited from a brother framework, and most of them aren't compatible anymore.

**Comment by bucaran** [comment]
@oranja That plugin was created mostly for testing purposes when I first started released Wahoo. You can safely delete it from the package list.

**Comment by bpinto** [comment]
Thanks @unusedPhD that's a great idea.

**Comment by sagebind** [comment]
This is now easily solvable by the organization maintainers and by the community with the merging of #427. Open a pull request on https://github.com/oh-my-fish/packages-main to add descriptions and other info on packages.
