### ISSUE TITLE
plugin bang-bang not functional

### ISSUE THREAD

**Issue by unusedPhD** [oh-my-fish/oh-my-fish#215]
attemp to used after install resulted in following output

    sudo !!
    [ sudo ] password for user:
    sudo !!: command not found

**Comment by unusedPhD** [comment]
Problem is caused if `~/.config/fish/functions/fish_user_key_bindings.fish` file already exists.

One solution was to concat the contents of the plugin `fish_user_key_bindings.fish` into the existing file.

**Comment by oranja** [comment]
I think it should be solved globally by OMF and not require user intervention.
Related: #211
