### ISSUE TITLE
Some themes should add the explicit -g flag to declare global variables

### ISSUE THREAD

**Issue by fishfreedom** [oh-my-fish/oh-my-fish#223]
To quote @bobthecow from this PR: https://github.com/oh-my-fish/theme-bobthefish/pull/19

> I'd actually prefer to make all of these local variables, but since fish doesn't support private functions they're script local. __bobthefish_current_bg is intentionally global, the rest are more of a constant than anything else, so I'd strongly prefer them not to leak. I don't know if there's a better way to handle it, though, so I'm open to suggestions (or to using globals, if that's really the only way).

While the sentiment is legit, the fact is these variables **are** global regardless of one's preferences, because that's just how fish works. By adding the `-g` you add compatibility to `fundle` and other systems without breaking OMF along the way.

Related:
+ https://github.com/oh-my-fish/theme-bobthefish/issues/18
+ https://github.com/oh-my-fish/theme-bobthefish/pull/19
+ https://github.com/fisherman/fisherman/issues/4

**Comment by derekstavis** [comment]
Theme creators are free to define their own interfaces, and as far as themes work with Oh My Fish we are good to go. I'm closing this as it's unrelated to Oh My Fish framework.
