### ISSUE TITLE
Using pure fish prompt

### ISSUE THREAD

**Issue by rif** [oh-my-fish/oh-my-fish#227]
Hi guys,

I am new to fish and oh-my-fish. I am trying to use pure fish theme (https://github.com/rafaelrinaldi/pure):

⋊> ~ omf list                                                           
default		fish-spec	pure
fasd		fzf		

⋊> ~ omf theme pure                                                     
Theme not installed!
Install it using omf install pure

⋊> ~ omf install pure                                                   
Error: pure package already installed.

I installed it with omf install https://github.com/rafaelrinaldi/pure, I can force it by overwritting fish_prompt but I am not sure what is the right way to use it through omf.

Thanks for the great tool,
-rif

**Comment by bpinto** [comment]
Hey @rif 

I'll investigate it now!

**Comment by bpinto** [comment]
The problem is that omf doesn't know if this is a theme or a plugin. It defaults to `plugin`.

Check this issue https://github.com/rafaelrinaldi/pure/pull/5

**Comment by rafaelrinaldi** [comment]
@rif @bpinto Hey guys, since I don't use `omf` I'm not aware of what needs to be done from my side in order to function well with it. @edouard-lopez made a [fork of my repository](https://github.com/edouard-lopez/theme-pure), renamed it, made compatibility changes and published to `omf`. I have no idea if it's working or not but I'm willing to help if needed, I just need some guidance.

**Comment by edouard-lopez** [comment]
@rif you can [install it using my fork](https://github.com/edouard-lopez/theme-pure) of @rafaelrinaldi  repo : 

    omf install https://github.com/edouard-lopez/theme-pure.git

I updated the code to be compatible with `omf` structure.

**Comment by edouard-lopez** [comment]
@rafaelrinaldi thanks :)

I'll submit my repo to the omf theme list to prevent further problem to people.

**Comment by rafaelrinaldi** [comment]
@edouard-lopez As far as I can see, the only thing you did besides renaming the repository was to split all the functions into individual files. Is that an `omf` requirement? If not, I can add you as a maintainer of the original repository and we can all be happy together :sparkles: 

That would also avoid maintainance trouble in the future. What do you think?

**Comment by rafaelrinaldi** [comment]
@edouard-lopez check @bpinto's comment [here](https://github.com/rafaelrinaldi/pure/issues/3#issuecomment-168686565). I think it's better if we do the merge once for all.

**Comment by rafaelrinaldi** [comment]
@edouard-lopez I'm going to work on this tonight and will let you know. Do not publish your fork to the registry otherwise it'll require an update tomorrow :+1: 

Also adding you as a main contributor to `pure`.

**Comment by edouard-lopez** [comment]
@rafaelrinaldi better merge back to your repo then. I'll update the pull request and resubmit then

**Comment by rafaelrinaldi** [comment]
@edouard-lopez 
![alright](https://i.cloudup.com/10SZU3zINn.gif)

**Comment by bpinto** [comment]
Thanks @rafaelrinaldi @edouard-lopez for pairing on this!
