### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by Alsan** [oh-my-fish/oh-my-fish#229]
I'm running into this problem:

    '->$ omf install brew
    Installing package brew
    ssh: Could not resolve hostname \033[38;5;15mhttps: Name or service not known
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    Could not install package brew.

So, what can I do? giving up omf?

**Comment by derekstavis** [comment]
> So, what can I do? giving up omf?

Don't give up so easily, let us help you! :smiley: 

Please feed us with the following information:

+ The output of `cat $OMF_PATH/db/pkg/brew`
+ Are you sure your DNS server is working?
  - Try `nslookup github.com`

**Comment by Alsan** [comment]
- Do this happen on any package or just on this specific?
Yes, all packages, including themes, and all the time since my first try of omf.

- The output of cat $OMF_PATH/db/pkg/brew
https://github.com/oh-my-fish/plugin-brew

- Are you sure your DNS server is working?
Yes, and No. A little bit complicated here. I'm living in China, and there's a GFW here. I've to setup my private dns proxy and use some trusted (I belive) open dns server as my upstream server. BTW, I'm pretty sure github.com is not affected by GFW, can't be sure others.

**Comment by oranja** [comment]
Alsan, what is your OS/distribution? What terminal are you using?

**Comment by derekstavis** [comment]
>I've to setup my private dns proxy and use some trusted (I belive) open dns server as my upstream server.

Have exported `http_proxy` and `https_proxy` variables into your shell?

**Comment by Alsan** [comment]
- what is your OS/distribution?
  I'm using Linux Mint 17.2 XFCE, and xterm as my default terminal.

- Have you exported http_proxy and https_proxy variables into your shell?
  No, I'm using VPN most of the time. The problem exists w/wo VPN.

My conclusion to the problem is the prompt color code settings is mixing up with the target url, but I don't know how to trace the running script.

**Comment by oranja** [comment]
`\033[38;5;15` is indeed an [escape code](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) (`\033[`) meant to set the foreground color (`38;5;`) to white (`15`). It should be supported by terminal emulators which support 256 colors. **xterm-256color** being one of them

The big mystery is how did this color code get inserted before the URL of the package repository?
* Do you have any custom wrapping on the `cat` command?
What is the output of `type cat`?

* Is your TERM set correctly?
What is the output of `echo $TERM`?

* And does your terminal support -256color mode?
How does the output of this line look like?
`echo -e "\033[38;5;15mhello\e[0m world"`

**Comment by Alsan** [comment]
- Do you have any custom wrapping on the `cat` command?

  Yes, I'm using a wrapper which wrap the `pygmentize` as the `cat` command, and after I rename the `cat` wrapper, the problem gone.

Thanks to @oranja, and thanks to @derekstavis.

**Comment by derekstavis** [comment]
Awesome! Thanks @oranja!

**Comment by oranja** [comment]
@Alsan I'm using [source-highlight] for code highlighting in `less`, and [grc]/[plugin-grc] for everything else. I'm pretty happy with my colorful shell. (which reminds me I still have to arrange syntax highlighting for Fish scripts in source-highlight).
Back to the issue at hand, what `grc` does, and you should consider too if you want to keep the `cat` wrapper, is to check if `stdout` is a _tty_. This way, when the output is piped or the command is called within command substitution (not a _tty_), the output is not colorized.

    --colour=auto
        will  test  if  standard  output  is  a  tty,  and colourise only when it is.
(From http://manpages.ubuntu.com/manpages/hardy/man1/grc.1.html)

In Fish you have the [`isatty`] command which can prove useful in this case :wink:
Good luck :four_leaf_clover: 

[source-highlight]: http://www.gnu.org/software/src-highlite/source-highlight.html
[grc]: https://michaelheap.com/grc/
[plugin-grc]: https://github.com/oh-my-fish/plugin-grc
[`isatty`]: http://fishshell.com/docs/current/commands.html#isatty

**Comment by derekstavis** [comment]
Oh My Fish code could be fixed to avoid this issue. Replacing all `cat` with `command cat` would solve this.

**Comment by oranja** [comment]
We should try, but it's the kind of stuff that's hard to enforce. You have
external plugins, for example, which you can't and wouldn't want to control.
For similar reasons, it's pretty much a linux standard to drop output
formatting when not writing to a terminal.

**Comment by Alsan** [comment]
@oranja thanks for the tip. I've just install grc after omf install functioning, and it works almost perfect, except the cat commnad, the output of cat is plain board text, just like without grc installed, I've to use the renamed cat wrapper to output cat content with highlight.

I didn't use source-highlight, I might give it a try later.

Thanks.
