### ISSUE TITLE
Implement Markdown Styleguide? 

### ISSUE THREAD

**Issue by demidovakatya** [oh-my-fish/oh-my-fish#239]
Hi there, 

I've been looking through the documentation/readme with intention to improve them a little. 

From my point of view, this [Markdown Styleguide](https://github.com/carrot/markdown-styleguide) would make the docs more readable and structured (and maybe understand if something important is missing). So, I wanted to know your opinion :rabbit:

**Comment by oranja** [comment]
It would have been great if there was some tool to check markdown style on commits.
Anyway a first step is indeed to pick one style. The one you suggest looks pretty standard to me. I don't have any objections to what's in it. What's missing from it, though, is some kind of reference to APIs. This is perhaps the most important aspect in OMF's docs.

There's also the more vital task of updating docs to reflect current code.
It shouldn't be very hard to keep `omf help` texts synchronized with the readme. The same goes for usage texts.

**Comment by demidovakatya** [comment]
> There's also the more vital task of updating docs to reflect current code.

Would you create an issue for that?

> What's missing from it, though, is some kind of reference to APIs. 

What do you mean? (an example would be awesome)

**Comment by oranja** [comment]
> Would you create an issue for that?

It's a good idea. I will open an issue later today.

> an example would be awesome

Of course. Look at the [Getting Started] section in README.md. This is OMF's API. It's everything that OMF enables its end-users do with it. It's OK as it is, but it's not so uniform, and so I believe it would benefit from some definitions in a style guide.
I can't find a good example of a Markdown API doc that looks the way I would want it to be, but they come in different flavors: Some API docs have more categories, some have a table of content (like in OMF's Themes.md). Some list a reference of all the available commands in a single block and only below that each command is elaborated. Etc...

[Getting Started]: https://github.com/oh-my-fish/oh-my-fish/blob/master/README.md#getting-started

**Comment by demidovakatya** [comment]
I've already been thinking how about this. And yes, OMF Docs styleguide should be more than the Markdown Styleguide I've mentioned.

> It would have been great if there was some tool to check markdown style on commits.
Something like [this](https://circleci.com/features/) works just fine.

todo:
1. Create the OMF Docs Styleguide.
2. Add a testing tool.

**Comment by oranja** [comment]
Oh-My-Fish already has a Continuous Integration server. https://travis-ci.org/oh-my-fish/oh-my-fish
What's missing is the actual style checker.
There are some tools in existence that check coding style and are highly configurable, so they might even fit Markdown requirements. I will look into it if I have time, but I admit it's lower in my priorities right now.

**Comment by bobthecow** [comment]
:+1: to the idea of a style guide, but I disagree with almost everything in that particular markdown style guide :)

**Comment by demidovakatya** [comment]
@oranja right, I forgot OMF has Travis :flushed: 
There's also [this page](https://github.com/oh-my-fish/oh-my-fish/wiki/Code-style-guide) in wiki, so when the Code style guide comes, a style checker would be nice. :smiley: 

@bobthecow could you explain why? :)

**Comment by bobthecow** [comment]
@demidovakatya because it hates whitespace, among other things:

> * Never use consecutive blank lines outside of code samples. A single blank line is always enough in Markdown.



> * Headers should not be followed by a newline unless the element following it requires a preceding newline



> Horizontal rules should span 80 characters for readability.



> * Lists should not be preceded by a newline, unless it follows an item that needs a newline after it (like code or another list).

**Comment by demidovakatya** [comment]
@bobthecow well, haters gonna hate (and make delirious rules like these)

Can we take the Markdown styleguide and remove unnecessary rules from it?

**Comment by sagebind** [comment]
Closing due to staleness. The docs have been improved since this issue was created, though no formal style guide was adopted. Re-open if we wish to discuss further.
