### ISSUE TITLE
Themes throw errors

### ISSUE THREAD

**Issue by goldquest** [oh-my-fish/oh-my-fish#253]
Hi there,
love fish and oh-my-fish!

Wanted to update oh-my-fish, to make use of the omf command.
Now, when I want to install/switch to a theme, I get different errors.

Trying to switch to theme es
```
fish: Unknown command 'string'
~/.local/share/omf/themes/es/fish_title.fish (line 7):   string replace -r '^'"$realhome"'($|/)' '~$1' $PWD
```

Batman:
```
fish: Unknown command 'fst'
~/.local/share/omf/themes/batman/fish_prompt.fish (line 1): fst
```
and
```
fish: Unknown command 'off'
~/.local/share/omf/themes/batman/fish_prompt.fish (line 1): off
```
and
```
fish: Unknown command 'snd'
~/.local/share/omf/themes/batman/fish_prompt.fish (line 1): snd
```

Any Ideas, what went wrong?
These commands are not documented in the fishshell...
Any help would be greatly appreciated.

**Comment by derekstavis** [comment]
About theme `es`, you need fish from git master. It uses a new builtin `string`, which is available only on master. About theme `batman`, it's kinda bad designed, as `fst`, `snd` and `off` functions are defined at `fish_greeting` function, which is called only if you haven't disabled the greeting message, thus causing this errors.

**Comment by goldquest** [comment]
Ah I see. Thank you very much for your help.
The theme `es` should maybe have another fish version tag then. I updated to v2.2.0, because I saw it.
Thanks again and have a good day
