### ISSUE TITLE
infinit loop

### ISSUE THREAD

**Issue by proutek** [oh-my-fish/oh-my-fish#256]
i leave here an issue beacause you have two infinite loop, one at the installation at the line 128

`
fish -c "omf install"
`

and an other in the init.fish at the line 53
`
source $OMF_CONFIG/init.fish ^/dev/null
`

**Comment by oranja** [comment]
Hi @proutek. Thanks for the feedback!
These are not infinite loops. Let me explain so you can rest assured.

1. `fish -c "omf install"`
The [bin/install] script is only run once to install Oh-My-Fish. What you see in line 128 is a call to `omf install`, which doesn't install Oh-My-Fish itself. `omf install` checks the _bundle_ file and installs any plugins or themes listed in it. Your confusion might stem from the function name in *bin/install* - `install_omf` - being similar to `omf install`.

2. `source $OMF_CONFIG/init.fish ^/dev/null`
Oh-My-Fish's root directory is stored in `$OMF_PATH`. However OMF also recognizes an `$OMF_CONFIG` directory, where the _bundle_ and _theme_ files are stored, and where you can put your own `init.fish` and OMF will source it if it exists.
There's an issue here with the error redirection, but that's another open matter.

[bin/install]: https://github.com/oh-my-fish/oh-my-fish/blob/master/bin/install

**Comment by proutek** [comment]
oh ok, that right, I've got an issue with an error redirection too and when I comment those lines, the probleme was solved, and the installation was good any way, so that why i was thinking it's an infinit loop

ps: for my defense, it's really look like to an infinit loop for a fish beginner ^^

**Comment by oranja** [comment]
> A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.
> ~ George Bernard Shaw

**Comment by proutek** [comment]
ah ah that's right 

so thx for your answer
