### ISSUE TITLE
pkg or plugin - which is it?

### ISSUE THREAD

**Issue by jhillyerd** [oh-my-fish/oh-my-fish#257]
I've been out of the omf development loop for quite a while... In attempting to use the "omf new pkg" command, I see the README file it generated assumed my github repo would start with "pkg-" but all the oh-my-fish package repos start with "plugin-"

Also, there are some broken links in: https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/en-US/FAQ.md

Is oh-my-fish in the process of migrating from one to the other?

**Comment by bobthecow** [comment]
Yeah, it's in the process of changing, and yeah, you should use `plugin-*` :)

**Comment by coderstephen** [comment]
Closing since the question seems to be answered. If you have any more questions, feel free to reopen or open a new issue. :grinning:
