### ISSUE TITLE
Second sourcing of init.fish in a subshell

### ISSUE THREAD

**Issue by jhillyerd** [oh-my-fish/oh-my-fish#258]
I put a debugging statement in my init.fish, and noticed it was being output twice when starting fish.  I created an empty home directory with a fresh install of omf (no plugins, default theme), and an init.fish that only has the line:

```
echo INIT $SHLVL
```

Logging in with a fresh SSH session gave me the following result:

```
Last login: Thu Feb  4 21:29:44 2016 from 192.168.1.120
INIT 1
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
⋊> ~ INIT 2

⋊> ~ ls -a
./  ../  .config/  .local/
⋊> ~ tree .config/
.config/
├── fish
│   ├── config.fish
│   ├── fishd.archbox
│   └── fish_history
└── omf
    ├── bundle
    ├── init.fish
    └── theme

2 directories, 6 files
⋊> ~                                     
```

Note the "INIT 1" and "INIT 2" statements.  I tried to track down where it was occurring, but I got the exact same source "stack" from both:

```
from sourcing file ~/.config/omf/init.fish
    called on line 53 of file ~/.local/share/omf/init.fish

from sourcing file ~/.local/share/omf/init.fish
    called on line 8 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
    called during startup
```

Does anyone else see this behavior?

**Comment by oranja** [comment]
What is your terminal? Are you using something like **byobu**/**tmux**/**screen**?

I get the same thing, and never really took it seriously, but it does have implications on shell startup times and correctness.

If I just start a new instance of the shell from an existing tab, I get the debug statement once.
However when I open a new tab (I'm using byobu+tmux), I get two new shell instances.
```fish
[~]─> ps -ft
  PID TTY      STAT   TIME COMMAND
10590 pts/5    Ss     0:00 fish -c /usr/bin/fish
10778 pts/5    S      0:00  \_ /usr/bin/fish
```
The first one is probably called as the default shell and is non-interactive. The second one is the interactive shell I'm finally using. So two questions follow:
1. Can we make the first shell act as an interactive shell and avoid the second fork&exec?
2. Can we make OMF boot faster by reducing redundancy? Perhaps we can make some things happen only once. I'm thinking the login shell will be the first candidate. If fish is not used as a login shell, then in the non-interactive parent shell, and only if it hasn't been initialized by the time we get to an interactive shell, it should be initialized with each new instance. I have to study these matters more deeply before I can offer any real change.

[byoubu]: http://byobu.co/
[tmux]: https://tmux.github.io/
[screen]: https://www.gnu.org/software/screen/

**Comment by jhillyerd** [comment]
For the test case, it was just PuTTY going into SSH on an Archlinux box.  When I tried with tmux I did see the two init statements, but with higher SHLVL numbers than the initial SSH session.

Oddly enough, I am trying it from a different Archlinux box now and am not seeing double.  They are both using fish version 2.2.0.

**Comment by derekstavis** [comment]
How are you using tmux? I suspect that it can be caused by `tmux` being executed in `config.fish`, instead as set as a command. In OS X Terminal there's this configuration:

![screen shot 2016-02-05 at 9 07 34 pm](https://cloud.githubusercontent.com/assets/1611639/12861718/879c6f76-cc4c-11e5-8466-c6b30ec88e1d.png)

 If you mark "Run inside shell" you are very likely to see the `echo` twice.

**Comment by jhillyerd** [comment]
It's been a while, and more experimentation is needed. But, I think the cause was: Python not installed.  Each time I logged in, either fish or oh-my-fish was trying to launch the completions generation script in the background.

**Comment by oranja** [comment]
I doubt that this is it. Or maybe we have different issues with the same symptoms.
I have both Python 2 and 3 installed, and still get the two instances of fish.
For me it might has something to do with how `byobu` is launched on every instance of the shell, but I'm pretty certain that it doesn't come from the "Run in a shell" option.

Will update if I find anything.

**Comment by coderstephen** [comment]
Depending on how it is set up, even running tmux from within fish shouldn't run the init script twice. For example, if you're using the [tmux-zen](http://github.com/coderstephen/tmux-zen) package, fish always manages running tmux on startup, but even then `init.fish` is only sourced once. Of course, every tmux pane you open will cause `init.fish` to be sourced one more time.

**Comment by oranja** [comment]
`screen` launched fish for me without sourcing `config.fish` twice, so I'm afraid that this is some kind of `tmux` issue. Following is my current workaround for `tmux`.

Given that Fish is my default shell
```fish
[~]─> cat /etc/passwd | grep $USER
oranja:x:1000:1000:Itzik Ephraim:/home/oranja:/usr/bin/fish
```

The only arrangement that worked to stop sourcing `config.fish` twice was:
* In my default Konsole's profile, I set the initial command to `/usr/bin/fish --login`
* The first line in my `config.fish`:
```fish
[~]─> head -n1 .config/fish/config.fish
status --is-login; and status --is-interactive; and exec byobu-launcher
```
(added by `byobu-enable` and moved by me to the top of the file)
The `--is-login` check here is what made me add `--login` to Konsole's config above.
* The real trick was, for some reason, to **make tmux use bash as the default shell**...
```fish
[~]─> cat .byobu/.tmux.conf
set -g default-shell '/usr/bin/bash'
set -g default-terminal 'konsole-256color'
```

Now when I open Konsole I get:
```fish
[~]─> command ps -ft
  PID TTY      STAT   TIME COMMAND
32765 pts/3    Ss     0:01 /usr/bin/fish
 7537 pts/3    R+     0:00  \_ ps -ft
```
And not:
```fish
[~]─> command ps -ft
  PID TTY      STAT   TIME COMMAND
 9589 pts/3    Ss     0:00 fish -c /usr/bin/fish
10021 pts/3    S      0:00  \_ /usr/bin/fish
10433 pts/3    R+     0:00      \_ ps -ft
```

**Comment by oranja** [comment]
btw, I verified just now that there is really only one `omf` init this way, by adding
```
date >> fish_init.log
```
to the beginning of omf's `init.fish`.

Opening a new tmux window then results in only one time-stamp in `fish_init.log`.

**Comment by goofansu** [comment]
+1. `tmux new-session` will source the configuration again.

**Comment by jhillyerd** [comment]
Just as a clarification, I was seeing this without launching screen or tmux.  There is probably more than one cause, but I haven't been able to repro it.

**Comment by sagebind** [comment]
Closing due to staleness. If you are still noticing this happen, please re-open the issue.
