### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by krzkrzkrz** [oh-my-fish/oh-my-fish#26]
Anyone getting `env: node: No such file or directory`. Am using NVM for Node. But the `node` command is not recognised in Fish. Any suggestions?

**Comment by bpinto** [comment]
Which plugin are you using? When are you having this error message? Please add more details to the problem so we can help out.

**Comment by krzkrzkrz** [comment]
I am trying to start the ember server via `ember server`. Normally in bash, having `source ~/.nvm/nvm.sh` in `.bashrc` will get this working

**Comment by derekstavis** [comment]
@krzkrzkrz NVM is written in bash, thus it will not work seamlessly with fish. I recommend you to use [foreign-env](https://github.com/oh-my-fish/plugin-foreign-env) plugin to run NVM inside fish.

**Comment by krzkrzkrz** [comment]
Would https://github.com/tj/n be a better fit for Fish?

**Comment by krzkrzkrz** [comment]
Also, using `foreign-env`. Installed via `omf install foreign-env`. Where should the following go?
    
    fenv source ~/.nvm/nvm.sh \;

**Comment by derekstavis** [comment]
This line doesn't do anything usable. NVM is implemented as a bash function, so you need to specify a nvm command afterwards:

    fenv source ~/.nvm/nvm.sh \; nvm --help

**Comment by krzkrzkrz** [comment]
@derekstavis which file should that line go?

**Comment by derekstavis** [comment]
This line don't need to be anywhere, you need to use it to switch node versions:

    fenv source ~/.nvm/nvm.sh\; nvm install 0.10

Or to use a specific node version:

    fenv source ~/.nvm/nvm.sh\; nvm use 0.10

But if you need to change to a node version just when you open a new shell:

    echo 'fenv source ~/.nvm/nvm.sh\; nvm use 0.10' >> $OMF_CONFIG/init/fish

**Comment by krzkrzkrz** [comment]
@derekstavis `fenv source ~/.nvm/nvm.sh\; nvm use 0.12.2` is in `~/.config/omf/init/fish`. But `nvm` is an unknown command. Am I missing something?

**Comment by derekstavis** [comment]
Bear in mind that as `nvm` is a bash function it will not be available in fish. Foreign env executes its arguments inside bash, that's why you need to `source ~/.nvm/nvm.sh` everytime. It's on my plans adding a `nvm` plugin to the framework, but as it's dependant upon foreign-env we need to tackle plugin dependency management before.

**Comment by krzkrzkrz** [comment]
Good to know. Closing for now
