### ISSUE TITLE
Switching theme does nothing

### ISSUE THREAD

**Issue by jscheel** [oh-my-fish/oh-my-fish#27]
When switching my theme, nothing changes. Also, some themes throw errors. Fish version 2.1.2, just updated oh my fish. Running on osx 10.9.5.

**Comment by derekstavis** [comment]
Can you please be more specific about the errors you get?

**Comment by jscheel** [comment]
Sure :) First, here's what's happening with themes:
![theme](https://cloud.githubusercontent.com/assets/211478/9740307/ae8d4b7c-5619-11e5-8e37-0e164f26418e.gif)
Second, here's the error I'm getting with the `led` theme:
```
fish: Unknown command 'led::fst'
/Users/jscheel/.local/share/omf/themes/led/fish_right_prompt.fish (line 2): led::fst
                                                                            ^
in command substitution
	called on line 2 of file '/Users/jscheel/.local/share/omf/themes/led/fish_right_prompt.fish',

in command substitution
	called on line 12 of file '/Users/jscheel/.local/share/omf/themes/led/fish_right_prompt.fish',

in function 'fish_right_prompt',
	called on standard input,

in command substitution
	called on standard input,

fish: Unknown command 'off'
/Users/jscheel/.local/share/omf/themes/led/fish_right_prompt.fish (line 2): off
                                                                            ^
in command substitution
	called on line 12 of file '/Users/jscheel/.local/share/omf/themes/led/fish_right_prompt.fish',

in function 'fish_right_prompt',
	called on standard input,

in command substitution
	called on standard input,
```

And when switching to `dangerous`:
```
expr: syntax error
test: Missing argument at index 2
set_color: Expected an argument
switch: Expected exactly one argument, got 0
/Users/jscheel/.local/share/omf/themes/dangerous/fish_right_prompt.fish (line 226):         switch $pwd_style
                                                                                            ^
in function '__dangerous_prompt_pwd',
	called on line 246 of file '/Users/jscheel/.local/share/omf/themes/dangerous/fish_right_prompt.fish',

in command substitution
	called on line 246 of file '/Users/jscheel/.local/share/omf/themes/dangerous/fish_right_prompt.fish',

in function 'fish_right_prompt',
	called on standard input,

in command substitution
	called on standard input,


       switch − switch ‐ conditionally execute a block of commands


switch ‐ conditionally execute a block of commands
   Synopsis
       switch VALUE; [case [WILDCARD...]; [COMMANDS...]; ...] end

switch: Type 'help switch' for related documentation

set_color: Expected an argument
```

**Comment by derekstavis** [comment]
Thanks for the report. We are having some issues with Fish 2.1.x. Maybe upgrading fix your problem?

**Comment by derekstavis** [comment]
Fish 2.2.0 here, Oh My Fish master:

![anim](https://cloud.githubusercontent.com/assets/1611639/9741096/d18f8ecc-562e-11e5-9496-6ab9591e2140.gif)

**Comment by jscheel** [comment]
Hmm, I've update to 2.2.0, but I'm still getting the same results.

**Comment by jscheel** [comment]
`.config/omf/revision` is `5d4b9098fc3783464da826a1215ec555c4cb6018`

**Comment by bobthecow** [comment]
did you change your theme using the fish builtin config at some point?

**Comment by jscheel** [comment]
@bobthecow Using the web config to change the prompt? I did do that.

**Comment by bobthecow** [comment]
Check if there's a file at `~/.config/fish/functions/fish_prompt.fish` (and if so, delete it).

**Comment by jscheel** [comment]
@bobthecow ahhh, that does it. Thanks! Wonder if that could be part of the install process. Have it just move the file to `fish_prompt.fish.backup` or something.

**Comment by derekstavis** [comment]
A `brew doctor`-like functionality to perform this checks would be great too.

**Comment by jscheel** [comment]
Hmm, it's switching themes, but my encoding is jacked up. Guessing I have something set wrong here:
![screen shot 2015-09-08 at 1 54 44 pm](https://cloud.githubusercontent.com/assets/211478/9744403/3e997bde-5631-11e5-85d2-fd9a13518b62.png)

**Comment by derekstavis** [comment]
This is your terminal font not supporting Powerline characters. Give a look at some fonts that support powerline at https://github.com/derekstavis/awesome-font, Monospaced section. I highly recommend Inconsolata.

**Comment by jscheel** [comment]
@derekstavis Ah, thanks! I've used Inconsolata in the past, looks like I need to give it another spin.

**Comment by derekstavis** [comment]
I'm closing the issue as it's solved

**Comment by jscheel** [comment]
@derekstavis do you want to open a new issue as a feature request for the `brew doctor`-esque check for fish_prompt.fish?

**Comment by derekstavis** [comment]
Yes, I will do it! Thanks for remembering :+1:
