### ISSUE TITLE
How to install on win7.

### ISSUE THREAD

**Issue by huagt** [oh-my-fish/oh-my-fish#270]
Hi,

I tried to install fish framework on win7. but I failed! I am using the following command:
curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
(Error log: 'Fish' is not an internal or external command....)

How can I solve this problem?

**Comment by coderstephen** [comment]
Hello, @huagt! Let's check that the basics are in order first. Oh My Fish! is a framework for the [Fish](http://fishshell.com) shell, so you will need to make sure that Fish is installed properly first. For Windows machines, you will almost certainly need to make sure Cygwin is installed and that Fish is in your `$PATH` first.

**Comment by huagt** [comment]
Okay thank you!  I immediately installed.

**Comment by derekstavis** [comment]
@huagt have this issue been solved for you? If yes, feel free to close it.

**Comment by luckyalvinyc** [comment]
@huagt can you please post an instruction on how to install on windows?
