### ISSUE TITLE
Install z

### ISSUE THREAD

**Issue by onmyway133** [oh-my-fish/oh-my-fish#283]
Hi, I just start using fish and am very happy with it, so simple and powerful

I'm using fish 2.2.0 and trying to install z https://github.com/rupa/z

```
brew install z
omf install z
```

but when running z, an error occurs

```
bash: line 0: source: filename argument required
source: usage: source filename [arguments]
bash: _z: command not found
```

How do fix this? Thanks

**Comment by coderstephen** [comment]
I'm not entirely sure of the reason; `z` seems to be working on a fresh install for me. Let's check out your environment. Please if you would, paste the output of each of the following commands:

- `which z`
- `type z`
- `set | grep '^Z'_`

It may be an issue on how the plugin is set up, or an issue in the plugin itself.

**Comment by onmyway133** [comment]
@coderstephen thanks for your prompt reply

`which z` and `set | grep '^Z'_` prints nothing. `type z` prints 

```
z is a function with definition
function z --description 'jump around'
	cd (bash -c "source $Z_SCRIPT_PATH; _z $argv; echo \$PWD")
end
```

`brew install z` prints "z-1.9 already installed" and `omf install z` prints "package z already installed"

**Comment by coderstephen** [comment]
Alright, thank you for that information. According to the [`z` plugin docs](https://github.com/oh-my-fish/plugin-z), you need to manually set `$Z_SCRIPT_PATH` to the location that Homebrew installed `z.sh` to. I don't have a Mac so I can't test it out, but something like the following should work if you put it in `$OMF_CONFIG/init.fish`:

```fish
set -g Z_SCRIPT_PATH (brew --prefix)/etc/profile.d/z.sh
```

**Comment by onmyway133** [comment]
@coderstephen yeah, it works. Didn't know about those `plugin` repos, thanks :tada:

**Comment by coderstephen** [comment]
Glad you got it working! Feel free to open another issue for any other problems or suggestions you may have. :wave:

**Comment by tommyjcarpenter** [comment]
I have this same issue.

**Comment by tommyjcarpenter** [comment]
Adding `set -g Z_SCRIPT_PATH /usr/local/etc/profile.d/z.sh` to my fish config worked for me too.

**Comment by tommyjcarpenter** [comment]
I switched to https://github.com/fisherman/z
