### ISSUE TITLE
How to execute an sh script?

### ISSUE THREAD

**Issue by krzkrzkrz** [oh-my-fish/oh-my-fish#29]
I am using the Gruvbox theme (https://github.com/morhetz/gruvbox) for Vim. All works. However, in `.bashrc`, I have:

    source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"

Which will recalibrate the colors in iTerm.

I have `fenv source ~/.vim/bundle/gruvbox/gruvbox_256palette.sh` in `~/.config/omf/init/fish`, but it doesn't seem to be doing anything.

Am I missing something?

**Comment by derekstavis** [comment]
Fish should works OOB with 256 color palette, so I think this isn't needed.

**Comment by krzkrzkrz** [comment]
You still do: https://github.com/morhetz/gruvbox/wiki/Terminal-specific

**Comment by krzkrzkrz** [comment]
Running `fenv source ~/.vim/bundle/gruvbox/gruvbox_256palette.sh` in a fish terminal, immediately changes the colors appropriately. 

I wonder why it doesnt do the same when placed in `~/.config/omf/init/fish`

**Comment by derekstavis** [comment]
Oh, wrong path, I've fixed on the other issue!! The right is `~/.config/omf/init.fish`.

**Comment by derekstavis** [comment]
Have you tried the right file @krzkrzkrz?

**Comment by krzkrzkrz** [comment]
Ok `fenv source ~/.vim/bundle/gruvbox/gruvbox_256palette.sh` seems to work now! But I think something is wrong with:

    fenv source ~/.nvm/nvm.sh\; nvm use 0.12.2

I get:

    contains: Unknown option '-iqE'
~/.local/share/omf/pkg/foreign-env/fenv.parse.diff.fish (line 30):         if not contains $environment $OLD_ENV
                                                                              ^
    in function 'fenv.parse.diff'
        called on line 25 of file ~/.local/share/omf/pkg/foreign-env/fenv.main.fish

**Comment by derekstavis** [comment]
Boom! You have found a bug in `foreign-env`!! Nothing like real life use for testing!! Thanks!! I'm closing this issue, but you can follow https://github.com/oh-my-fish/plugin-foreign-env history for the fix.
