### ISSUE TITLE
Can't install omf on Mac

### ISSUE THREAD

**Issue by Leolik** [oh-my-fish/oh-my-fish#296]
fish = v.2.2.0
mac = v.10.11.4 (El Capitan)

when I tried install omf I got this error:
```
curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   140  100   140    0     0     92      0  0:00:01  0:00:01 --:--:--    92
100  4654  100  4654    0     0   2084      0  0:00:02  0:00:02 --:--:--  9402
Installing Oh My Fish to /home/leolik/.local/share/omf...
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
fatal: could not create leading directories of '/home/leolik/.local/share/omf': Operation not supported
Error cloning repository!
```

**Comment by derekstavis** [comment]
Thanks for your report! Would you mind pasting the result of the following commands?

```
echo $HOME
echo $XDG_DATA_HOME
```

This will help us identify why your installation is failing. As you're on OS X, the installer should be installing to a path like `/Users/leolik/.local/share/omf`, and not `/home/leolik/.local/share/omf`.

**Comment by Leolik** [comment]
$HOME = /Users/leolik
$XDG_DATA_HOME is empty

**Comment by derekstavis** [comment]
Hm.. Maybe you have `$OMF_PATH` set to something? Is this a clean install?

**Comment by Leolik** [comment]
you right, it's my bug (( I copied config from Ubuntu and forgot remove `$OMF_PATH` from config
@derekstavis thanks

**Comment by derekstavis** [comment]
Cool! You're welcome!
