### ISSUE TITLE
`brew doctor`-like to check if everything is great.

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/oh-my-fish#30]
A `omf doctor` command would be great for checking the sanity of our environment. At this moment there are some checks that come in mind:

* `fish_prompt` overriden by a file? (as arised in issue #27)
* `config.fish` containing `Plugin` and `Theme` (while we don't tackle #7)

@oh-my-fish/core feel free to edit this issue and add more checks.

**Comment by bobthecow** [comment]
:+1:

The `fish_prompt` issue is probably the most common theme-related issue we get, since anyone who tries to customize their prompt via the builtin `config` will run into it after installing omf.

**Comment by bpinto** [comment]
I really like it too!

**Comment by derekstavis** [comment]
A possible output format is:

```
- System Type:
  * Apple OS X
- Current theme:
  * agnoster
- Enabled plugins:
  * brew
  * foreign-env
  * nvm
  * osx
  * title

- Warnings:
  * Overriden prompt at ~/.config/fish/functions/fish_prompt.fish
  * Plugins or Themes defined in ~/.config/fish/config.fish
```

We need to include useful information for using in bug reports. Any other things?

**Comment by bpinto** [comment]
That plugin warning is not enough. We could improve it a little better. Possibly use `brew doctor` as a template to follow.
