### ISSUE TITLE
omf update fails

### ISSUE THREAD

**Issue by andrewrynhard** [oh-my-fish/oh-my-fish#304]
````
$ omf update
Oh My Fish failed to update.
Please open a new issue here → github.com/oh-my-fish/oh-my-fish/issues
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
````

**Comment by andrewrynhard** [comment]
I tried removing the `-C` flag in [__omf.repo.git](https://github.com/oh-my-fish/oh-my-fish/blob/master/pkg/omf/functions/repo/omf.repo.pull.fish#L11) and now I get:

````
$ omf update                                                                                                                                                                                     
git: '/home/vagrant/.local/share/omf' is not a git command. See 'git --help'.
git: '/home/vagrant/.local/share/omf' is not a git command. See 'git --help'.
Oh My Fish failed to update.
Please open a new issue here → github.com/oh-my-fish/oh-my-fish/issues
git: '/home/vagrant/.local/share/omf/themes/default' is not a git command. See 'git --help'.
git: '/home/vagrant/.local/share/omf/themes/default' is not a git command. See 'git --help'.
````

**Comment by oranja** [comment]
You're seem to be using an old version of `git`, while OMF requires `git` 1.9.5 at least.
I notice now that we failed to mention this in the README. I take the blame on me.

What is your current `git` version and which OS are you using?

**Comment by coderstephen** [comment]
My guess is you have an old version of Git. What do you have for

    git --version

**Comment by coderstephen** [comment]
@oranja Haha, we replied at the exact same moment...

**Comment by andrewrynhard** [comment]
````
$ git --version                                                                                                                                                                                  
git version 1.8.3.1
````

**Comment by coderstephen** [comment]
Yeah, like @oranja mentioned, you need Git >=1.9.5 to support the `-C` flag, which OMF needs.

**Comment by andrewrynhard** [comment]
Got it. Thanks!

**Comment by oranja** [comment]
Actually the `-C` flag was introduced in 1.8.5, but we need 1.9.5 for other things we want to support in the future, like shallow cloning.

I'm glad we could help @andrewrynhard.

(@coderstephen: we make a great team! want to work on some FOSS project together? :grin: )

**Comment by coderstephen** [comment]
@oranja We already are, aren't we‽
