### ISSUE TITLE
Adding a plugin to oh-my-fish/oh-my-fish

### ISSUE THREAD

**Issue by andrewrynhard** [oh-my-fish/oh-my-fish#307]
Are you guys open to moving plugins created by non organization members to the official oh-my-fish org?

**Comment by derekstavis** [comment]
Yes. We often encourage and allocate repos. Would you like to move a plugin to organization?

**Comment by andrewrynhard** [comment]
Great! The plugin is https://github.com/andrewrynhard/plugin-rustup.git

**Comment by derekstavis** [comment]
I allocated a repo and made you an admin. Feel free to push the contents and be sure to open a PR here updating the reference. Also be sure to remove the original repository to avoid confusion :)

**Comment by andrewrynhard** [comment]
Done! Thanks for the prompt response.

**Comment by derekstavis** [comment]
Cool! Here we go! Welcome to the organization!! Be sure to always use this repository when pushing changes 😁

**Comment by andrewrynhard** [comment]
Sounds good!

**Comment by derekstavis** [comment]
Also be sure to join us on Slack (https://oh-my-fish-slack.herokuapp.com), we can promptly allocate other repos if you need, and so help you with issues 👌
