### ISSUE TITLE
git_branch_name fails when repo has detached HEAD

### ISSUE THREAD

**Issue by cbennett35** [oh-my-fish/oh-my-fish#312]
git_branch_name calls `git symbolic-ref --short HEAD` to get the branch name of a git repo. This works in most cases, but when a repo is in a detached HEAD state, git_branch_name will spew `fatal: ref HEAD is not a symbolic ref` on stderr. What should happen is, if the symbolic-ref call fails (because there is no symbolic ref), it falls back to `git rev-parse --short HEAD`.

**Repro steps:**
1. Open an omf shell
2. cd to a directory containing a git repo
3. Put repo in detached HEAD state, e.g. with: `git checkout (git rev-parse HEAD)`

**Expected:** prompt shows "on [short commit ID]"
**Actual:** prompt shows "on " (with a blank) and is preceded by the error message `fatal: ref HEAD is not a symbolic ref`

**Comment by coderstephen** [comment]
I'm not sure if this is really an issue with `git_branch_name`... `git rev-parse --short HEAD` doesn't really make sense here since that is not the branch name.

Are you using the default theme? It would be better to fix the command prompt of the desired theme most likely. Opinions @bobthecow?

**Comment by bobthecow** [comment]
bobthefish's version of this function falls back to `git rev-parse --short HEAD`. mostly because it's closest to what the user is _asking for_, even if it's not technically what the function is called :P
