### ISSUE TITLE
Install fail!

### ISSUE THREAD

**Issue by bakiro** [oh-my-fish/oh-my-fish#316]
Good day, sorry for my english, it is the case

`Installing Oh My Fish to /home/server/.local/share/omf...
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Adding startup code to fish config file...
Building Oh My Fish configuration...
fish: Unknown command 'source'
/home/server/.config/fish/config.fish (line 8): source $OMF_PATH/init.fish
                                                ^
in . (source) call of file '/home/server/.config/fish/config.fish',
	called on standard input,

fish: Unknown command 'omf'
Standard input: omf install
                ^
Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues
`

thanks for your help

**Comment by coderstephen** [comment]
Thanks for submitting an issue! I'm not entirely sure what error you are experiencing. Could you paste in the output of the following commands?

- `fish -v`
- `git --version`

**Comment by bakiro** [comment]
Thank's
fish, version 1.23.1
git version 1.7.10.4

I try install on server debian 7

**Comment by coderstephen** [comment]
Ah, I see your problem. You need newer versions of both those programs. The minimum supported version for Git is `1.9.5` and the minimum version of Fish needed is `2.2.0`. Try updating to those versions first, then run the installer.
