### ISSUE TITLE
Needs a document about updating from older versions

### ISSUE THREAD

**Issue by danieljaouen** [oh-my-fish/oh-my-fish#317]
I just recently updated to the newer version (i.e., I was using the old bpinto/oh-my-fish.git) and now all of my Plugins and my custom-made Theme broke.  I don't see anything documenting how to upgrade from older versions, and now my prompt and prior fish-functionality are all broken.  What do?

**Comment by danieljaouen** [comment]
OK, I managed to submit my personal theme, and everything is working except that fish cannot find the "pyenv" and "rbenv" commands (which are required for my theme to work correctly).  See attached pic. 
![pic1](https://cloud.githubusercontent.com/assets/766444/15232950/ad701f32-1872-11e6-86df-ffb2221b7890.png)
![pic2](https://cloud.githubusercontent.com/assets/766444/15232951/ad72c138-1872-11e6-99dd-180ed154a0b0.png)

**Comment by danieljaouen** [comment]
Also, none of my previous aliases are working.

**Comment by danieljaouen** [comment]
I tried replacing the overwritten config.fish with my old config.fish, but now I'm seeing the following error:

"""
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
fish: Unknown command 'git_is_repo'
~/.config/fish/functions/fish_prompt.fish (line 29):   if git_is_repo
                                                          ^
in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

⋊> ~
"""

**Comment by danieljaouen** [comment]
And now ```omf``` doesn't work as a command anymore either.

**Comment by coderstephen** [comment]
Hi @danieljaouen! You must be upgrading from a very old version of OMF to get these errors, and I'm not entirely sure what might have gone wrong. What I can say is that some key directories and file names have been changed since then, so let's try getting at least the init step working.

I'd back up your stuff for now in case anything odd happens before proceeding. First try putting this into `~/.config/fish/config.fish`:

```
# Path to oh-my-fish.
set -g OMF_PATH $HOME/.local/share/omf

# Path to oh-my-fish configuration.
set -g OMF_CONFIG $HOME/.config/omf

### Configuration required to load oh-my-fish ###
# Note: Only add configurations that are required to be set before oh-my-fish is loaded.
# For common configurations, we advise you to add them to your $OMF_CONFIG/init.fish file or
# to create a custom plugin instead.

# Load oh-my-fish configuration.
source $OMF_PATH/init.fish
```

Just to be sure, please also let me know what versions of Fish (`fish --version`) and Git (`git --version`) you are using.

Second, let's move your Oh My Fish! installation to the location that it expects. A while ago we changed where installs are put, to be more XDG compliant. Do this next if your installation hasn't already been moved:

```
mv ~/.oh-my-fish ~/.local/share/omf
```

Please report back if this gets you anywhere.

**Comment by coderstephen** [comment]
I think I see what might be additional causes of problems. It looks like your `~/.config/fish/functions/fish_prompt.fish` file might be using some old functions that are no longer available, causing Fish to give up on the rest of the initialization steps. Try removing it (after backing it up somewhere safe) and try re-opening the terminal.

**Comment by coderstephen** [comment]
For your aliases and functions, I would copy everything after line 3 in https://github.com/danieljaouen/dotfiles/blob/master/topics/fish/config.fish and put it into a script at `~/.config/omf/init.fish`, which should restore your aliases.

**Comment by danieljaouen** [comment]
Adding those few lines you mentioned seemed to fix almost everything.  Now my theme works, but I still get one additional error:

```
fish: Unknown command 'rbenv init -'
~/.local/share/omf/pkg/rbenv/rbenv.fish (line 9):   if command rbenv init - | grep --quiet "function"
                                                               ^
in function 'init'
	called during startup
	with parameter list '/Users/dan/.local/share/omf/pkg/rbenv'

in event handler: handler for generic event 'init_rbenv'

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

+-----------------------------------------------------------------------------
| [dan@macbook] [pwd: ~] [time: 20:42:31]
| [python: 2.7.8, ruby: 2.1.5]
+------------
```-----------------------------------------------------------------
○

**Comment by danieljaouen** [comment]
Also, my ```fish --version```: 
```fish, version 2.2.0```

And my ```git --version```:
```git version 2.8.2```

**Comment by coderstephen** [comment]
That seems to be a `$PATH` issue; I'm not sure how OMF could affect the ability to find `rbenv`.

**Comment by coderstephen** [comment]
Also, those versions should work just fine with latest OMF. :ok_hand:

**Comment by danieljaouen** [comment]
Actually, I managed to fix that last error by putting the additional lines after setting my PATH variable in my config.fish.

Thanks for the help!

**Comment by coderstephen** [comment]
The title of this issue is good, though. I'll add it to our todo list to add an upgrade guide for these things. Maybe we can save someone else a headache. :sweat:

**Comment by SethSanchez** [comment]
I ran into the same problem. This helped out quite a bit.
