### ISSUE TITLE
Package installed but not loaded

### ISSUE THREAD

**Issue by cuekoo** [oh-my-fish/oh-my-fish#320]
I successfully installed a package through
```
omf install <url>
```
The package name then shows in the output of `omf list`. But it is not loaded. How can I solve it?

**Comment by derekstavis** [comment]
What's the package? It may be an issue with the package or it may need additional steps.

**Comment by cuekoo** [comment]
It has been solved. 

It is a self-defined testing package. While editing this answer, I found that the git repository name differs from the `<package_name>` which is used in
```
omf new pkg <package_name> 
```
After correcting, it works.

**Comment by derekstavis** [comment]
Cool! I'm closing this issue, but be welcome to report any other issue you may encounter!
