### ISSUE TITLE
omf.theme.set options

### ISSUE THREAD

**Issue by tannhuber** [oh-my-fish/oh-my-fish#332]
Obviously, it's confusing that the budspencer and dangerous themes need vi key bindings enabled in advance. It should be enabled automatically when a user switches to one of these themes. Where's the best place to include such an option. Is it `omf.theme.set`? I don't want to write it into the theme itself because it shouldn't be executed each time when a user opens a new shell.

**Comment by derekstavis** [comment]
Hi @tannhuber, you can use `key_bindings.fish` in the root of your repository. It will be correctly called in fish's `fish_user_key_bindings` callback.

**Comment by tannhuber** [comment]
That's it. Thank you.
