### ISSUE TITLE
strange characters in prompt

### ISSUE THREAD

**Issue by helloworlderly** [oh-my-fish/oh-my-fish#339]
I install bobthefish and agnoster theme on my macbook. Then I find there are some characters showing messy code

**Comment by derekstavis** [comment]
You need to install a powerline patched font. There are a lot of them available online.

To easily install a powerline font you can use the `fonts` package:

```fish
omf install fonts
```

List all available powerline fonts
```fish
fonts list --available --powerline
```

Install a powerline font
```fish
fonts install Inconsolata
```

Setup your terminal with the installed font and be happy 🍻

**Comment by bobthecow** [comment]
If you're running bobthefish or agnoster, you need to install powerline or nerd fonts patched fonts. See bobthefish docs for more info:

https://github.com/oh-my-fish/theme-bobthefish#installation

**Comment by bobthecow** [comment]
Or what @derekstavis said :P

**Comment by helloworlderly** [comment]
when I execute 
`fonts install Inconsolata`

> wget: missing URL
Usage: wget [OPTION]... [URL]...
Try `wget --help' for more options.
Failed downloading font file
@derekstavis

**Comment by derekstavis** [comment]
Hi @helloworlderly, the right usage for installing powerline fonts is:

```
fonts install --powerline Inconsolata
```

**Comment by oranja** [comment]
After installing a powerline font I believe it is necessary to change the terminal settings such that it actually uses the powerline-patched font. It was also discussed not long ago on omf's gitter that enabling _font smoothing_ or _font anti-aliasing_ makes the glyph rendering even crisper.

**Comment by derekstavis** [comment]
Closing as looks like it's answered. Feel free to comment if you still have any issue @helloworlderly!

**Comment by JensTimmerman** [comment]
I'm still having the wget issue on a brand new Mac, brew install wget fixes this, but it should not be happening? Maybe switch to curl, or install wget first?

**Comment by oranja** [comment]
@JensTimmerman, please open this `wget` issue and suggestions as a new issue over at https://github.com/derekstavis/plugin-fonts/issues

**Comment by agirault** [comment]
What if `fonts list --available --powerline` lists nothing? I also installed [those](https://github.com/powerline/fonts) using the `install.sh` script on MacOS Mojave, along with the [bobthefish](https://github.com/oh-my-fish/theme-bobthefish) theme, but the symbols all show as ` `.
