### ISSUE TITLE
Standard installation fails

### ISSUE THREAD

**Issue by tommyjcarpenter** [oh-my-fish/oh-my-fish#347]
Just following your README with the two straitfiorward commands:

```
~/Development curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install > install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   140  100   140    0     0    683      0 --:--:-- --:--:-- --:--:--   686
100  4719  100  4719    0     0  12793      0 --:--:-- --:--:-- --:--:-- 12793
~/Development fish install
Installing Oh My Fish to ~/.local/share/omf...
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Existent config.fish found at /Users/tcarpent/.config/fish
↳ Moving to /Users/tcarpent/.config/fish/config.1465743261.copy
Adding startup code to fish config file...
Building Oh My Fish configuration...
fish: Unknown command 'omf.cli.install'
~/.local/share/omf/pkg/omf/functions/omf.fish (line 38):       omf.cli.install $arguments
                                                               ^
in function 'omf'
	called on standard input
	with parameter list 'install'

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues
```

**Comment by Memphizzz** [comment]
Same here! For some reason the files from the git repository are in /home/user**/~/**.local/share.
Notice that it installs them into a ~ subfolder of ~. Any fix?

**Comment by coderstephen** [comment]
Seems like another Fish, 2.3.0 issue. What version of Fish are you using?

**Comment by Memphizzz** [comment]
I'm running 2.3.0.

**Comment by tommyjcarpenter** [comment]
The fish developer emailed me personally, in response to this thread, and essentially said "use fisherman and stop using oh my fish because it's no longer maintained", so I uninstalled it. I was already using fisherman and didn't know it was a direct replacement of OMF.

**Comment by Memphizzz** [comment]
Oh, well I didn't know that. Looks like I have to check out fisherman then... Anyway if that's the case the Readme.md should state that...

**Comment by derekstavis** [comment]
@tommyjcarpenter, just a little correction: The Fisherman developer emailed you. Neither Fisherman or Oh My Fish are officially supported by Fish shell developer.

**Comment by oranja** [comment]
And that is like having a call from a Microsoft's salesman telling you to stop using Linux because it is no longer maintained.
It's a lie and it's an ugly predatory marketing technique.

OMF is still maintained, and Fisherman is only a direct replacement to itself (it's been completely rewritten 3 times in the last couple of years).

**Comment by oranja** [comment]
As for this issue, what is your `git --version`?
Memphizzz, are you too using Mac?
I just installed `fish` and `omf` on a brand new laptop and had no such issues, so we need more information to understand what makes your setup stand out.

**Comment by Memphizzz** [comment]
@oranja Thanks for the clarification. This is happening on a Ubuntu 14.04.4 Server. Installed fish via apt. Noticed version 2.0.0. Added the fish repo then updated from fish 2.0.0 to 2.3.0 and tried to install omf using the curl command from the readme.md.

**Comment by Memphizzz** [comment]
Problem successfully solved using git version 2.9.0!

**Comment by tommyjcarpenter** [comment]
I am using fish shell 2.3.0 on OSX10.11.5.

**Comment by oranja** [comment]
It really is time for us to check the git version in the installer and specify the min version in the readme...

@tommyjcarpenter, git version?

**Comment by derekstavis** [comment]
Maybe we should step back our git version? I had an issue on a friend's Mac this week too. OS X ships an older Git by default. Shame on Apple!!

**Comment by tommyjcarpenter** [comment]
~ git --version
git version 2.6.2

**Comment by tommyjcarpenter** [comment]
Git 2.9 was JUST released two days ago, so I'm a little skeptical that @Memphizzz's comment towards  upgrade to 2.9 is the solution.

**Comment by derekstavis** [comment]
@tommyjcarpenter IIRC OS X ships with Git 1.8. Our minimum required version is Git 1.9.5:

https://github.com/oh-my-fish/oh-my-fish/blob/master/pkg/omf/functions/core/omf.doctor.fish#L33

**Comment by coderstephen** [comment]
Git 2.6.2 should be new enough then, so that is not @tommyjcarpenter's issue.

**Comment by tommyjcarpenter** [comment]
Well, I still have the issue stated in my original post in this thread, and I am using fish shell 2.3.0 and git 2.6.2.

**Comment by oranja** [comment]
Yes, so your problem is different than Memphizzz's. Now we still need to figure out what's the problem on your setup.

Did you leave `omf` installed? If so:
- What happens when you start `fish`? any warning/error messages?
- Can you try calling `omf install` again and post the results?

**Comment by tommyjcarpenter** [comment]
I upgraded homebrew's git to 2.9.0, and OMF now installs for me as well.

**Comment by tommyjcarpenter** [comment]
```
~ brew upgrade git
==> Upgrading 1 outdated package, with result:
git 2.9.0
==> Upgrading git
==> Downloading https://homebrew.bintray.com/bottles/git-2.9.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring git-2.9.0.el_capitan.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.9.0: 1,424 files, 31.3M
~ fish install
Installing Oh My Fish to /Users/tommy/.local/share/omf...
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Existent config.fish found at /Users/tommy/.config/fish
↳ Moving to /Users/tommy/.config/fish/config.1466000338.copy
Adding startup code to fish config file...
Building Oh My Fish configuration...
Installing theme default
✔ theme default successfully installed.
Installation successful!
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

**Comment by oranja** [comment]
I'm glad that you got it working too, but I'm still curious, because my `git --version` is 2.5.5 and I haven't seen such issues on my machine.

If anyone else runs into this kind of issue with any git version between 1.9.5 and 2.9.0, please do post your logs and insights here.

**Comment by tommyjcarpenter** [comment]
@derekstavis no problem, hopefully git is on semver and upgrading didn't just blow up my dev system otherhow..

**Comment by tommyjcarpenter** [comment]
Closing due to issue resolvement on git 2.9.0.
