### ISSUE TITLE
Can't set vars except $PATH in  ~/.config/omf/init.fish

### ISSUE THREAD

**Issue by specter119** [oh-my-fish/oh-my-fish#353]
for example i set:

```sh
set -x MAPI_KEY "uEAGXx7TqdgbolM4"
```

and then I

```sh
omg reload
echo $MAPI_KEY
```

i will get a blank row. the vars was set correct before using the same way.

but when i type `set -x MAPI_KEY "uEAGXx7TqdgbolM4"` in terminal, it works.

**Comment by coderstephen** [comment]
Also, see #328.

**Comment by derekstavis** [comment]
Hey @specter119, sorry for the inconvenient. This was due a recent change in OMF startup process.

The new startup process isolate the scope of packages and custom init files. Therefore, you need to make this variable global by using `-g` in addition of `-x`. In your case you would have the following:

```
set -g -x MAPI_KEY "uEAGXx7TqdgbolM4"
```

**Comment by specter119** [comment]
@coderstephen @derekstavis Thank you.
