### ISSUE TITLE
Should there be a place to host all of the plugins/themes?

### ISSUE THREAD

**Issue by KhaledMohamedP** [oh-my-fish/oh-my-fish#358]
I am not sure if it exist, but was wondering if there is a site that hosts all plugins/themes?

It should include top features, downloads, stars  etc...

**Comment by oranja** [comment]
Hi,

A good-looking website is one of our future goals.
In the meantime:

You can see a preview of the themes here:
https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md
(might be a little out of date)

Both plugins and themes can be searched here on [github.com/oh-my-fish](https://www.github.com/oh-my-fish) or with simple `omf` commands:
`omf search ([-t | --theme]) ([-pkg | --package]) item`
`omf list` [--available | --installed | --database]
'omf describe [name]'

Does this answer your question?

**Comment by KhaledMohamedP** [comment]
@oranja thanks for the great reply. I am familiar with those places to get going for the moment, but will love a great looking website.

**Comment by sagebind** [comment]
As part of #427, plugins will be distributed and not necessarily in a central location, though there will be an official repository just for descriptions, etc. of all the plugins. Not quite a website, but probably satisfactory.

Closing since the question has been answered.
