### ISSUE TITLE
Oh-my-fish bobthefish theme at 'user' and 'root' mode after 'su'

### ISSUE THREAD

**Issue by ghost** [oh-my-fish/oh-my-fish#362]
I install fish shell and install OMF with bobthefish theme at 'user' mode, change shell for 'user' and 'root' to fish by means of **chsh -s /bin/fish user** and **chsh -s /bin/fish root**. So, that is all right at user-mode, i see bobthefish theme, but when i change my privilege to 'root' by means of 'su' i have fish shell without bobthefish theme. Furthermore when i try install oh-my-fish at root mode (after 'su'), installer try put OMF to 'user' folders and tell me 'Aborting: Existing installation detected.' 
How can i have bobthefish theme in 'user' and 'root' mode?

**Comment by derekstavis** [comment]
Hi @relden, thanks for your report.

I had the same issue in the past. I solved it using

```
$ sudo -s
# chsh -s /bin/fish
# reboot
```

The `reboot` is needed on some systems for the shell change have effect.

**Comment by relden** [comment]
These commands did not give the desired results. After execute sudo -s i have 'root' privilege with fish shell (as 'user' shell) without oh-my-fish bobthefish theme (theme is default).

**Comment by oranja** [comment]
I'm coping here my comments from the gitter chat, for the record and for others:

> First, when you Substitute User (su) without any command, it opens an interactive shell. The shell in this case is the default shell for the 'root' user. If it's not fish (it's probably bash and I would keep it that way), you can't expect the theme to still work. It's a fish theme after all.
> Second, even if the shell for 'root' was fish, root has a different `$HOME` folder and therefore all fish configurations will be loaded from his `/root` folder instead of `/home/relden` (or whatever you have in your system). Among these configurations there are omf, your chosen theme and a few lines that tell fish to load omf.

> Now that we understand what's stopping us, we can easily find a way to get your theme to show for 'root'.
> Method 1: Instead of running `su`, run `su -c fish` to switch to root user with fish as your shell. Then install omf for the root user! You can install omf for 'root' just like for any other user. Then you can install and set a theme for it. (It might be a good practice to keep the theme for root different so that you'll remember that you have privileges and be careful). You'll always have to type `su -c fish` instead of just `su`, so you might want to set up an alias for that. Otherwise, you can change the default shell for root from bash to fish, but I believe it's safer to have the default shell for root a POSIX compatible shell, so again, I'd keep bash as the default.
> Method 2: Something tells me it's not recommended, but there's a very simple workaround and it goes like this:
> `sudo HOME=$HOME fish` (to start fish in a subshell, as root, with your $HOME folder instead of `/root`) or `su -c "export HOME=$HOME fish"` (to replace the process with a fish shell, running as root , with your `$HOME` folder instead of `/root`)
> Again, you can set up an alias to make this quicker.
> To be clear: something tells me that it's not recommended, so be careful and use at your own risk.

Regarding the installer problem, it seems like I missed a crucial detail. When you enter `su` mode, you still have two OMF variables set: `OMF_PATH` and `OMF_CONFIG`. They point to your user's `$HOME`, and you *do* actually have OMF installed there. I believe you can simply `set -e OMF_PATH` and `set -e OMF_CONFIG` to make the installer run.
I'm still not sure though what are the implications for future `su` sessions. You will carry your user's variables every time...
I need to give it more thought to come up with a proper solution.

**Comment by coderstephen** [comment]
@oranja The new installer isn't merged quite yet, but it will hopefully soon. Once it is merged, you can specify both those paths with command flags:

    install --path=/root/.local/share/omf --config=/root/.config/omf

**Comment by oranja** [comment]
@coderstephen yes, I think that this will be the best solution.
The new installer will allow more explicit control for cases like this.

One caveat, though: Whenever a user will use `su` to switch to _root_ (or any other user), `OMF_CONFIG` will still be set to the that user's directory, unless manually overriden in 'config.fish'.
This is not necesserily undesirable, but it seems unpredictable and unintuitive to me, so I'd consider sticking a warning.. somewhere...

**Comment by derekstavis** [comment]
A quick check could be done: If `OMF_PATH` and `OMF_CONFIG` is prefixed with a home directory which isn't the current `$HOME`, a warning could be emitted.

Anyway, `su -` is the right way of changing to superuser, as it cleans the previous environment variables.

**Comment by oranja** [comment]
Aha! I should have known that about `su -`... :disappointed: 

So one approach would be to get the privileges but keep everything else intact:
`su -c "HOME=$HOME /usr/bin/fish"`

And a second, maybe better approach, would be to turn to root completely:
`su -` or `su - -c "/usr/bin/fish"`
Then do whatever necessary to set up the environment similar to the user's.

**Comment by sagebind** [comment]
New installer is now available, and supports installing to specific directories. Closing.
