### ISSUE TITLE
Error during installation in cygwin

### ISSUE THREAD

**Issue by cumanzor** [oh-my-fish/oh-my-fish#376]
Wonder if I can get some help with this error message. I was able to install fish and omf on a previous Windows install using babun instead of plain Cygwin, but this time around, using the Cygwin installer and installing fish, the omf installation fails with this message:

`Installing Oh My Fish to /cygdrive/c/Users/cuman/.local/share/omf...
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Existent config.fish found at /cygdrive/c/Users/cuman/.config/fish
↳ Moving to /cygdrive/c/Users/cuman/.config/fish/config.1470181919.copy
Adding startup code to fish config file...
Building Oh My Fish configuration...
Illegal command name “{$OMF_CONFIG,$OMF_PATH}/pkg/*/key_bindings.fish”
~/.local/share/omf/init.fish (line 33):                       {$OMF_CONFIG,$OMF_PATH}/pkg/*/key_bindings.fish \
                                                              ^
from sourcing file ~/.local/share/omf/init.fish
        called on line 10 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup

source: Error while reading file “/cygdrive/c/Users/cuman/.local/share/omf/init.fish”
fish: Unknown command 'omf install'
楦桳›浯⁦湩瑳污੬†††ਫ਼Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues`

Any recommendations? 

Thanks.

**Comment by coderstephen** [comment]
@cumanzor Hmm, I know we occasionally had some trouble with Windows setups in the past.

Please paste in the output of the following commands so I can help you troubleshoot:

```fish
fish --version
git --version
echo "OMF_PATH: $OMF_PATH"
```

**Comment by cumanzor** [comment]
@coderstephen: I found out what was causing the issue. I had attempted to set my Cygwin home folder to my windows home folder by adding the "HOME" user env variable. Apparently this can break several things in Cygwin. I removed the variable and reinstalled Cygwin, fish and omf. Everything is working properly now.

Thanks!

**Comment by masaeedu** [comment]
@sagebind Is OMF trying to install something to a hardcoded /home/<user> path instead of `$HOME` by any chance? I need to continue using my Windows home folder, and most other cygwin packages (including fish itself) work correctly with the setup I have.

**Comment by sagebind** [comment]
@masaeedu  No, it uses `$HOME` during install. Try checking `~/.config/fish/config.fish` and `~/.config/fish/conf.d/omf.fish` to see what paths it is using.
