### ISSUE TITLE
Do you have any idea what what green [I] is before my shell on certain themes?

### ISSUE THREAD

**Issue by JewsOfHazard** [oh-my-fish/oh-my-fish#389]
![This One](http://i.imgur.com/W4HdBkK.png)

**Comment by JewsOfHazard** [comment]
Nevermind it's fish saying I have vi keybindings on but I don't know how to disable the notification

**Comment by derekstavis** [comment]
Hi @JewsOfHazard!

Since Fish 2.3 we got this indicator "by default". Since then, themes must be updated to properly handle it. While themes doesn't update, you can create an empty function to override fish's default behavior:

```fish
function fish_mode_prompt; end
funcsave fish_mode_prompt
```

**Comment by JewsOfHazard** [comment]
Worked like a charm @derekstavis. Thanks a bunch.
