### ISSUE TITLE
Receiving email on staring this project

### ISSUE THREAD

**Issue by mjunaidsalaat** [oh-my-fish/oh-my-fish#393]
I started using the `fish` shell and `oh-my-fish` recently and am also a new `linux` user.

I just wanted to confirm that on staring this project I got an email from `hi@ohmy.fish` claiming that they don't actively maintain this project and advised to move to fisherman as a member of this `omf` project.

I started looking through the issues and found out that both projects aren't related. So I thought I might confirm or acknowledge you guys

Below is the picture of the mail I received on staring the project.

![capture](https://cloud.githubusercontent.com/assets/9829936/17978470/b2c3a400-6b0f-11e6-966e-ee9240cf7915.PNG)

Thanks.

**Comment by sagebind** [comment]
@mjunaidsalaat Thanks for bringing this disturbing email to our attention! You're right, this email was not sanctioned by us. The team is investigating now on how to deal with this.

---

By the way, thanks for starring us! 😃  🌟

**Comment by mjunaidsalaat** [comment]
My Pleasure. Glad it helped. ;)

Closing this now.

**Comment by mjunaidsalaat** [comment]
My Pleasure. Glad it helped. ;)

Closing it now.
