### ISSUE TITLE
Archlinux plugin is not in registry

### ISSUE THREAD

**Issue by manu09** [oh-my-fish/oh-my-fish#395]
I tried to install [the archlinux plugins](https://github.com/oh-my-fish/plugin-archlinux) with `omf install archlinux` but it seems not to be in the plugin registry. Any reason not to include it?

```
⋊> ~/Downloads on master ⨯ omf install archlinux                        14:00:05
Installing package archlinux
fatal: repository 'archlinux' does not exist
Could not install package archlinux.
```

I had to use the absolute url to the repository:

```
⋊> ~/Downloads on master ⨯ omf install https://github.com/oh-my-fish/plugin-archlinux
Installing package archlinux
✔ package archlinux successfully installed.
```

**Comment by derekstavis** [comment]
Hey, sorry for this issue!

We have left out of registry some packages because they wasn't migrated to new Oh My Fish plugin structure, but looks like Arch Linux plugin was recently migrated.

Thanks for pointing. I will soon raise a PR to fix this issue :+1:

**Comment by manu09** [comment]
Thanks for all the plugins! The same happens with tmux plugin. I thought all plugins listed on the oh-my-fish organization account would be in the registry by default.
