### ISSUE TITLE
How to uninstall omf

### ISSUE THREAD

**Issue by lollipoppp** [oh-my-fish/oh-my-fish#397]
__How to uninstall omf__

**Comment by bobthecow** [comment]
The same way you install it, but with an `--uninstall` flag.

```
curl -L http://get.oh-my.fish > install
fish install --uninstall
```

… should do it?

**Comment by derekstavis** [comment]
Also if you do a quick search in main README for "uninstall" you can have the answer:

![screenshot from 2016-09-04 19-30-26](https://cloud.githubusercontent.com/assets/1611639/18234300/279c58a8-72d6-11e6-9b25-c7aeea1061b7.png)

**Comment by ffmpegboi** [comment]
Oh, is this how to uninstall `omf`!

**Comment by luxlogica** [comment]
Please note that due to issue #736, uninstalling OMF is no longer straight-forward - none of the methods described here work.

**Comment by dinotheextinct** [comment]
So why cant you deinstall it? Could it possibly be fixed?
![image](https://user-images.githubusercontent.com/32158581/163790025-0ce33932-c688-4288-83a3-3cc06db97cf6.png)

**Comment by logc** [comment]
Actually, writing `yes` at that prompt seemed to uninstall `omf` for me ...
