### ISSUE TITLE
Document custom configuration file

### ISSUE THREAD

**Issue by jney** [oh-my-fish/oh-my-fish#40]
maybe i missed that in the doc, how do i load my own config ?
i'm not sure it is a good way to go to edit `~/.config/fish/config.fish` file

**Comment by derekstavis** [comment]
Hi @jney. Good observation. You can put your custom config in `$OMF_CONFIG/init.fish`.

**Comment by derekstavis** [comment]
If things start to grow you can `omf new` and create a plugin for you. We highly encourage people to split `$OMF_CONFIG/init.fish` into its own plugins, as it provides better separation of concerns and allows you to add them to your dotfiles, which [are meant to be forked](http://zachholman.com/2010/08/dotfiles-are-meant-to-be-forked).

**Comment by jney** [comment]
thank you derek

**Comment by derekstavis** [comment]
Let's keep this issue open with a slight different title as this is missing in documentation.

**Comment by bpinto** [comment]
Ping @derekstavis

**Comment by derekstavis** [comment]
Merged!
