### ISSUE TITLE
oh-my-fish and spacemacs don't play nicely together

### ISSUE THREAD

**Issue by everson** [oh-my-fish/oh-my-fish#409]
I am having issues where Spacemacs and Fish does not play well together. In my case, as I type, sometimes the commands are overlapped with previous output and some numbers are displayed in the next lines as shown on http://take.ms/1Qud8

after removing oh-my-fish the problem went away. It would still be nice to be able to keep oh-my-fish, though. I am leaving this in hopes that someone knows how to fix it and also to those having the same issue to know that disabling oh-my-fish solves the issue.

I have also posted this comment on https://github.com/syl20bnr/spacemacs/issues/5593

**Comment by sagebind** [comment]
@everson Oh My Fish itself does not print anything or do anything to the terminal screen, so the first thing I would look at is the theme you are using for compatibility issues. My gut reaction is that the right-hand prompt is causing issues with Spacemacs (though I've never used Spacemacs). I would try using a theme without a right-hand prompt and see if issues persist.

You can view a list with previews of most themes [here](../blob/master/docs/Themes.md).

**Comment by everson** [comment]
Thank you for replying @sagebind. I will try that.

**Comment by bobthecow** [comment]
I'd guess that @sagebind is right. If that's the case, and if you want to disable your theme's right prompt, you can override it by creating a file called `fish_right_prompt.fish` inside `~/.config/omf/functions/` (create that directory if it doesn't exist). Then add an empty function to that file: `function fish_right_prompt; end` should do :)
