### ISSUE TITLE
Weird `fish_prompt` when super user

### ISSUE THREAD

**Issue by aytekinar** [oh-my-fish/oh-my-fish#410]
Hey,

I think I have a problem, tho I am not sure if this is a general bug, when using fish in `root`.

### Observed Behaviour

I am using `agnoster` theme for both my user account and root.  For my normal user account, the prompt looks fine; however, when I `sudo su -`, the prompt has 2 question marks. Does this make sense? I doubt this is due to some font issue, as I can see the yellow thunder symbol when I am super user.

### Setup

-  [x] Operating System: Arch Linux
-  [x] Fish Version: 2.3.1
-  [x] Oh My Fish Version: 2
-  [x] Git version: 2.10.0

Thanks!

**Comment by sagebind** [comment]
@aytekinar Is it possible to provide a screenshot? It could still be a font issue, as the thunder symbol I believe is in a much smaller Unicode range than some other symbols it might be using.

**Comment by aytekinar** [comment]
![scr_1920x1080_20161003](https://cloud.githubusercontent.com/assets/8845951/19047956/6ef1fe08-89a4-11e6-8710-b16cb3d2607e.png)

and I have the following [powerline](https://github.com/powerline/fonts) patched adobe fonts.

```
fc-list | grep -i powerline | grep -i source

/home/aytekin/.local/share/fonts/Sauce Code Powerline Black.otf: Source Code Pro for Powerline,Source Code Pro Black:style=Black,Regular
/home/aytekin/.local/share/fonts/Sauce Code Powerline Light.otf: Source Code Pro for Powerline,Source Code Pro Light:style=Light,Regular
/home/aytekin/.local/share/fonts/Sauce Code Powerline ExtraLight.otf: Source Code Pro for Powerline,Source Code Pro ExtraLight:style=ExtraLight,Regular
/home/aytekin/.local/share/fonts/Sauce Code Powerline Semibold.otf: Source Code Pro for Powerline,Source Code Pro Semibold:style=Semibold,Regular
/home/aytekin/.local/share/fonts/Sauce Code Powerline Regular.otf: Source Code Pro for Powerline,Sauce Code Powerline:style=Regular
/home/aytekin/.local/share/fonts/Sauce Code Powerline Medium.otf: Source Code Pro for Powerline,Source Code Pro Medium:style=Medium,Regular
/home/aytekin/.local/share/fonts/Sauce Code Powerline Bold.otf: Source Code Pro for Powerline,Sauce Code Powerline:style=Bold
```

**Comment by sagebind** [comment]
Those question marks are definitely in place of the "" character being used as the powerline arrow. My first guess would be to check your locale:

```fish
~> locale
# what do you get?
~> sudo su -
~> locale
# now what do you get?
```

Powerline fonts are usually locale-aware and may not be displayed properly if root is using a different, non UTF-8 locale.

**Comment by aytekinar** [comment]
I think you have spotted the problem! Sorry for confusing you then --- the `locale` from `sudo su -` and from my `ssh aytekinkth` login gives `POSIX` while leaving `LANG=` section empty.

I know, from this point on, this problem is not related to `omf`, but could you just give me a fast hint on why it might have happened? Is this related in any way to `fish`'s not being a POSIX-compliant shell?

PS: I have switched from zsh to fish and I did not have such a weird behaviour, then.

**Comment by sagebind** [comment]
It can depend on the system. It is usually the responsibility of the login process to set the locale and not the shell, so it would be weird for it to work fine with zsh and not fish. It isn't part of a POSIX shell (iirc) to set the locale. It is possible that the environment has no locale and zsh attempted to "do the right thing" by choosing a UTF-8 override if necessary, while fish may just use an empty locale as asked.

**Comment by aytekinar** [comment]
do you have a suggestion for this apart from what I have provided in my edited message above? `omf search utf` or `omf search locale` did not give any results. do you think I should just write a small function myself, or is there a neater/cleaner way of fixing this?

thanks for your time, by the way!

**Comment by sagebind** [comment]
If you want to force the locale, try putting something like this in `/root/.config/fish/config.fish`:

```
set -x LC_ALL=en_US.UTF-8
set -x LANG=en_US.UTF-8
set -x LANGUAGE=en_US.UTF-8
```

or replace `en_US` with any language.

Another possibility is to try just `sudo su` without `-`, which prevents environment variables like `LC_ALL` from being inherited by the child shell.

**Comment by aytekinar** [comment]
I think I still need to put those definitions in the `~` folders of my remote machines, right? `sudo su` did the trick, but I still don't know how to carry with me the environment variables via ssh. For this purpose, shall I write a `conf.fish` in `~/.config/fish/conf.d/` in the machines? May I assume any `.fish` file inside that folder fill be read/sourced by the shell?

**Comment by sagebind** [comment]
> I think I still need to put those definitions in the ~ folders of my remote machines, right?

Yep, unfortunately. Seems like bad practice, but I don't know what would be better. Depending on distribution you may be able to make a `~/.config/locale.conf` file instead.

> For this purpose, shall I write a conf.fish in ~/.config/fish/conf.d/ in the machines? May I assume any .fish file inside that folder fill be read/sourced by the shell?

Yep, anything in `~/.config/fish/conf.d` gets sourced before shell starts, assuming fish version <= 2.3.

**Comment by aytekinar** [comment]
> Yep, unfortunately. Seems like bad practice, but I don't know what would be better. Depending on distribution you may be able to make a ~/.config/locale.conf file instead.

I will try this, also, even though I doubt it will be any good --- I already have configured /etc/locale.conf properly and `localectl` seems to be giving me the correct results. It happens only when I login as a different user or ssh to a remote machine using my user account. A bit of a `man` reading.

That said, I thank you once more and close this comment not to abuse the issue anymore.
