### ISSUE TITLE
Where is function d and function c?

### ISSUE THREAD

**Issue by c02y** [oh-my-fish/oh-my-fish#413]
I really like the [function d](https://github.com/oh-my-fish/oh-my-fish/blob/00325f886f091768228c7f16ff6e1bd142b0368b/docs/Themes.md#quickly-navigate-in-history-of-working-directories) and [function c](https://github.com/oh-my-fish/oh-my-fish/blob/00325f886f091768228c7f16ff6e1bd142b0368b/docs/Themes.md#quickly-navigate-in-command-history), I tried to install oh-my-fish, but it says command not found, and I cannot find their definitions.

So how can I get **d** and **c** working and where is their definitions?

**Comment by c02y** [comment]
Why not simplify the functions and leave the theme doing its own business?

**Comment by lfiolhais** [comment]
That was the author's decision to implement both functions in the theme. If you just want the functions you can simply copy and paste them to your `init.fish`. If you feel that both functions should be separated into their own packages, I'm sure the OMF crew would be more than happy to take your PR and include them in the database (as long as the author is ok with it too).

> Functions like these should be working in the stock omf

That is not what OMF is for. OMF is first and foremost a framework that facilitates the customization of your shell. It very rarely assumes what you need and want, the only case where this rule is broken might be the [git functions](https://github.com/oh-my-fish/oh-my-fish/tree/master/lib/git). It is generally not a good a idea to add functions that most of the user base doesn't use. That is why packages exist.

**Comment by c02y** [comment]
This is the function `d` I'm using, not from the budspencer theme but it is useful and simple, I'll paste it here if any one needs it:

    function d --description "Choose one from the list of recently visited dirs"
        set -l letters - b c d e f h i j k l m n o p q r s t u v w x y z
        set -l all_dirs $dirprev $dirnext
        if not set -q all_dirs[1]
            echo 'No previous directories to select. You have to cd at least once.'
            return 0
        end
    
        # Reverse the directories so the most recently visited is first in the list.
        # Also, eliminate duplicates; i.e., we only want the most recent visit to a
        # given directory in the selection list.
        set -l uniq_dirs
        for dir in $all_dirs[-1..1]
            if not contains $dir $uniq_dirs
                set uniq_dirs $uniq_dirs $dir
            end
        end
    
        set -l dirc (count $uniq_dirs)
        if test $dirc -gt (count $letters)
            set -l msg 'This should not happen. Have you changed the cd function?'
            printf (_ "$msg\n")
            set -l msg 'There are %s unique dirs in your history' \
                'but I can only handle %s'
            printf (_ "$msg\n") $dirc (count $letters)
            return 1
        end
    
        set -l pwd_existed 0
        # already_pwd avoid always print the bottom line *pwd:...
        for i in (seq $dirc -1 1)
            set dir $uniq_dirs[$i]
    
    	if test $pwd_existed != 1
    		if test "$dir" = "$PWD"
    			set pwd_existed 1
    		end
    	end
    	
            set -l home_dir (string match -r "$HOME(/.*|\$)" "$dir")
            if set -q home_dir[2]
    		set dir "~$home_dir[2]"
    		# change dir from /home/user/path to ~/path
    		# dir is not PWD anymore
            end
    	
    	if test $pwd_existed = 1
    		printf '%s* %2d)  %s%s\n' (set_color red) $i $dir (set_color normal)
    		set pwd_existed 2 # to make the rest of current the dirprev not red
    	else if test $i = 1
    		printf '%s- %2d)  %s%s\n' (set_color cyan) $i $dir (set_color normal)
    	else if test $i != 1 -a $pwd_existed != 1
    		printf '%s %2d)  %s\n' $letters[$i] $i $dir
    		
    	end
        end
        if test $pwd_existed = 0 # means the current dir is not in the $uniq_dirs
    	    printf '%s* %2d) %s%s\n' (set_color red) "0" $PWD (set_color normal)
        end
    
        echo '---------------------------'
        read -l -p 'echo "Goto: "' choice
        if test "$choice" = ""
            return 0
        else if string match -q -r '^[\-|b-z]$' $choice
            set choice (contains -i $choice $letters)
        end
    
        if string match -q -r '^\d+$' $choice
            if test $choice -ge 1 -a $choice -le $dirc
                cd $uniq_dirs[$choice]
                return
            else
    	    echo Error: expected a number between 1 and $dirc, got \"$choice\"
                return 1
            end
        else
            echo Error: expected a number between 1 and $dirc or letter in that range, got \"$choice\"
            return 1
        end
    end

**Comment by sagebind** [comment]
Question seems to be answered. Closing. Feel free to open a new case for any other questions or issues.
