### ISSUE TITLE
Using omf install duplicates lines in bundle

### ISSUE THREAD

**Issue by dbanck** [oh-my-fish/oh-my-fish#42]
Starting with no plugins installed and two things defined in the bundle file.

```
> cat .config/omf/bundle
theme bobthefish
package z
```

Now I'm running `omf install` to install my theme/packages.
```
> omf install
Installing bobthefish theme...
✔ theme bobthefish successfully installed.
Installing z package...
✔ package z successfully installed.
```

After that both things are getting added to the bundle (again)
```
> cat .config/omf/bundle
theme bobthefish
package z
theme bobthefish
package z
```

I'm using fish 2.2.0 and oh-my-fish 4b0dbc2

**Comment by derekstavis** [comment]
Damn! `uniq` hasn't worked! Could you give a look at the source code and debug it?

**Comment by bobthecow** [comment]
`uniq` only works on consecutive lines, i.e.:

```
foo
bar
bar
foo
```

will return

```
foo
bar
foo
```

We need to use `sort -u` if we want to only have one line per thing.

**Comment by derekstavis** [comment]
PR'ing in 3... 2... 1...

**Comment by derekstavis** [comment]
@bobthecow @dbanck could you give a try at the PR branch?

**Comment by dbanck** [comment]
Looks good to me. No more duplicate entries so far :)
