### ISSUE TITLE
Cant install when using Fish version 2.3.1 on cygwin

### ISSUE THREAD

**Issue by CallumCarmicheal** [oh-my-fish/oh-my-fish#425]
Pretty much as it says, i cant install while using fish 2.3.1. 

Error: 

```
/j/D/t/omf> curl -L http://get.oh-my.fish > install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    466      0 --:--:-- --:--:-- --:--:--   470
100   140  100   140    0     0    180      0 --:--:-- --:--:-- --:--:--   180
100 16530  100 16530    0     0  18659      0 --:--:-- --:--:-- --:--:-- 18659
 /j/D/t/omf> fish install --path=~/.local/share/omf --config=~/.config/omf
Input file specified two times.

test: Missing argument at index 2
Install aborted: Fish version 2.2.0 or greater required; you have 2.3.1

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues
 /j/D/t/omf>
```

**Comment by sagebind** [comment]
@CallumCarmicheal You aren't using cygwin by chance, are you?

> Input file specified two times.

Looks like a Windows `sort` error. Please paste the output of `which sort` here.

**Comment by CallumCarmicheal** [comment]
```
/j/D/P/s/mupen> which sort
/c/Windows/system32/sort
```

That is the output of `which sort`

**Comment by sagebind** [comment]
@CallumCarmicheal That's what I suspected. The installer is expecting a POSIX `sort` command, but instead it is finding Windows' `sort` command instead. The key is to adjust your path to prioritize the POSIX commands over native Windows ones:

```fish
set PATH /usr/bin $PATH
fish install --path=~/.local/share/omf --config=~/.config/omf
```

**Comment by CallumCarmicheal** [comment]
It installs perfectly fine now. And for the record the installation worked flawlessly on Cygwin but right now im using MSYS2 to compile ps vita code. I only think it is a problem on MSYS2 but i could be wrong.

**Comment by sagebind** [comment]
This appears to be solved. Closing.
