### ISSUE TITLE
Add docs on how to add npm globals to path

### ISSUE THREAD

**Issue by corysimmons** [oh-my-fish/oh-my-fish#429]
Please

**Comment by sagebind** [comment]
This issue doesn't belong in Oh My Fish -- nothing is npm-specific in the framework. Try npm docs to see what paths you need to add to `$PATH`: https://docs.npmjs.com/files/folders

**Comment by oranja** [comment]
See this helpful plugin:
https://github.com/oh-my-fish/plugin-node

From its README:
## Install

```fish
$ omf install node
```


## Usage

This plugin makes `npm` and `./node_modules/.bin` available on `$PATH`. In some
situations it may be necessary to set `npm`'s directory path:

```fish
# ~/.config/fish/config.fish

# Set npm bin directory location
set NPM_DIR /path/to/npm/dir
```
