### ISSUE TITLE
Testing local themes

### ISSUE THREAD

**Issue by LukasMa** [oh-my-fish/oh-my-fish#432]
Environment:
- macOS
- fish, version 2.3.1 
- Oh My Fish version 3  
- git version 2.10.2

First time fish user here. I wanted to create a theme and test it before submitting it. I was under the assumption that after adding my theme to the local registry I could install it by `omf install`. But this doesn't work (`Repository not found`).

What is the prefered way of testing local themes?

**Comment by sagebind** [comment]
@LukasMa Sorry about the delay, missed this issue.

The typical way would be to put the theme directory in `$OMF_PATH/themes`, then enable it using `omf theme <theme-name>`. Installing is not necessary as it is already in the correct path.

**Comment by LukasMa** [comment]
Thanks for the reply! Will try that.

**Comment by LukasMa** [comment]
And it worked! Wow... So simple. Can't believe I did not try that...
