### ISSUE TITLE
How to disable fish_vi_key_bindings?

### ISSUE THREAD

**Issue by Ramblurr** [oh-my-fish/oh-my-fish#433]
I've played around with fish_vi_key_bindings, but would like to go back to normal.

How do i disable it? 

`set -U fish_key_bindings` --> breaks all input
`set -U fish_key_bindings fish_key_bindings` --> throws errors

Could we also get this added to the docs?

**Comment by sagebind** [comment]
`fish_vi_key_bindings` is a feature of Fish, not Oh My Fish.

To reset back to default key bindings:

```fish
set -U fish_key_bindings fish_default_key_bindings
```

**Comment by Ramblurr** [comment]
Ah, I didn't realize that it was a fish feature. Thanks!

**Comment by fyee** [comment]
Thank you very much @sagebind !

**Comment by fyee** [comment]
i use 
``[sh]
set -U fish_key_bindings fish_default_key_bindings
```
and it's back to normal.
