### ISSUE TITLE
Anyone knows why my theme is displayed in a reversed color?

### ISSUE THREAD

**Issue by HughGrant** [oh-my-fish/oh-my-fish#440]
I really liked the picture of the default theme which should be looked like this
![image](https://cloud.githubusercontent.com/assets/752577/20141919/949206f8-a6cd-11e6-968e-74b9e77faeae.png)

But this is what is looks like on my mac
![image](https://cloud.githubusercontent.com/assets/752577/20141753/bcf7fd10-a6cc-11e6-9719-152eecddf8e6.png)

See the first special character, I think it's a unicode character, its color is reversed.
I googled a lot, can't find any related topic or solution.

Both Terminal and iTerm2 on my mac are having the problem.

**Comment by oranja** [comment]
I'm on Fedora using Konsole, and here the themes can look dramatically different if I choose different color schemes.

In iTerm2 try to choose an alternative scheme from Preferences > Profiles > Colors.

**Comment by HughGrant** [comment]
@oranja no use at all, no matter what color preset I set, the first character always displayed in a reversed color state.

**Comment by derekstavis** [comment]
What's your fish version @HughGrant? This error happened to me after I've upgraded to fish 2.4.

**Comment by HughGrant** [comment]
hi @derekstavis , my fish version is exactly 2.4, installed via homebrew. I am wondering the problem is related to the theme used by iTerm2 or Terminal itself. 

You see the Terminal or iTerm2 has its own color scheme, then it is got blended together with the fish theme, resulting such weird problem.

**Comment by HughGrant** [comment]
@derekstavis what you mean is that you're not having this issue if you roll back the fish version?

**Comment by sagebind** [comment]
Looks like these changes in 2.4 could be the culprit: https://github.com/fish-shell/fish-shell/issues/3176 https://github.com/fish-shell/fish-shell/pull/3260

**Comment by sagebind** [comment]
Spinning up a fresh fish 2.4.0 container reveals a _number_ of colors that are inverted or messed up. Created an issue on fish for now: https://github.com/fish-shell/fish-shell/issues/3555

We might have to update our themes to be compatible with 2.4.0.

**Comment by oranja** [comment]
I don't know if the original plan was to bind the 'default' OMF theme with fish's pager colors, but there you have it. If it's suddenly not as pretty as expected, then a change is due in the theme's colors. It's possible to either globally unbind the theme from pager colors, or the user can locally change the pager colors until both the pager and the theme looks good to the user.
If the theme colors were not meant to be bound to fish's pager colors, then why are they? Obviously it's better to just write 'cyan' when you want cyan specifically, or if we want a kind of blue but want to let the user to decide which kind of blue, then we can use color number 4. Then the user might decide to make color number 4 very different from blue and it won't bother anyone (except for him in the case that the colors are now ugly).
