### ISSUE TITLE
Strange/bright character shows up on some clean fish installs

### ISSUE THREAD

**Issue by ztratar** [oh-my-fish/oh-my-fish#445]
I've been switching computers a couple times lately, and for some reason on about half the installs, fish decides that it should have this bright green [I] character at the beginning of every shell.

My last computer didn't have this issue but now I can't get rid of it.

Any help appreciated... anyone know why this Is happening?

- I've tried install fonts and power line fonts
- I've tried uninstalling and re-installing fish
- Have rebooted etc after installations
- Have tried multiple themes
- Can confirm other shells (bash, zsh) don't have this strange character
- As I said... it almost seems random when it shows up. Last base install didn't have this issue.

<img width="181" alt="screenshot 2016-11-22 12 07 17" src="https://cloud.githubusercontent.com/assets/955182/20540336/bf233a38-b0ad-11e6-9151-e43bf916af5f.png">

**Comment by sagebind** [comment]
This is a Fish feature. See #437 and #433.

**Comment by ztratar** [comment]
@sagebind oh, fascinating. Didn't even realize I had vi keybindings with this thing.

Thank you so much for the (very) fast help. Happy thanksgiving!
