### ISSUE TITLE
is there an oh-my-fish plugin that achieves "glob-expand-word" ?

### ISSUE THREAD

**Issue by introom** [oh-my-fish/oh-my-fish#447]
Basically, I'd like to have an equivalent of the Bash's "glob-expand-word (C-x *)".

Given a folder with files a{a,b,c} inside.
ls a*<C-x><*> will expand to ls aa ab ac.

Is there any equivalent plugin in omf that achieves the above functionality?

**Comment by sagebind** [comment]
Not that I can remember. You might be able to write a custom key binding. You can also do a lot with https://github.com/oh-my-fish/plugin-expand, you could write a function for that plugin to expand a glob word.
