### ISSUE TITLE
plugin-emacs doesn't work

### ISSUE THREAD

**Issue by seagle0128** [oh-my-fish/oh-my-fish#450]
I use this command to install emacs plugin, but it doesn't work.
```shell
omf install emacs
```
I checked the ~/.local/share/omf/pkg/emacs, the folder structure seems incorrect.
<img width="495" alt="image" src="https://cloud.githubusercontent.com/assets/140797/21072382/4f4dfb60-befb-11e6-8dbd-8f757665c429.png">

If I create functions folder, and move all fish files into it, it works.

**Comment by sagebind** [comment]
It looks like the name `emacs` is currently pointing to an old deprecated repository instead of https://github.com/oh-my-fish/plugin-emacs. I will update the database. After I have done so, you can fix the plugin by uninstalling it and then reinstalling.
