### ISSUE TITLE
Missing plugin-pj repository

### ISSUE THREAD

**Issue by esphen** [oh-my-fish/oh-my-fish#452]
Hi,

I have not heard anything on [the PR that was merged earlier this week](https://github.com/oh-my-fish/oh-my-fish/pull/449), so I'll open an issue here for increased visibility.

The aforementioned PR added a plugin with an `oh-my-fish` organization repository URL, which is what I interpreted from [the guide](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/en-US/Packages.md#make-it-public) as the way to make a plugin public. That URL still 404s, however, so I just wanted to check that everything is in order.

Apologies if I misunderstood something of the plugin approval process.

**Comment by derekstavis** [comment]
Oh! Soorry!! 🙀

I really overlooked the PR!! My fault!!

I've imported into `oh-my-fish/plugin-pj` and made you an admin! 

My apologies!!

**Comment by esphen** [comment]
No problem, @derekstavis! 

I see I'm invited to the new repository now, that's great. Thanks!
