### ISSUE TITLE
How to further debug an issue when doctor fails? 

### ISSUE THREAD

**Issue by TheServerAsterisk** [oh-my-fish/oh-my-fish#453]
I am unable to determine the cause of why the bobthefish theme is partially failing, that is, the right arrows aren't rendering correctly. Namely, I get a symbol like [I] but rotated 90 degrees. This suggests a font issue, but I can't seem to confirm this is the case. Thus I was wonder how to further debug this.

**Comment by sagebind** [comment]
@TheServerAsterisk Font errors are nasty. Great ways to get help are to open an issue here, which you have done!

If you're seeing something like `[i]`, I would make sure you're not running into #437.

**Comment by TheServerAsterisk** [comment]
I tried using the fix found in #433, but that didn't work :disappointed: , but it appears that github accepts the Unicode so the prompt looks like so: 
```
 me@WS-15  ~/.c/fish  
```

Where `` and `  ` I believe are suppose to be the right triangles

**Comment by TheServerAsterisk** [comment]
Also this is on Fedora 25 64 bit machine.

**Comment by bobthecow** [comment]
Have you installed a powerline patched font?

**Comment by TheServerAsterisk** [comment]
@bobthecow I thought I did, but then I read that single sentence in the powerline repo "This repository contains pre-patched and adjusted fonts for usage" *sigh*. However, I discovered that there is a repo already set up for fedora. Once I installed that everything works.

**Comment by bobthecow** [comment]
Glad you got it sorted out!
