### ISSUE TITLE
Incompatibility with Terminix?

### ISSUE THREAD

**Issue by otahirs** [oh-my-fish/oh-my-fish#462]
![screenshot from 2016-12-22 22-16-01](https://cloud.githubusercontent.com/assets/24588500/21438998/f4bcb138-c88b-11e6-914e-ee4ebf9a9f48.png)

Hi.
I run into problem when using omf with Terminix. Normal bash terminal works completely fine, but when using terminix the UI is bugged. As you can se from the screenshot, the cursor is not on the line with the location (~), but on the next line.

**Comment by derekstavis** [comment]
Hi @otahirs, thanks for your report!

Could you please try with another prompt theme? It looks to me that this is something related with the theme, given that the right prompt is reflowing to the next line.

**Comment by bobthecow** [comment]
It looks like it's incorrectly treating non-ascii glyphs (like the prompt segment separators) as double-width. I dunno about your terminal, but iTerm has a checkbox for disabling that.

**Comment by Despin** [comment]
@otahirs Hi, I wanted to know, what environment are you using?

**Comment by otahirs** [comment]
Theme doesnt matter.
In fact the problem persist even with powerline package and ocurs ofter incorrectly written comand.
![screenshot from 2016-12-24 13-21-28](https://cloud.githubusercontent.com/assets/24588500/21466971/2741412c-c9dc-11e6-9389-2cc0328e6666.png)

I am running Arch with gnome 3.22 enviroment.

**Comment by otahirs** [comment]
only working powerline shell for me is https://github.com/banga/powerline-shell

**Comment by derekstavis** [comment]
Closing this as I have been using fish in Terminix for a long time (since first Terminix release) and never experienced the issue described.
