### ISSUE TITLE
Vundle gives me errors

### ISSUE THREAD

**Issue by th3m4ri0** [oh-my-fish/oh-my-fish#463]
Using the vundle plugin, but typing the ```vundle``` command gives me the same errors as not using the plugin (partial screenshot because error shows for half a sec) : 
![capture d ecran 2015-05-27 a 16 48 16](https://cloud.githubusercontent.com/assets/2685884/7847222/3d0d135e-0490-11e5-91a2-4783196fd650.png)

**Comment by bpinto** [comment]
Seems to be an error on vundle itself?

**Comment by th3m4ri0** [comment]
Isn't the vundle plugin supposed to do this workaround ?
https://github.com/gmarik/Vundle.vim/wiki#faq4

**Comment by bpinto** [comment]
Is this error related to this? Have you tried removing all your `.vimrc` configurations and running it?

**Comment by bpinto** [comment]
ping @th3m4ri0

**Comment by th3m4ri0** [comment]
Yes this error is happening because of fish being a non-POSIX shell 

Here's my .vimrc :
```
set nocompatible              " be iMproved, required
" set shell=bash
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'


" Tree explorer
Plugin 'scrooloose/nerdtree' 
```
Uncommenting the second line (```set shell=bash```) make it all work.  

After looking at the [plugin file](https://github.com/oh-my-fish/plugin-vundle/blob/master/vundle.load), I understand that its purpose isn't to provide a solution to this issue, but only to give a shorthand to Vundle related commands. My bad ! ;)

**Comment by bpinto** [comment]
If you could work on a plugin for supporting fish or to improve the read
me, that would be great!
