### ISSUE TITLE
__original_fish_user_key_bindings function is broken, creates recursive loop

### ISSUE THREAD

**Issue by zhiayang** [oh-my-fish/oh-my-fish#465]
Environment:
Linux Mint, Fish 2.4.0, omf version 3.

Immediately upon logging in, I get swarmed by a stack trace, caused by the infinite recursion of `__original_fish_user_key_bindings` calling itself. Looking at the output, it appears to be caused by this section of `omf/init.fish`:

```
# Backup key bindings
functions -q fish_user_key_bindings
  and not functions -q __original_fish_user_key_bindings
  and functions -c fish_user_key_bindings __original_fish_user_key_bindings
# Override key bindings, calling original if existent
function fish_user_key_bindings
  read -l theme < $OMF_CONFIG/theme
  # Prepare packages key bindings paths
  set -l key_bindings $OMF_CONFIG/key_binding?.fish \
                      {$OMF_CONFIG,$OMF_PATH}/pkg/*/key_bindings.fish \
                      {$OMF_CONFIG,$OMF_PATH}/themes/$theme/key_binding?.fish
  # Source all keybindings collected
  for file in $key_bindings
    source $file
  end
  # Call original key bindings if existent
  functions -q __original_fish_user_key_bindings
    and __original_fish_user_key_bindings
end
```

What appears to happen is that the function `fish_user_key_bindings` becomes `__original_fish_user_key_bindings`. After the swarm of errors, I'm presented with a working shell, and the output of `functions __original_fish_user_key_bindings` is this:

```
function __original_fish_user_key_bindings
  read -l theme < $OMF_CONFIG/theme
  # Prepare packages key bindings paths
  set -l key_bindings $OMF_CONFIG/key_binding?.fish \
                      {$OMF_CONFIG,$OMF_PATH}/pkg/*/key_bindings.fish \
                      {$OMF_CONFIG,$OMF_PATH}/themes/$theme/key_binding?.fish
  # Source all keybindings collected
  for file in $key_bindings
    source $file
  end
  # Call original key bindings if existent
  functions -q __original_fish_user_key_bindings
    and __original_fish_user_key_bindings
end
```

Clearly, the function becomes defined (`functions -q __blabla` returns `true`), and it calls itself infinitely (or until stopped).

Strangely I'm not having this issue on my OS X install of fish/omf, running the same versions.

For now, since i'm not using any custom keybindings, I've just removed the final call to `__original_fish_user_key_bindings`.

**Comment by sagebind** [comment]
@zhiayang I recall seeing this before on Windows... I believe it is caused by accidental double-sourcing of `init.fish`. What does your `config.fish` look like?

**Comment by derekstavis** [comment]
Hi @zhiayang, thanks for your report.

The only scenario I can see this problem happening is when you have a double source of OMF initialization file. Could you check if you don't have duplicated content on `~/.config/fish/config.fish` and `~/.config/fish/conf.d` files?

**Comment by zhiayang** [comment]
`.config/fish/conf.d/omf.fish`:
```
set -q XDG_DATA_HOME and set -gx OMF_PATH "$XDG_DATA_HOME/omf" or set -gx OMF_PATH "$HOME/.local/share/omf"
source $OMF_PATH/init.fish
```

`.config/fish/config.fish`:
```
set -gx OMF_PATH "/home/zhiayang/.local/share/omf"
# set -gx OMF_CONFIG "/home/zhiayang/.config/omf"

source $OMF_PATH/init.fish
```

I think i can see where the problem lies, and what you're talking about. So,

1. how did this come about?
2. which one do i delete?

**Comment by sagebind** [comment]
@zhiayang `.config/fish/conf.d/omf.fish` is created by the installer and is the recommended way for Fish 2.3+, but `conf.d` was not supported for Fish 2.2.

`.config/fish/config.fish` used to be generated by the installer to set up `OMF_PATH` and to source `$OMF_PATH/init.fish` but is no longer necessary. My guess is that you copied that config file from somewhere else when it was generated by an old installer.

**Comment by zhiayang** [comment]
Alright, I'll delete the `config.fish` file then, thanks.

**Comment by bentolor** [comment]
Stumbled here over the same issue.

**Comment by oranja** [comment]
But did you manage to solve it?
And if so, did you find all the information you needed in this thread?

**Comment by bentolor** [comment]
Obviously update OMF breaks the installation into this error as it does not remove nor guard the infinitive loop it causes by adding a second call to `init.sh`. Lost ~30mins until I actively searched for closed issues in this project here.

My feedback should just encourage to keep in mind that _breaking user space_ with backward-incompatible changes causes much pain in the userbase.

**Comment by fbcotter** [comment]
> Alright, I'll delete the `config.fish` file then, thanks.

For others wondering, you don't need to delete the entire config.fish file, just the lines that source omf. I.e., your config.fish should NOT have:

    # Path to Oh My Fish install.
    set -q XDG_DATA_HOME
      and set -gx OMF_PATH "$XDG_DATA_HOME/omf"
      or set -gx OMF_PATH "$HOME/.local/share/omf"
    
    # Load Oh My Fish configuration.
    source $OMF_PATH/init.fish

**Comment by dsousa12** [comment]
I'm only having this issue on Intellij integrated terminal.
