### ISSUE TITLE
Idea conserve some fish variable accross omf reloading.

### ISSUE THREAD

**Issue by jeremiejig** [oh-my-fish/oh-my-fish#47]
Hi,

It might be a good idea to keep some more variable accross the reload of fish like `$dirprev $dirnext and $dirstack`

For example:
* I'm doing some work and constantly doing some `cd` and using alt + :arrow_left: or :arrow_right: 
* Suddenly I'm missing an awesome pkg
* So I just need to install it doing a `omf install awesome_pkg`
* ***omf reload fish***, I can now use thefreshly installed awesome pkg.
* But I want to go back to some previous directory using alt + :arrow_left: 
* **Damn** I can't, have to use `cd ../some/stupid/directory`

There might be some other variable needed to be kept accross omf reloading.

**Comment by bpinto** [comment]
True. I wonder if we can't just init the plugin instead of opening another shell. It might be a cleaner solution.

**Comment by jeremiejig** [comment]
What about `omf update` ? We do need to reload fish, do we ?
or do we trust fish to detect the change ?

Might also have the problem of some change in the init of the plugin.

**Comment by derekstavis** [comment]
The ideal solution would to include another event to "deinit" the plugin. This way the hard work is left to developers: Writing code to cleanup variables, functions, etc.

**Comment by bpinto** [comment]
Do we have any plugins that are this complicated? I wonder if we can't revert PATH changes and call init on every plugin again.

**Comment by coderstephen** [comment]
Preserving the directory stack has now been fixed by #266.
