### ISSUE TITLE
Themes folder empty

### ISSUE THREAD

**Issue by ismay** [oh-my-fish/oh-my-fish#470]
It looks like you're in the middle of moving all themes to their own repos. Am I right in assuming that you're now supposed to manually clone each theme in your `.oh-my-fish/themes` folder? Or is there an easier way?

**Comment by scorphus** [comment]
Fortunately there is!

Turn:
```fish
set fish_theme my_favorite_theme

set fish_plugins foo bar baz

. $fish_path/oh-my-fish.fish
```
Into:
```fish
. $fish_path/oh-my-fish.fish

Theme "my_favorite_theme"

Plugin "foo"
Plugin "bar"
Plugin "baz"
```

**Comment by ismay** [comment]
Cool, thanks!
