### ISSUE TITLE
Theme right prompt overflows

### ISSUE THREAD

**Issue by Altynai** [oh-my-fish/oh-my-fish#471]
I updated `oh-my-fish` today, something weird happened,
When I'm using the theme `thebobfish`, the right promopt in iTerm2 overflows like the image follows:
![image](https://cloud.githubusercontent.com/assets/1445958/7938390/d842b84c-0977-11e5-9613-fd10e0acab64.png)

I tried to change the format of the date, but it didn't work :(
my environment:
OSX, 10.10.3
iTerm2, Build 2.1.1
fish, version 2.1.0

**Comment by bobthecow** [comment]
Weird. It looks like you have two right prompts, somehow.

I'm assuming you ran `omf install` and/or `omf update` after updating?

Try opening `themes/bobthefish/fish_right_prompt.fish` and renaming the function to something else, then reloading fish. Do you still see a right prompt?

**Comment by riverssteve** [comment]
I had the same problem with iTerm2. Turns out I had "treat ambiguous width characters as double width" set under Preferences -> Profile -> Text.

**Comment by Altynai** [comment]
I did `omf update` after updating, it shows:
![image](https://cloud.githubusercontent.com/assets/1445958/7960548/ff6001f2-0a33-11e5-9b56-6d94925e5d1f.png)

then I renamed `themes/bobthefish/fish_right_prompt.fish` to `some_temp_file` and reloaded the fish,
the right prompt was gone, as expected:
![image](https://cloud.githubusercontent.com/assets/1445958/7960614/86ef8412-0a34-11e5-813f-ad5310d46ae4.png)

so it seems only one right prompt exists.

**Comment by Altynai** [comment]
@riverssteve 
Thanks bro :+1:
It works for me!

**Comment by bobthecow** [comment]
Good to know! :+1:

**Comment by bpinto** [comment]
Do you know why this would cause this problem @bobthecow

**Comment by bobthecow** [comment]
@bpinto because the powerline glyphs are an unknown width — they put them at an undefined codepoint, so iTerm has no idea whether they're single or double wide glyphs. So if you have that setting enabled, iTerm just makes everything it doesn't understand act like it's double wide, which means fish's native right prompt spacing is off.
