### ISSUE TITLE
Offline installation does not appear to be working: requires newer version of Git

### ISSUE THREAD

**Issue by SurfaceThought** [oh-my-fish/oh-my-fish#477]
Hello there,

Trying to install omf (which I dearly love) on an offline server.

I downloaded the latest version at this link: 

https://github.com/oh-my-fish/oh-my-fish/archive/v4.tar.gz

and unpacked it into my home on the server.

From there, I 

`cd oh-my-fish-4`
`bin/install --offline`

And I get the message: 

Install aborted: Git version 1.9.5 or greater required; you have 1.7.1

Needless to say, I do not have the ability to upgrade git on the system, although I believe that the offline installation should not have to use git?

Please let me know any other information you may need from me.

**Comment by sagebind** [comment]
That is working as intended. More than just installation requires Git. Installing plugins and themes also require Git, where the minimum supported version is 1.9.5.

It might be possible to install a newer version of Git in your home directory with something like [Linuxbrew](http://linuxbrew.sh).

**Comment by SurfaceThought** [comment]
Ah shucks alright well thank you anyway. I guess I'll probably just manually install my themes like a sucker XD
