### ISSUE TITLE
Command omf not found

### ISSUE THREAD

**Issue by lthibault** [oh-my-fish/oh-my-fish#478]
Hello,

I've just installed oh-my-fish via `curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | fish` on OSX Yosemite.  After running this command, the `omf` command cannot be found by the shell.  What gives?

**Comment by lthibault** [comment]
Calling `source` seems to have done the trick.

Closing.

**Comment by bpinto** [comment]
References: https://github.com/oh-my-fish/oh-my-fish/issues/473
