### ISSUE TITLE
why my mac installed fish and oh_my_fish can't use try

### ISSUE THREAD

**Issue by RIcky-Gerry** [oh-my-fish/oh-my-fish#482]
I read https://github.com/oh-my-fish/plugin-theme, and I konw how to switch theme ,but 'try' don't work for me , so how can I  solve the problem?
tip： if i want to look all themes , is a theme list present?

**Comment by bucaran** [comment]
Sorry, `try` was the original name of the command. It should be `theme` now.

**Comment by RIcky-Gerry** [comment]
@bucaran thanks!  I will try it now.:smile:
