### ISSUE TITLE
http://get.oh-my.fish/ is blank

### ISSUE THREAD

**Issue by NinoFloris** [oh-my-fish/oh-my-fish#489]
Might want to take a look as the installation does not work

**Comment by sagebind** [comment]
@NinoFloris Tried it just now and it works. If you're using cURL, be sure to enable following redirects with `-L`:

```
curl -L http://get.oh-my.fish
```

**Comment by NinoFloris** [comment]
Nope was also blank in browser, works here now again as well. Thanks for your quick response, must have been a fluke.
