### ISSUE TITLE
Tweaks to the logo

### ISSUE THREAD

**Issue by bucaran** [oh-my-fish/oh-my-fish#490]
I think a simpler logo results is a more austerely elegant image.

What do you think? It looks stylish in small size.

![2](https://cloud.githubusercontent.com/assets/8317250/8510172/f006f0a4-230f-11e5-98b6-5c2e3c87088f.png)
<hr>

![1](https://cloud.githubusercontent.com/assets/8317250/8510171/ecfcfc5a-230f-11e5-983f-f17635a6bf7f.png)

@bpinto @bobthecow @marcker

**Comment by marcker** [comment]
I agree with your suggestion. I even think that to reproduce this in many
ways the logo should be so simple.

Em dom, 5 de jul de 2015 00:20, Jorge Bucaran <notifications@github.com>
escreveu:

**Comment by bobthecow** [comment]
I like the current logo :)

There's nothing that says we can't use a variant like this for smaller logos, like the favicon. In fact, that's really common. Almost nobody uses the same full-size and small sized icons.

**Comment by marcker** [comment]
:+1

**Comment by bucaran** [comment]
> There's nothing that says we can't use a variant like this for smaller logos, like the favicon. In fact, that's really common. Almost nobody uses the same full-size and small sized icons.

Of course, why didn't I think of that :smile: 

The current logo looks great in the repo, but I prefer either of the suggested ones for the small version.

Let's try them on, and if you folks don't like them, we can go back to the current one again.

**Comment by bpinto** [comment]
:+1:

**Comment by bucaran** [comment]
Awesome.
