### ISSUE TITLE
How can I change Welcome Fish Shell Message

### ISSUE THREAD

**Issue by Zx-EvM** [oh-my-fish/oh-my-fish#491]
OS:

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

Today I install fish shell, version `2.5.0` using command:

```
sudo apt-add-repository ppa:fish-shell/release-2
sudo apt-get update
sudo apt-get install fish
```

and at once install `oh-my-zsh` using:

```
curl -L http://get.oh-my.fish | fish
```

And on each start of  terminal I have message:

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

How can I change this message if it's possible?

**Comment by sagebind** [comment]
This is a Fish shell feature. See https://fishshell.com/docs/current/faq.html.
