### ISSUE TITLE
Can't install in fish/cygwin

### ISSUE THREAD

**Issue by afboteroz** [oh-my-fish/oh-my-fish#492]
I'm trying to install it on fish (cygwin 64bits) and get the following error:

user@PC ~> curl -L http://get.oh-my.fish | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0    652      0 --:--:-- --:--:-- --:--:--   657
100 16533  100 16533    0     0  25221      0 --:--:-- --:--:-- --:--:-- 25221
Existing installation detected at /cygdrive/c/Users/user/.local/share/omf
Would you like to remove the existing installation? (y/N): y
This will uninstall Oh My Fish and all plugins and themes from
/cygdrive/c/Users/user/.local/share/omf.
Are you sure you want to continue? (y/N): y
Uninstalling from /cygdrive/c/Users/user/.local/share/omf...
Restoring backup file to
/cygdrive/c/Users/user/.config/fish/functions/fish_prompt.fish
Uninstall complete
Installing Oh My Fish to /cygdrive/c/Users/user/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Writing bootstrap to /cygdrive/c/Users/user/.config/fish/conf.d/omf.fish...
Existent fish_prompt.fish found at
/cygdrive/c/Users/user/.config/fish/functions
↳ Moving to
/cygdrive/c/Users/user/.config/fish/functions/fish_prompt.1488211451.copy
Setting up Oh My Fish configuration...
 to clone.g: Could not find remote branch mastermain master
 not found in upstream origin
Error
Install aborted: Error installing plugins

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues

**Comment by sagebind** [comment]
@afboteroz These lines looks very suspicious:

```
to clone.g: Could not find remote branch mastermain master
not found in upstream origin
```

This looks like it could be some sort of line endings issue; Windows occasionally gives us problems. Could you share the output of the following command?

```
git config --global core.autocrlf
```

Also, do you have some sort of wrapper around Git? I'm not sure what `clone.g` means in that output. Please also share the output of

```
type git
```

**Comment by sagebind** [comment]
Also try the solution in #425 to see if that helps.

**Comment by mjameson** [comment]
Had same issue, running "git config --global core.autocrlf false" and then installed correctly.
