### ISSUE TITLE
Assoc and functional plugins

### ISSUE THREAD

**Issue by hanny24** [oh-my-fish/oh-my-fish#493]
Hi,
I have created two simple plugins. First one, assoc (https://github.com/hanny24/assoc) tries to emulate associative arrays using ruby. Second one, functional (https://github.com/hanny24/functional) provides simple higher-order functions (map, filter, fold ...) for fish.

**Comment by bucaran** [comment]
This looks very nice. Good job @hanny24.

I've created two new repos that you can push to and manage yourself. 

+ https://github.com/oh-my-fish/plugin-assoc
+ https://github.com/oh-my-fish/plugin-functional
