### ISSUE TITLE
OhMyFish can't load theme when is started with ENV CWD

### ISSUE THREAD

**Issue by brodock** [oh-my-fish/oh-my-fish#494]
My IDE (RubyMine) has an integrated terminal and I can specificy manually it to use the fish shell. The issue is that it uses the ENV `CWD` to specificy an initial directory that is different from the `HOME` variable.

This is the error I get when trying to load the new terminal:

```
<W> fish: An error occurred while redirecting file '/Applications/RubyMine.app/Contents/plugins/terminal/omf/theme'
open: No such file or directory
<W> fish: An error occurred while redirecting file '/Applications/RubyMine.app/Contents/plugins/terminal/omf/theme'
open: No such file or directory
```

>Operation system: Mac OS: 10.12.3
>fish, version 2.4.0
>Oh My Fish version 5
>git version 2.11.0

**Comment by brodock** [comment]
looks like the CWD is not the issue. This is the relevant part of my ENV:

```
OMF_CONFIG=/Applications/RubyMine.app/Contents/plugins/terminal/omf
OMF_PATH=/Users/brodock/.local/share/omf
PWD=/Users/brodock/some/folder/here
```

**Comment by sagebind** [comment]
@brodock Do you have valid configuration located at `/Applications/RubyMine.app/Contents/plugins/terminal/omf`? As far as I know, using arbitrary paths for `$OMF_CONFIG` without being set up first isn't explicitly supported, though I see no reason why we couldn't support it.

OMF is looking for a text file named `theme` in `$OMF_CONFIG` to determine what the current theme is set to.

**Comment by brodock** [comment]
Ok I figured out what was wrong. For some reason RubyMine cached ENV `SHELL` pointing to the old one which was `/bin/zsh`. After restarting the app it was able to load the theme correctly.
