### ISSUE TITLE
Let's consolidate into only one Fish Framework.

### ISSUE THREAD

**Issue by bucaran** [oh-my-fish/oh-my-fish#498]
I have been a long time contributor at OMF and I learned a lot from this framework. 

In all the good faith that I could gather and wishing this suggestion is well taken I will propose something that may not please the fancy of some of you folks, but I really hope you can see my point. I would like for all of us to work together and consolidate into one and only Fish framework. 

I believe that framework should be [Wahoo](https://github.com/fish-shell/wahoo). I wrote Wahoo to push our shells forward and improve learning from OMF mistakes. 

***If we work together we can take this to the next level.***

To be clear, Wahoo aims to replace OMF. On the other hand, many OMF plugins do work with  [Wahoo](https://github.com/fish-shell/wahoo) with little to no change necessary. I do hope they can be properly migrated though.

### Reasoning

+  [Wahoo](https://github.com/fish-shell/wahoo) was carefully designed __from day one__ to use fishshell powerful features such as autoloading, completions and events _consistently_.

+  [Wahoo](https://github.com/fish-shell/wahoo) has a cleaner and higher level plugin system based in events.

+  [Wahoo](https://github.com/fish-shell/wahoo) is thoroughly documented. Everything you need to know is in the README.

+  [Wahoo](https://github.com/fish-shell/wahoo) is a decentralized package manager. We simply maintain a registry with URLs to packages. You don't even need to be in the registry `wa get <URL>` will attempt to install a package from whatever URL you provide.

  _When  [Wahoo](https://github.com/fish-shell/wahoo) was released, OMF was still a centralized system with plugins and themes living in the same repository. They have improved since then, but each package still requires a repository in the organization, so one has to create a team for each package inside the organization._

+  [Wahoo](https://github.com/fish-shell/wahoo) includes a powerful utility `wa` that lets you get / remove packages, switch themes, scaffold out new packages, submit plugins/themes and even uninstall  [Wahoo](https://github.com/fish-shell/wahoo) itself. There is nothing like this in OMF. This utility is already nearing 500 LOC and I am constantly improving it and fixing the occasional bug.

+ _Wahoo learned from OMF._

> Oh My Fish! was a great project and I learned a lot from it and I am still a maintainer and [top committer](https://github.com/oh-my-fish/oh-my-fish/graphs/contributors?from=2012-07-22&to=2015-07-17&type=a). I rebuilt many of OMF core, help rebuilt the installation system, added many plugins, improved the docs and wrote the test framework (twice), but after much suffering and dealing with a large code base, inconsistent design and poorly written plugins I decided I needed to move on and wanted to apply all this knowledge to create a new, simpler yet more powerful framework.

**Comment by bpinto** [comment]
Thanks @bucaran but honestly, I feel like they are too different. Although I like wahoo, I don't like how it handles packages. I like how our packages are reliable: e.g. the repo will always be there, no matter if the user closes their account on github, omf collaborators check the code so we can check for bad code designs and hacks.

If wahoo would like to change some of its design decisions we could merge. If so, ping here and I'll open some issues on wahoo on things we need to work on there.

**Comment by bucaran** [comment]
I agree with you, which is why I have created the [Wahoo Foundry]() to host _official_ packages and themes, similar to what OMF does, but I still want to give users the choice to download and install what they want, so Wahoo lets you fetch any packages from the URLs listed in the registry as well as just git clone from whatever URL the user specifies.

I don't enforce any particular rules regarding approval of packages into the registry (although I do check the submissions source code). As for packages that are officially listed in the Foundry, the code review and check before acceptance is definitely a must do.

**Comment by bpinto** [comment]
> I agree with you, which is why I have created the Wahoo Foundry to host official packages and themes, similar to what OMF does, but I still want to give users the choice to download and install what they want, so Wahoo lets you fetch any packages from the URLs listed in the registry as well as just git clone from whatever URL the user specifies.

This is too confusing. It should be simple, either it is a official package and all you need to do is to declare it. e.g. Plugin 'rbenv' and if it is not official, you specify the repo, e.g. Plugin 'rbenv', github: 'bucaran/rbenv'.

But I like that you are now convinced that this is a better approach.

I guess the biggest challenge is, wahoo imo is a bad name. As it happened with Rails and Merb, they merged and as Rails had the best name and more users in the database they continued working together using the Rails name. If you are willing to merge and keep omf name, I think we can help each other a lot (as we used to do).

**Comment by bucaran** [comment]
Wahoo's model is more powerful because although I didn't write an actual registry server, the architecture is so that it could be done one day and it would function similar to npm or ruby gems.

The registry of URLs is kept inside the repo, so I could enforce what gets accepted or not, whether I do it or not is a different thing. It could be easily done. I do it all the time. But the system is not designed to enforce owners to code review anything.

I created the foundry just to make it convenient to organize packages and themes in one place and not clob my own gh account with repos.

I would be totally willing to negotiate how this part works, in the this should be transparent to users. All I want is:

```
wa g pkg_name
```

Which is how Wahoo does it right now and it works. So as long as we can keep that easy interface, the internals are tweakable.

The only part that I am not so sure about is the name. I think naming this framework after Oh My Zsh is a dishonor.

**Comment by bpinto** [comment]
> The registry of URLs is kept inside the repo also, so I could enforce what gets accepted or not, whether I do it or not is a different thing :smile: . It could be easily done and I have done every time until now. But the system is not designed to enforce owners to code review anything.

This is the part I don't like and I think is unnecessary. If it's official then it's inside the foundry, if it's not, use your own url if you want. But as you said, it's a matter of changing the internals as the command would still behave the same.

I don't see any problems on naming after Oh My Zsh. It's similar to fish, it sounds very similar to how some pronounce zsh, and it's not a dishonour. They are very different nowadays but that does not mean we can have fun with it. :D

**Comment by bucaran** [comment]
I didn't invent anything new here and that's very similar to how npm works, just that the registry is actually a web server, but the client part which is inside Wahoo already works like this. In the future we could easily create a node-based or rails-based server. I have plans for that later on :stuck_out_tongue_winking_eye:

**Comment by bpinto** [comment]
That could be interesting, indeed!
