### ISSUE TITLE
`omf query` is useless?

### ISSUE THREAD

**Issue by bpinto** [oh-my-fish/oh-my-fish#5]
I have never used `omf query` and I don't think I ever will.

It's only polluting the list of commands. The only time we need such feature is when someone is having an issue with `omf`. Instead of polluting the list of commands, what about renaming it to `debug` and change it's output to a file that people can attach to us when creating an issue?

I was also thinking about adding it to the bottom of the help section, similar to what `git` does:
```
The most commonly used git commands are:
...
   status     Show the working tree status
   tag        Create, list, delete or verify a tag object signed with GPG

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
```

**Comment by derekstavis** [comment]
A footnote looks great, as we can also include the repository URL to report bugs.

**Comment by derekstavis** [comment]
`omf query` can be ditched as soon as #30 is PR'd and merged.

**Comment by bpinto** [comment]
Done!
