### ISSUE TITLE
cbjohnson theme broken on fish 2.4

### ISSUE THREAD

**Issue by daks** [oh-my-fish/oh-my-fish#501]
I recently upgraded to fish 2.4 (Debian testing/Jessie version) and the theme I use (cbjohnson) seems to be broken.

Instead of displaying information about directory, git info (branch, status), I got a "[I]"

`[I] eric at machine in ~`

**edit** : some git info appear but the current directory still not, and the [I] still appear

**Comment by sagebind** [comment]
The `[I]` signifies insert mode of vi key bindings are enabled. See #433.

This is a Fish shell feature: https://fishshell.com/docs/current/index.html#vi-mode

**Comment by daks** [comment]
Thanks a lot. I'll close this issue.
