### ISSUE TITLE
Confuse with the default .config.fish file

### ISSUE THREAD

**Issue by simonbcn** [oh-my-fish/oh-my-fish#501]
I have installed today `oh-my-fish` with the installation script and this is the `.config.fish`:
```
# Path to your oh-my-fish.
set fish_path $HOME/.oh-my-fish

# Path to your custom folder (default path is ~/.oh-my-fish/custom)
#set fish_custom $HOME/dotfiles/oh-my-fish

# Load oh-my-fish configuration.
. $fish_path/oh-my-fish.fish

# Custom plugins and themes may be added to ~/.oh-my-fish/custom
# Plugins and themes can be found at https://github.com/oh-my-fish/
Theme 'robbyrussell'
Plugin 'theme'
```
I'm confusing with the last 2 lines. It lacks documentation here but I see in another pages that to define plugins and themes is used: `set fish_theme ...` and `set fish_plugins ...`. Has this changed?

**Comment by simonbcn** [comment]
ok, I've seen the warning when source the config file:
```
~ source .config/fish/config.fish 
$fish_plugins usage has been deprecated. Please see https://asciinema.org/a/20802.
$fish_theme usage has been deprecated. Please see https://asciinema.org/a/20802.
```
I have corrected the config file but the warning still is showed when I source this file.

**Comment by bpinto** [comment]
We are available https://gitter.im/oh-my-fish/oh-my-fish for quicker fix.
