### ISSUE TITLE
Plugin: Change terminal title

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/oh-my-fish#504]
Here goes a little plugin to change the terminal title.

https://github.com/derekstavis/plugin-title

The usage is pretty simple:

`title <terminal title here>`

Results:

![terminal-title](https://cloud.githubusercontent.com/assets/1611639/9259757/e5906c7a-41d9-11e5-9d25-4e8f2f6c2a28.png)

Rather than using escape codes, this plugin is based on `fish_title` function.

**Comment by jugoncalves** [comment]
:+1:

**Comment by bpinto** [comment]
Sorry for taking so long, I need to find an automatic solution for creating new repos. :dancer: 
Thanks!

**Comment by derekstavis** [comment]
No problem! Now live! And thanks again!
