### ISSUE TITLE
Plugin: Foreign environment variables

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/oh-my-fish#505]
As `nvm-fish` isn't maintained anymore I came across with a plugin that imports into fish all variables modified by a foreign application. You can find it here:

https://github.com/derekstavis/plugin-foreign-env

The plugin works by executing the application inside bash, taking a diff of environment variables and importing them inside fish. Head to the repository for more information on usage.

**Comment by bpinto** [comment]
Created https://github.com/oh-my-fish/plugin-foreign-env and added you as admin. This is going to be a good addition to fish!

**Comment by derekstavis** [comment]
Thanks @bpinto! Pushed!

From now use `fenv` by adding `Plugin "foreign-env"` to your `~/.config/fish/config.fish` file.

**Comment by bpinto** [comment]
Super!

**Comment by jney** [comment]
:+1:
