### ISSUE TITLE
function error

### ISSUE THREAD

**Issue by yuceltoluyag** [oh-my-fish/oh-my-fish#506]
/usr/share/fish/functions/__fish_config_interactive.fish (line 177): 	function __fish_winch_handler --on-signal winch
		commandline -f repaint
                                                                     	^
in function '__fish_config_interactive'
	called on line 137 of file /usr/share/fish/config.fish

in function '__fish_on_interactive'
	called on standard input

in event handler: handler for generic event 'fish_prompt'

137 command line 

#
# Whenever a prompt is displayed, make sure that interactive
# mode-specific initializations have been performed.
# This handler removes itself after it is first called.
#
function __fish_on_interactive --on-event fish_prompt
	__fish_config_interactive
	functions -e __fish_on_interactive
end

**Comment by yuceltoluyag** [comment]
solved the problem

fish-shell/share/functions/__fish_config_interactive.fish
open sublime and delete all code 

https://raw.githubusercontent.com/kergoth/fish-shell/master/share/functions/__fish_config_interactive.fish  COPY all code and change 
savve and restart terminal : )

**Comment by cycoe** [comment]
> solved the problem
> 
> fish-shell/share/functions/__fish_config_interactive.fish
> open sublime and delete all code
> 
> https://raw.githubusercontent.com/kergoth/fish-shell/master/share/functions/__fish_config_interactive.fish COPY all code and change
> savve and restart terminal : )

Follow you instruction, I have solved the same problem now. But could know if this change will be merged into the release branch
