### ISSUE TITLE
edc/bass for bash script support

### ISSUE THREAD

**Issue by jney** [oh-my-fish/oh-my-fish#506]
this project https://github.com/edc/bass looks interesting, and i would like to see it natively integrated in omf. 
what's your opinion ?

**Comment by derekstavis** [comment]
#505 addresses this with native fish script, instead of using a python helper.

**Comment by bucaran** [comment]
@jney  @derekstavis [Wahoo](https://github.com/wa/wahoo) could use support for this too.

**Comment by derekstavis** [comment]
You want a __fenv__ port to Wahoo?

**Comment by bpinto** [comment]
@jney Plugin https://github.com/oh-my-fish/plugin-foreign-env created, you could work with @derekstavis .

**Comment by bpinto** [comment]
@bucaran please raise an issue on Wahoo instead.

**Comment by bucaran** [comment]
@derekstavis Would be nice.
