### ISSUE TITLE
OMF uninstall overwrites fish.config

### ISSUE THREAD

**Issue by smoneck** [oh-my-fish/oh-my-fish#509]
I just executed `./install --offline` to fix a broken omf installation (broken in the sense that the update produced errors that might be on my side).

> Would you like to remove the existing installation? (y/N): y
> This will uninstall Oh My Fish and all plugins and themes from 
> /home/username/.local/share/omf.
> **Your configuration will _not_ be modified. You may need to remove Oh My Fish 
> startup code from /home/username/.config/fish/config.fish.**
> Are you sure you want to continue? (y/N): y
> Uninstalling from /home/username/.local/share/omf...
> **Restoring backup file to /home/username/.config/fish/config.fish**
> Restoring backup file to /home/username/.config/fish/functions/fish_prompt.fish
> Uninstall complete

Are you fuc**** kidding me? I spend hours on writing some functions!

**Comment by sagebind** [comment]
First of all, it is not our intention to delete valuable files, and we take these kinds of issues seriously. I apologize for the frustration we caused you. That being said, not everyone's workflow is the same, and some users get upset if we _don't_ restore your configuration to how it was before you installed OMF (think users who want to just try it out).

I _do_ think what we should do is ask for confirmation before we restore any backups in the installer. This might be slightly annoying for just the `--uninstall` case, but for reinstalling allows the user to decline this operation.

Even better, I think we could either add an explicit `--reinstall` flag, or make reinstalling distinct from uninstall + install. We could also improve the `omf doctor` command to detect more issues and give the ability to reinstall OMF.

**Comment by smoneck** [comment]
Thank you for your reply! It is plain to me that there are no insidious intentions involved here. Nor wouldn't have been this a big deal, if I had stuck to the *backup what's valuable/important*-rule. But one of my points here is a slightly different one:

 1. The declared actions of the installer are in *direct* contradiction to what it tells me it would do if I allow him to. It does what it promised *not to do the line above*. This *effectively* is an evil behaviour.
 2. The is the possibility to delete personal/valuable/important code *at all*. You just *can not* restore the configuration by simply overwriting it with an ancient backup that was somewhen taken without any checks/case handling at all.

Certainly---and I think very well understandable---some users get upset if OMF alters  whatever it alters on it's way without *reversing* it on uninstall but the *only* scenario in which point 2 does *not lead* into trouble is when the user *directly* uninstalls after installation (e.g. when the timestamp of `config.fish` did not change since installation but that should imo not be the scenario with the main focus on). In *every other case* it has to be expected that there is a loss of material by doing so.

So, where do we go? I would say: Don't use backups for restoring at all. Make a backup of `config.fish` in case something goes wrong and then take the OMF content out.
