### ISSUE TITLE
OMF install fails

### ISSUE THREAD

**Issue by smoneck** [oh-my-fish/oh-my-fish#510]
Plain installation fails in `line 306` of https://get.oh-my.fish

> Installing package shark
> fatal: repository 'shark' does not exist
> Could not install shark.
> ...
> Install aborted: Error installing plugins

Fish version 2.5.0
xterm-termite
4.10.13-1-ARCH

**Comment by sagebind** [comment]
@smoneck You probably have `shark` in your bundle file at `$OMF_CONFIG/bundle`, but that package was removed quite a while ago.

**Comment by smoneck** [comment]
Yes, that did it! I supposed that it was a leftover somewhere but I could't find it.
