### ISSUE TITLE
installation via curl is failing

### ISSUE THREAD

**Issue by ChandraKoduru** [oh-my-fish/oh-my-fish#513]
Here is the log
----------------------------------------------------------------

fish install --path=~/.local/bin/omf --config=~/.config/omf
Missing: FILENAME

Usage: head FILENAME [-n|--numlines NUM]
  A bad clone of head
test: Missing argument at index 2
Install aborted: Fish version 2.2.0 or greater required; you have 2.5.0

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues

**Comment by sagebind** [comment]
This seems familiar; my guess is a bad version of `head` is being used. What operating system are you installing on?

**Comment by ChandraKoduru** [comment]
Here are the OS details.

> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

> uname -nmr:
4.4.0-77-generic x86_64

**Comment by ChandraKoduru** [comment]
Found the problem.
I have another binary called 'head' in the path. 

Apologies and thanks
