### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by consultantRR** [oh-my-fish/oh-my-fish#514]
The SSL certificate for  get.oh-my.fish has expired:

```bash
$ echo | openssl s_client -servername get.oh-my.fish -connect get.oh-my.fish:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Feb 17 20:21:00 2017 GMT
notAfter=May 18 20:21:00 2017 GMT
```

**Comment by sagebind** [comment]
@oranja Can we get this renewed?

**Comment by oranja** [comment]
Thanks for the report, @consultantRR.
It's fixed now and I figured out the problem with the renewal cron job, so I hope this won't happen again.
