### ISSUE TITLE
Installation failed, what happened?

### ISSUE THREAD

**Issue by sazure** [oh-my-fish/oh-my-fish#516]
zg@Zhengsus-MacBook-Pro ~/oh-my-fish> bin/install --offline
Existing installation detected at /Users/zg/.local/share/omf
Would you like to remove the existing installation? (y/N): y
This will uninstall Oh My Fish and all plugins and themes from
/Users/zg/.local/share/omf.
Are you sure you want to continue? (y/N): y
Uninstalling from /Users/zg/.local/share/omf...
Uninstall complete
Installing Oh My Fish to /Users/zg/.local/share/omf...
Writing bootstrap to /Users/zg/.config/fish/conf.d/omf.fish...
Setting up Oh My Fish configuration...
Updating https://github.com/oh-my-fish/packages-main master... error: cannot open .git/FETCH_HEAD: Permission denied
Error
Install aborted: Error installing plugins

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues

**Comment by sagebind** [comment]
That's _really_ weird, I've never seen this error before. The interesting bit is:

> Updating https://github.com/oh-my-fish/packages-main master... error: cannot open .git/FETCH_HEAD:
> Permission denied

Oh My Fish stores its package repository cache in `~/.cache/omf` by default. Do you not have permissions to that directory? Please try sending me the output of the following commands:

    stat ~/.cache

    stat ~/.cache/omf

    echo $XDG_CACHE_HOME

    uname -a

**Comment by sazure** [comment]
Ends up I dont have fully write access to some folder. After I chmod all
the folders, the error disappeared.

**Comment by sagebind** [comment]
@sazure That fixing the issues causes the problem to make sense to me then. Glad you got it sorted out! 👍
