### ISSUE TITLE
install failed@infinite loop, macOS

### ISSUE THREAD

**Issue by murray0** [oh-my-fish/oh-my-fish#521]
hi, this is the error message as below:

fish: The function call stack limit has been exceeded. Do you have an accidental infinite loop?
    and __original_fish_user_key_bindings
        ^
in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on standard input

in function '__original_fish_user_key_bindings'
	called on line 41 of file ~/.local/share/omf/init.fish

in function 'fish_user_key_bindings'
	called on standard input

in function '__fish_reload_key_bindings'
	called on line 235 of file /usr/local/Cellar/fish/2.6.0/share/fish/functions/__fish_config_interactive.fish

in function '__fish_config_interactive'
	called on line 211 of file ~/.config/fish/config.fish

in function '__fish_on_interactive'
	called on standard input

in event handler: handler for generic event 'fish_prompt'

the only thing i did is that I install fish with `brew install fish` and my fish was installed to /usr/local/Cellar/fish/2.6.0/ and then i exec soft link by `ln -s /usr/local/cellar/fish/2.6.0/share/fish/config.fish  ~/.config/fish/config.fish`

that's all before i install this framework.

**Comment by murray0** [comment]
now, I have to remove ~/.local/share/omf and ~/.config/fish/conf.d/omf.fish files to silence error message of fish startup

**Comment by sagebind** [comment]
This seems similar to #465.

You should **not** link `~/.config/fish/config.fish` to `/usr/local/cellar/fish/2.6.0/share/fish/config.fish` if I understand correctly, because that will cause a recursion. `share/fish/config.fish` already gets sourced by fish. Since it gets sourced twice, its redefining key binding functions multiple times and breaking stuff.

**Comment by murray0** [comment]
ok, thx
