### ISSUE TITLE
Updating https://github.com/oh-my-fish/packages-main master... error: Your local changes to the following files would be overwritten by merge

### ISSUE THREAD

**Issue by sidahmed-malaoui** [oh-my-fish/oh-my-fish#524]
Whenever I want to install a new package with `omf`, I am getting this error : 

>Updating https://github.com/oh-my-fish/packages-main master... error: Your local changes to the following files would be overwritten by merge:
        LICENSE
        README.md
Please commit your changes or stash them before you merge.
Aborting

I tried to remove `omf` (using `omf destroy`) then installing it back, but now it doesn't even want to install, I get the same error as before : 

>Setting up Oh My Fish configuration...
Updating https://github.com/oh-my-fish/packages-main master... error: Your local changes to the following files would be overwritten by merge:
        LICENSE
        README.md
Please commit your changes or stash them before you merge.
Aborting
Error
Install aborted: Error installing plugins      
Oh My Fish installation failed.
If you think that it's a bug, please open an
issue with the complete installation log here:   
http://github.com/oh-my-fish/oh-my-fish/issues

**Comment by sagebind** [comment]
Your package index is corrupt somehow; you can wipe and retry it by running something like

```fish
rm -rf ~/.cache/omf
```

@oh-my-fish/core We should add a `clear` command or something to make it easy to wipe your index caches.

**Comment by sidahmed-malaoui** [comment]
@sagebind I noticed that each time I remove `omf` then install it back, all my previously installed plugins are automatically reinstalled. Where does `omf` recover my previously installed plugins, and how can I completely remove `omf` ?

**Comment by sagebind** [comment]
@sidahmed-malaoui If you want to do a completely fresh reinstall, you'll have to remove some stuff in `~/.config/omf`, mainly `~/.config/omf/bundle` which saves your installed plugins.

**Comment by sidahmed-malaoui** [comment]
Thanks @sagebind
