### ISSUE TITLE
Cannot install, because of switch-case syntax

### ISSUE THREAD

**Issue by tleh** [oh-my-fish/oh-my-fish#536]
Hey, i'm always getting the following error: 

```
'case' builtin not inside of switch block
~/.config/fish/config.fish (line 42): case $- in
                                      ^
from sourcing file ~/.config/fish/config.fish
        called during startup

fish: Unknown command 'omf install'
Install aborted: Error installing plugins
```

tried different things, but no solution found

**Comment by oranja** [comment]
Hi @tleh,

First, you left some important details out of your report:
`fish --version`, `git --version`, operating system?

Next, the line of code that causes this error doesn't come from Oh-My-Fish.
It seems like your `config.fish` has some script snippets from another shell.
`$-` is not a valid name for a variable in `fish`.

**Comment by tleh** [comment]
hi @oranja 
`fish --version --> 2.2.0`
`git --version --> 2.7.4`
OS --> Ubuntu 16.04 LTS

is there a way to determine which scripts can conflict the oh-my-fish config?
i have no idea where the `$-` comes from
i just fowarded the output

**Comment by oranja** [comment]
Can you take a look in `~/.config/fish/config.fish`, around line number 42 and paste a snippet of the script here (redact any personal/sensitive information), or at least try to understand the context?

**Comment by tleh** [comment]
```
19 
 20 # Load Oh My Fish configuration.
 21 source $OMF_PATH/init.fish
 22 # Path to Oh My Fish install.
 23 set -q XDG_DATA_HOME
 24   and set -gx OMF_PATH "$XDG_DATA_HOME/omf"
 25   or set -gx OMF_PATH "$HOME/.local/share/omf"
 26 
 27 # Load Oh My Fish configuration.
 28 source $OMF_PATH/init.fish
 29 # Path to Oh My Fish install.
 30 set -q XDG_DATA_HOME
 31   and set -gx OMF_PATH "$XDG_DATA_HOME/omf"
 32   or set -gx OMF_PATH "$HOME/.local/share/omf"
 33 
 34 # Load Oh My Fish configuration.
 35 source $OMF_PATH/init.fish
 36 # Path to Oh My Fish install.
 37 set -q XDG_DATA_HOME
 38   and set -gx OMF_PATH "$XDG_DATA_HOME/omf"
 39   or set -gx OMF_PATH "$HOME/.local/share/omf"
 40 
 41 # Load Oh My Fish configuration.
 42 source $OMF_PATH/init.fish
 43 # Path to Oh My Fish install.
 44 set -q XDG_DATA_HOME
 45   and set -gx OMF_PATH "$XDG_DATA_HOME/omf"
 46   or set -gx OMF_PATH "$HOME/.local/share/omf"
 47 
 48 # Load Oh My Fish configuration.
 49 source $OMF_PATH/init.fish
 50 
 51 # ~/.bashrc: executed by bash(1) for non-login shells.
 52 # see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
 53 # for examples
 54 
 55 # If not running interactively, don't do anything
 56 case $- in
 57     *i*) ;;
 58       *) return;;
 59 esac
 60 
 61 # don't put duplicate lines or lines starting with space in the history.
 62 # See bash(1) for more options
 63 HISTCONTROL=ignoreboth
```

**Comment by oranja** [comment]
So:
Lines 20-49 are part of OMF's code.
Lines 51-63 are supposedly a copy of your `~/.bashrc` file.
I have no idea how it got there, but it should not be there, and I find it impossible to believe that it is was copied by OMF's installer.

I suggest that you rip these lines (51-63) out of `config.fish`* and then try to install / use OMF as usual.
Let me know how it went.

* I'm supposed to tell you to take a backup first, and it's always a good idea, but: (1) it's right here as a backup. (2) it really doens't belong in a `fish` script.

**Comment by tleh** [comment]
wow thats strange, the code listing was only a snippet, it copied my whole `.bashrc` content into `config.fish`

after deleting the bashrc content, it worked without problems
thank you!

should i close the issue, or do u want to investigate further into the config bashrc copying issue?

**Comment by oranja** [comment]
You may close the issue. I'm just a contributer, so I can't close the issue even if I wanted to.

If the same issue will pop up again we'll investigate further.
At this point I'm personally still pretty confident that this is something external to OMF.

**Comment by tleh** [comment]
ok thanks for your support!
