### ISSUE TITLE
Readme correction

### ISSUE THREAD

**Issue by thorstenkampe** [oh-my-fish/oh-my-fish#540]
Project Readme says `Oh My Fish installer places its startup code in your fish config file (~/.config/fish/config.fish).`. Actually it goes into `~/.config/fish/conf.d/omf.fish`.

**Comment by sagebind** [comment]
Good catch! Actually this used to be true, and still is for Fish 2.2.0 I believe. We should correct the README to explain that.

**Comment by sagebind** [comment]
This was resolved with #546.
