### ISSUE TITLE
The certificate for oh-my.fish has expired

### ISSUE THREAD

**Issue by forsen** [oh-my-fish/oh-my-fish#544]
The certificate has expired, which breaks the default installer:

`curl -L https://get.oh-my.fish | fish`

**Comment by oranja** [comment]
My bad again. Fixed.

**Comment by geekpete** [comment]
Seems still not to work.

Running from OSX: 

```
curl -vvv -L https://get.oh-my.fish | fish
* Rebuilt URL to: https://get.oh-my.fish/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 5.79.97.250...
* TCP_NODELAY set
* Connected to get.oh-my.fish (5.79.97.250) port 443 (#0)
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0* Server aborted the SSL handshake
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
* Closing connection 0
curl: (35) Server aborted the SSL handshake
```

Curl Version:
```
curl --version
curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

**Comment by geekpete** [comment]
Though this works:

```
curl -L https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
Setting up Oh My Fish configuration...
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package default
✔ default successfully installed.
Installation successful!
Welcome to fish, the friendly interactive shell
```

In Chrome when I browse to https://get.oh-my.fish I first see a `site cannot be reached` then it redirects to that github url. In firefox it just sits there doing `Performing a TLS handshake`

**Comment by geekpete** [comment]
Darwin Peters-MBP-2 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by oranja** [comment]
For some reason the old server's IP address remained listed in the DNS
configuration for the domain.
I removed it now again and it should be sorted out within minutes.

**Comment by roychoo** [comment]
it is still the same.

**Comment by oranja** [comment]
This time it wasn't SSL related. I just had to take the server down for maintenance for a few minutes.
Sorry for the inconvenience.

**Comment by firstchair** [comment]
Its again expired at 4 November 2021...

**Comment by scorphus** [comment]
Please use the current official one:

    curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
