### ISSUE TITLE
How to change the color of time displayed in flash theme ?

### ISSUE THREAD

**Issue by HanielF** [oh-my-fish/oh-my-fish#549]
I installed the flash theme before and i changed the color of terminal background to grey.
I noticed that the color of time is unnormal.
Just like the screenshot below.
How to change the color of it?
![image](https://user-images.githubusercontent.com/24732516/29877520-76ba43e6-8d65-11e7-94dd-84cb37d94b43.png)

**Comment by oranja** [comment]
The colors for this theme are hard-coded in the theme sources:
```fish
function flash_fst; set_color -o fa0; end
function flash_snd; set_color -o C00; end
function flash_trd; set_color -o 666; end
function flash_dim; set_color -o 333; end
function flash_off; set_color normal; end
```

The gray that is used to the
You can either try to reach the author or

**Comment by HanielF** [comment]
Thank you very much .
I finded it in `$OMF_PATH/themes/flash/fish_prompt.fish` and located it in `$OMF_PATH/themes/flash/fish_right_prompt.fish` .
Then I changed `(flash_dim)%M` into `(flash_trd)%M`, and the problem was solved.
![image](https://user-images.githubusercontent.com/24732516/29956737-c8201770-8eae-11e7-93ec-67c08cae84f7.png)
