### ISSUE TITLE
Agnoster theme don't shows arrow

### ISSUE THREAD

**Issue by christianmtr** [oh-my-fish/oh-my-fish#558]
I did installed and activate agnoster and it don't shows the arrowhead in my prompt.

I'm using Xubuntu's terminal, and I tested in Terminator and the same issue.
I see  at end of the aech line, the colors ends before.

What can I do??

**Comment by bobthecow** [comment]
Agnoster requires a powerline-patched font for the arrows and git glyphs. I'd recommend choosing one of these: https://github.com/ryanoasis/nerd-fonts

**Comment by christianmtr** [comment]
I'm trying to install that fonts, I did clone the repo and ran the install script but nothing happens.
Anyway, thanks for the response.

**Comment by oranja** [comment]
Next step is to go back to the terminal emulator you're using and set one of the newly installed fonts as the font for the terminal.
As a sanity test, you may try something dramatic with the font size first, just to make sure that the changes you make do have an effect. With `Konsole`, for example, I often run into an issue by making changes to some profile that's not currently in use.

**Comment by christianmtr** [comment]
I installed with pip powerline-status and powerline-shell, i think that with the last it works, and I had to change the font of my terminal, now looks great!
Thanks you guys!
