### ISSUE TITLE
Regarding the copyright of the current source code

### ISSUE THREAD

**Issue by bucaran** [oh-my-fish/oh-my-fish#56]

**Comment by bucaran** [comment]
/cc
@bpinto @bobthecow @bucaran @rominf @derekstavis @tannhuber @jhillyerd @scorphus @skk @krisleech @jacaetevha @tripleplus @felipero @jeremiejig @vincent-psarga @farao @ngroup @sheldon @syl20bnr @joar @amio @jacobono @theonewolf @xorgy @lvicentesanchez @godfat @kiRach @jonknapp @beloglazov @cap10morgan @tanob @iven @daveyarwood @numist @charlesbjohnson @RobDay @wzhishen @sn0cr @JBarberU @taktoa @wk @Paulloz @rahult @exdis @JeanMertz @idan @CodeFalling @Bastes @uggedal @ramitos @peteretep @ohspite @nirvdrum @liquid @dgarrett @natrim @Lavoaster @jonathanpa @erikkallen @zhuangya @CyberShadow @osamu2001 @vincentjames501 @williamhogman @dan-c-underwood @janlindblom @exzz @CADBOT @greggles @steeeve @ilkosta @michelegera @oneKelvinSmith @nesl247 @joshuawarner32 @jcouyang @celsomiranda @daenney @unbalancedparentheses @kholbekj @bbbenji @adevore @ccwang002 @inxilpro @Fryie @froztbyte @despairblue @Mic92 @fibric @zdavison @KnightHawk3 @phaedryx @aznashwan @andyklimczak @mtahmed @josiahsprague @hsharrison @talios @lloydde @andrelfpinto

**Comment by bucaran** [comment]
@peteretep @ohspite @nirvdrum @liquid @dgarrett @natrim @Lavoaster @jonathanpa @erikkallen @zhuangya @CyberShadow @osamu2001 @vincentjames501 @williamhogman @dan-c-underwood @janlindblom @exzz @CADBOT @greggles @steeeve @ilkosta @michelegera @oneKelvinSmith @nesl247 @joshuawarner32 @jcouyang @celsomiranda @daenney @unbalancedparentheses @kholbekj @bbbenji @adevore @ccwang002 @inxilpro @Fryie @froztbyte @despairblue @Mic92 @fibric @zdavison @KnightHawk3 @phaedryx @aznashwan @andyklimczak @mtahmed @josiahsprague @hsharrison @talios @lloydde @andrelfpinto

**Comment by derekstavis** [comment]
Just for the record: There are a lot of moderated messages in https://github.com/wa/wahoo/issues/95, including the one which @bpinto manifest his opinion on the matter. I have all emails sent from Github stored and the number of moderated messages are scary.

![screen shot 2015-09-19 at 4 46 43 pm](https://cloud.githubusercontent.com/assets/1611639/9977887/078c9b74-5eee-11e5-8b2b-5ad54999618e.png)

**Comment by bpinto** [comment]
My message has been deleted and the thread locked. It is sad that the truth is being manipulated by @bucaran. Luckily the information is out there in the Internet for everyone to see.
