### ISSUE TITLE
Installation error on WSL/Windows Bash

### ISSUE THREAD

**Issue by codepunkt** [oh-my-fish/oh-my-fish#565]
Windows 10, Build 15063

```
curl -L http://get.oh-my.fish | fish
source: Error encountered while sourcing file “/root/.local/share/omf/init.fish”:
source: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0   1146      0 --:--:-- --:--:-- --:--:--  1147
100 16622  100 16622    0     0   2309      0  0:00:07  0:00:07 --:--:-- 50217
Installing Oh My Fish to /root/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Setting up Oh My Fish configuration...
 to clone.g: Could not find remote branch mastermain master
 not found in upstream origin
Error
Install aborted: Error installing plugins

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues
```

It breaks somewhere around (probably?) cloning/fetching stuff from oh-my-fish/packages-main. Will gladly add the complete installation log - if someone helps me find it!

**Comment by oranja** [comment]
Hi @codepunkt,
This is weird.. the output looks garbled. Much mysterious.

A few questions to narrow down the search:
1. Which version of `fish` is that?
2. Which version of `git` are you using? Is it Git for Windows or some git version that comes with the WSL?
3. Do you have any otherwise unique git setup? Unusual aliases or settings?
4. Does the file `/root/.local/share/omf/init.fish` exist?
5. Have you had OMF installed on this system before?

By the way, did you intend to install OMF for the `root` user? Does it work for a "regular" user? Are you running under `su` perhaps?

**Comment by codepunkt** [comment]
I could not find the bug yesterday and you had not answered yet. I need to get on with my work and need a suitable terminal for that, so i simply started from scratch with a fresh install of the windows subsystem for linux.

Everything works as expected now.

It's a bit of a pity because we can't find out what the deal breaker was - so i'm sorry for that.
Thanks for your interest & answer though. Very appreciated!

**Comment by andb0t** [comment]
I have the same problem.

1. fish version 2.6.0
2. git version 2.7.4
3. My git setup:
```
[alias]
st = status
ci = commit
co = checkout
lola = log --graph --decorate=full\n--pretty=oneline --abbrev-commit --all
logf = "!echo \"Remember to add -S<string>\" ; git log --color -p --source --all"
[color]
ui = true
diff = auto
status = auto
[core]
excludesfile = /dev/null
editor = vim
        autocrlf = true
[branch]
autosetuprebase = always
[push]
default = simple
```
4. no
5. I'm not running under sudo, simply running `curl -L https://get.oh-my.fish | fish` in a new bash shell

**Comment by oranja** [comment]
@andb0t 
Two things to check first:
1. That git is Linux build and not pointing to Git for Windows.
See: `whereis git`, and assuming that the first entry is `/usr/bin/git`, make sure that it's not just a symlink to the Windows version.
2. If removing the `autocrlf = true` line from configuration helps anything.
We've seen issues with it before. It tends to mess things up for `fish` when it's set.

**Comment by andb0t** [comment]
Hi, thanks for the answer! I have in the meantime decided to use zshell and customize it myself, which gives me more freedom. For the sake of this issue, I will anyway try to provide the info as far as I can without installing fish.

1. I use the Linux git, which is not a symlink
```shell
$ whereis git
git: /usr/bin/git /mnt/c/Program Files/Git/cmd/git.exe /usr/share/man/man1/git.1.gz
$ ls -l /usr/bin/git                                                                                                                                                       
-rwxr-xr-x 1 root root 1866896 Oct  4 20:22 /usr/bin/git
```
2. That, unfortunately, I cannot verify now without reinstalling fish and oh-my-fish.

**Comment by nwykes** [comment]
I wonder if this has something to do with using /root as the home?  Maybe a rights thing?

I checked my two windows VMs where I have previously setup fish and omf and both use /home/username.  I setup a new VM to test it from scratch and it uses /home/username as well.
