### ISSUE TITLE
local changes to packages/fish_logo prevents update

### ISSUE THREAD

**Issue by keevee09** [oh-my-fish/oh-my-fish#567]
~> omf update
    Oh My Fish is up to date.
    You are now using Oh My Fish version 6.
    Updating https://github.com/oh-my-fish/packages-main master... error: Your local changes to the following files would be overwritten by merge:
	packages/fish_logo
    Please commit your changes or stash them before you merge.
    Aborting
    Error

    ~/.local/share/omf> git status                                  1 3s 324ms
    HEAD detached at v6
    nothing to commit, working tree clean

How do I commit or stash the change requested in order to update and install omf packages and themes?

**Comment by oranja** [comment]
The local git repository which is raising this issue is probably:
`~/.cache/omf/https___github.com_oh-my-fish_packages-main_master`
Try `git status` there
(or `git -C ~/.cache/omf/https___github.com_oh-my-fish_packages-main_master status`)

**Comment by keevee09** [comment]
@oranja : Your suggestion is correct.
I changed to said directory and ran

    ~/.cache/omf/https___github.com_oh-my-fish_packages-main_master$ git stash
    ~/.cache/omf/https___github.com_oh-my-fish_packages-main_master$ git pull

then  ran

    ~/.cache/omf/https___github.com_oh-my-fish_packages-main_master$ omf update

which worked.

**Comment by scorphus** [comment]
Thanks, @oranja 👍

**Comment by bobthecow** [comment]
Would it make sense to try to stash -> update -> pop to preserve local modifications but still allow updating?
