### ISSUE TITLE
How to install Powerline ?

### ISSUE THREAD

**Issue by Deathlive** [oh-my-fish/oh-my-fish#568]
installed OMF and the  BobtheFish theme , but some characters are no visible.
When installing Agnoster theme, also.
How to correctly install the Powerline ?

**Comment by bobthecow** [comment]
You just need to use a powerline patched font. See the readme for bobthefish for links!

**Comment by Deathlive** [comment]
@bobthecow I installed font https://github.com/powerline/fonts
but when I write `echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"` 
shows `\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699` , so to speak check.

**Comment by oranja** [comment]
And without the quotes?
Just `echo \ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699`

**Comment by Deathlive** [comment]
@oranja 
wrote without quotes, instead `\ue0b0  \ue0a0` square.

**Comment by oranja** [comment]
See my edit. Did you set the font to a powerline font in your terminal emulator? (iTerm2, gnome-terminal, konsole, etc..)

**Comment by Deathlive** [comment]
@oranja sorry but how to install it ?
if you about pip install powerline-status, then yes.

**Comment by Deathlive** [comment]
@oranja I just use Termux(Terminal Emulator Android), and there it is not possible to select a font powerline

**Comment by oranja** [comment]
To change the font in Termux to Powerline fonts you need the **Termux:Styling** add-on.
You can support the developer buy buying it from the [Play Store](https://play.google.com/store/apps/details?id=com.termux.styling) for less than (USD) $3, or directly get the apk from [F-Droid](https://f-droid.org/packages/com.termux.styling/). (It's an open-source add-on, so it's legal)
