### ISSUE TITLE
Unknown command 'omf', after fresh install

### ISSUE THREAD

**Issue by bytesizedpcs** [oh-my-fish/oh-my-fish#574]
The plugin for omf 'tmux-zen' busted my install of omf, but now every time I try to fresh install omf it installs all of the plugins in the previous install of omf, and also the busted plugin 'tmux-zen'. How do I stop it from installing these plugins?

`austin at Austins-MacBook-Pro in ~
» curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   140  100   140    0     0    407      0 --:--:-- --:--:-- --:--:--   407
100 16622  100 16622    0     0  26916      0 --:--:-- --:--:-- --:--:-- 26916
Existing installation detected at /Users/austin/.local/share/omf
Would you like to remove the existing installation? (y/N): <W> fish: No TTY for interactive shell (tcgetpgrp failed)
setpgid: Inappropriate ioctl for device
austin at Austins-MacBook-Pro in ~
» omf doctor
fish: Unknown command 'omf'
austin at Austins-MacBook-Pro in ~
» fish -v
fish, version 2.6.0
austin at Austins-MacBook-Pro in ~
» rm -rf ~/.local/share/omf/
austin@Austins-MacBook-Pro ~> rm ~/.config/fish/conf.d/omf.fish
austin@Austins-MacBook-Pro ~> clear
austin@Austins-MacBook-Pro ~> echo yes | fish read-bug
read-bug: No such file or directory
austin@Austins-MacBook-Pro ~> curl -L https://get.oh-my.fish | fish

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0    275      0 --:--:-- --:--:-- --:--:--   275
100 16622  100 16622    0     0  16688      0 --:--:-- --:--:-- --:--:--  115k
Installing Oh My Fish to /Users/austin/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Writing bootstrap to /Users/austin/.config/fish/conf.d/omf.fish...
Setting up Oh My Fish configuration...
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package config
✔ config successfully installed.
Installing package tmux-zen
✔ tmux-zen successfully installed.
Installing package cbjohnson
✔ cbjohnson successfully installed.
Installing package default
✔ default successfully installed.
Installation successful!
no server running on /private/tmp/tmux-501/default
lost server
austin@Austins-MacBook-Pro ~> omf doctor
fish: Unknown command 'omf'`

**Comment by sagebind** [comment]
@bytesizedpcs Your plugin preferences are stored in `~/.config/omf/bundle`, which is always persisted. If you don't want a package to be installed for you, you can remove it from that file so that it is not downloaded automatically.

**Comment by bytesizedpcs** [comment]
I got it fixed, but I'm honestly not sure how.

I uninstalled omf using `brew`, deleted all relevant files connected to it, such as `/.config/omf` and reinstalled everything again and it worked (only after 4 or 5 times uninstalling and reinstalling)

**Comment by Vistaus** [comment]
I have the same problem. fish also reports "unknown command 'omf'" after a fresh install on Solus with the latest fish.
