### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by krzkrzkrz** [oh-my-fish/oh-my-fish#58]
How would one go about uninstalling this? Is it just a matter or removing `~/.config/omf`and removing any references from `~/.config/fish/config.fish`?

**Comment by bpinto** [comment]
It would. We also have a omf destroy command that you assist you.

**Comment by bobthecow** [comment]
Also remove `~/.local/share/omf`. The library lives there, your local config lives in `~/.config/omf`.

**Comment by krzkrzkrz** [comment]
Thanks for that
