### ISSUE TITLE
Error installing plugins

### ISSUE THREAD

**Issue by denningsrogue** [oh-my-fish/oh-my-fish#580]
I get the following error when I try to install regardless of the method used:

Updating https://github.com/oh-my-fish/packages-main master... error: Your local changes to the following files would be overwritten by merge:
	packages/emacs
	packages/fishbone
Please commit your changes or stash them before you merge.
Aborting
Error
Install aborted: Error installing plugins

**Comment by sagebind** [comment]
Please see #567.
