### ISSUE TITLE
How to add last two levels of PWD to prompt?

### ISSUE THREAD

**Issue by hisnawi** [oh-my-fish/oh-my-fish#583]
I really like the pure theme but the only thing missing for me is the ability to see the last two directory names in the prompt. Example:

test1/test2 > 

How is that possible? What code do I need to add/change in able to get this addition?
I understand this is not a bug or issue, but I have no idea where else to ask about this.

**Comment by sagebind** [comment]
The `pure` theme is here: https://github.com/rafaelrinaldi/theme-pure

You could fork it and modify it, and then use your forked version. Or maybe talk to the theme author about adding some features.
