### ISSUE TITLE
Question marks instead of icons with some themes

### ISSUE THREAD

**Issue by Vistaus** [oh-my-fish/oh-my-fish#588]
Some themes include something special, like an icon or arrow or something like that. But I only get question marks. I don't know where to start debugging. All I can tell is that I'm using Solus (Linux), the latest stable Fish, latest stable Oh My Fish and the latest stable Guake (terminal).

Can anyone help me?

**Comment by nwykes** [comment]
Some themes require a powerline font.  https://github.com/ryanoasis/nerd-fonts is a good source to find some.

**Comment by Vistaus** [comment]
Thanks. I've installed a few and set them but it doesn't help :(

**Comment by Vistaus** [comment]
I'll close this as it seems to be an issue with Guake. The themes work fine in Tilix.
