### ISSUE TITLE
where i can find packages?

### ISSUE THREAD

**Issue by nanotime** [oh-my-fish/oh-my-fish#59]
Is a pretty basic question but, ok `omf install {{packagename}}`... cool, but i'm new with this and i don't know any index of packages or something... are independient in they own repos? are they in the same repo of OMF? can i list them in the terminal like themes? some hint here? 

I know that my question is pretty stupid but, really im googling and get nothing D:

**Comment by derekstavis** [comment]
At this moment you can browse our core-supported plugins and themes on our profile:

https://github.com/oh-my-fish?utf8=✓&query=plugin
https://github.com/oh-my-fish?utf8=✓&query=theme

But as package system is decentralised you can browse all packages available in the registry:

https://github.com/oh-my-fish/oh-my-fish/tree/master/db/pkg
https://github.com/oh-my-fish/oh-my-fish/tree/master/db/theme

We are working to bring better documentation of available packages back into this repository. #55 are working on theme previews, and should be merged soon. Probably there should be a also package list in the near future.

**Comment by bpinto** [comment]
If you type omf list you will be able to see a list of packages to install, or just do omf install and hit tab for autocomplete.

**Comment by derekstavis** [comment]
I have compiled a plugin list here:

https://gist.github.com/derekstavis/26b7fc254cbc9bc4d461

**Comment by nanotime** [comment]
Hey! Thanks dudes!

**Comment by Darkless012** [comment]
For those who will need this in future (including me):
You can list and browse all the available packages from terminal: `omf search '.*' | less`
