### ISSUE TITLE
Change color of the font

### ISSUE THREAD

**Issue by natashh** [oh-my-fish/oh-my-fish#592]
Hello,

How to change the colour of the font in OMF ?

http://prntscr.com/iady8i

I want
ssh fw-pl-dc4 - brighter 
-01-secondary - want to change colour too, to diffrent one.

I am using iTerm2 with Color Preset - Solarized Dark which allow me to change some colors but not all.

**Comment by sagebind** [comment]
There are two things here:

- Most themes use "general" colors, like `cyan` or `red`, and it is up to the terminal to choose what those names map to. These names are usually hard-coded in most themes though. You would have to fork and modify the theme to use different general colors for different things.
- Specific themes have specific colors they use, like a hex color code. You would have to fork and modify the theme to change those.

You may want to create your own theme if you want this level of customization, or find a theme that has configurable colors. It is up to the author of each theme to offer configuration points.
