### ISSUE TITLE
Wrongly generated year in LICENSE of new theme

### ISSUE THREAD

**Issue by kfkonrad** [oh-my-fish/oh-my-fish#593]
- Operating System: macOS Sierra 10.12.6
- Fish Version: 2.7
- Oh My Fish Version: 6
- Git version: 2.4.3 (Apple Git-98)

Generating a new theme using `omf n theme myname` I get a LICENSE file beginning with:
```
The MIT License (MIT)

Copyright (c) 2016 Kevin Konrad

Permission is hereby granted, free of charge, to any person obtaining a copy
```

That value should be generated some command like `date +%Y`, but it looks like it's hard-coded or not generated correctly.

Expected behaviour: Third line of LICENSE should be `Copyright (c) 2018 Kevin Konrad`

**Comment by pxgamer** [comment]
Running that looks like it uses this as the template.
https://github.com/oh-my-fish/oh-my-fish/blob/master/pkg/omf/templates/themes/LICENSE

I guess a PR would be a temporary fix, but it should probably be dynamic as you stated.

**Comment by sagebind** [comment]
Thanks for raising this issue. The `omf new` command definitely needs some work as it hasn't been touched in some time. This is just one of the small issues...

I'll put this on the docket to be fixed for now using a variable substitution.
