### ISSUE TITLE
Will not install - edit: not entirely true, but still major issues

### ISSUE THREAD

**Issue by KadenGordon** [oh-my-fish/oh-my-fish#594]
It will not install for me. I am running Linux Mint 18. I ran it with --verbose and here is what I got:

DEBUG: verbose turned on
Checking for a sane environment...
DEBUG: Command 'awk' is /usr/bin/gawk
DEBUG: Command 'basename' is /usr/bin/basename
DEBUG: Command 'cp' is /bin/cp
DEBUG: Command 'cut' is /usr/bin/cut
DEBUG: Command 'date' is /bin/date
DEBUG: Command 'dirname' is /usr/bin/dirname
DEBUG: Command 'env' is /usr/bin/env
DEBUG: Command 'fish' is /usr/bin/fish
DEBUG: Command 'fold' is /usr/bin/fold
DEBUG: Command 'head' is /usr/bin/head
DEBUG: Command 'mkdir' is /bin/mkdir
DEBUG: Command 'mv' is /bin/mv
DEBUG: Command 'readlink' is /bin/readlink
DEBUG: Command 'rm' is /bin/rm
DEBUG: Command 'sed' is /bin/sed
DEBUG: Command 'sort' is /usr/bin/sort
DEBUG: Command 'tar' is /bin/tar
DEBUG: Command 'tr' is /usr/bin/tr
DEBUG: Command 'which' is /bin/which
DEBUG: Checking for a sane 'head' implementation
DEBUG: Checking for a sane 'sort' implementation
DEBUG: Checking for a working AWK interpreter
DEBUG: Verifying Git implementation is not buggy Git for Windows
DEBUG: Verifying Git autocrlf is not enabled
Existing installation detected at /home/kaden/.local/share/omf
Would you like to remove the existing installation? (y/N): y
This will uninstall Oh My Fish and all plugins and themes from 
/home/kaden/.local/share/omf.
Your configuration will not be modified. You may need to remove Oh My Fish 
startup code from /home/kaden/.config/fish/config.fish.
Are you sure you want to continue? (y/N): y
Uninstalling from /home/kaden/.local/share/omf...
Uninstall complete
Installing Oh My Fish to /home/kaden/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Setting up Oh My Fish configuration...
Updating https://github.com/oh-my-fish/packages-main master... error: Your local changes to the following files would be overwritten by merge:
	packages/one
Please, commit your changes or stash them before you can merge.
Aborting
Error
Install aborted: Error installing plugins

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues

**Comment by KadenGordon** [comment]
EDIT: omf command did install, however, pretty well nothing can be done with it. Clarification on details, I have not edited, or touched, any file that was generated by omf

Details:

omf install pure
Updating https://github.com/oh-my-fish/packages-main master... error: Your local changes to the following files would be overwritten by merge:
	packages/one
Please, commit your changes or stash them before you can merge.
Aborting
Error

**Comment by sagebind** [comment]
This looks like the same issue as #567. I'm not sure how the package database gets into this state though. Basically the package repo has uncommitted changes in it and it needs to be either reset or just blown away.
