### ISSUE TITLE
Installation on WSL failed

### ISSUE THREAD

**Issue by qnaalx** [oh-my-fish/oh-my-fish#597]
The installation on Windows 10 Linux Subsystem failed with the following argument.
```
curl -L https://get.oh-my.fish | fish

Checking for a sane environment...
type: invalid option -- 'q'
Install aborted: Missing required command: awk
```
AWK ist installed  
```
awk --version
GNU Awk 4.0.1
```

**Comment by sagebind** [comment]
> type: invalid option -- 'q'

This looks very odd to me. What version of Fish are you running?

**Comment by JackyWangMislantiaJnirvana** [comment]
The same problem.

```
curl -L https://get.oh-my.fish | fish
Checking for a sane environment...
type: invalid option -- 'q'
Install aborted: Missing required command: awk
```
```
fish -v
fish, version 2.0.0
```

**Comment by qnaalx** [comment]
> So maybe the problem is that the default version installed from apt-get is too old.

Yes indeed. Thats the problem.
Solution is

```
sudo apt-add-repository ppa:fish-shell/release-2
sudo apt-get update
sudo apt-get install fish
```

AND upgrade a newer version of git (mine was 1.9.1)

```
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git
```

Its not a problem of omf, just WSL with older versions of everything :)

But the solution is in this post.
