### ISSUE TITLE
OMF fails to update

### ISSUE THREAD

**Issue by bronzehedwick** [oh-my-fish/oh-my-fish#60]
I get the following error on Mac OS X 10.10.5 when running `omf update`:

```
Oh My Fish failed to update.
Please open a new issue here → git.io/omf-issues
```

I have two factor authentication turned on, and generated an access token to use for my password.

**Comment by derekstavis** [comment]
You need to update your Oh My Fish remote:

    omf cd
    git remote rm upstream
    git remote add upstream https://github.com/oh-my-fish/oh-my-fish.git

Or do a clean install accodingly to https://github.com/oh-my-fish/oh-my-fish#update-instructions

**Comment by bronzehedwick** [comment]
Perfect, that worked. Thanks!
