### ISSUE TITLE
Powerline corrupts themes [Huge entry space]

### ISSUE THREAD

**Issue by MatzeS** [oh-my-fish/oh-my-fish#600]
### Symptomps
![powerline](https://user-images.githubusercontent.com/3418055/37881334-d2e085de-3096-11e8-879e-521d53348d95.png)

1. The first command character is missaligned, many spaces in between.
2. Similarly, a possible git branch marker, which I assume should be at the end of the command line is missaligned and pulled to the center.
3. This is not the actual expected theme. running powerline-setup overwrites the current theme end even forces some theme on the shell which cannot be replaced/removed by `omf t default`.

### Setup
I am running arch linux and you are looking konsole. 
fish, omf and powerline were installed 'the recommended way' - meaning the most obvious, generally first mentioned way. After ~2 hours of experiments I believe everything is setup correctly. Also, I assume this not to be a version issue since the system is 2 days old. (However, this is my first arch and fish setup).

Yet:
fish 2.7.1
omf 6
git 2.16.2

### Possible cause
is the powerline-setup script. I do not understand what it is doing or should do. However, this script breaks omf themes completly and causes this wiered missalignments.

Any ideas what could cause this or how to fix it?

**Comment by erik-linden** [comment]
I had similar symptoms, and they went away when I fixed a problem with my `locale`.
Essentially, I was having [this problem](https://askubuntu.com/questions/144235/locale-variables-have-no-effect-in-remote-shell-perl-warning-setting-locale-f).

**Comment by sagebind** [comment]
Closing as this doesn't seem to be OMF's fault. Feel free to reopen or create a new issue if you find more problems. Thanks!
