### ISSUE TITLE
Remove caret (^)

### ISSUE THREAD

**Issue by hamon-e** [oh-my-fish/oh-my-fish#609]
The caret operator as been remove in the master branch of fish-shell
so the installation script isn't working anymore

**Comment by spacekookie** [comment]
Can confirm, using `fish, version 2.7.1-1117-ge02e485c`, can still install stuff but the output is very spammy...

**Comment by faho** [comment]
Note from the fish team: This is now hidden behind a "feature" flag, so it will still be available by default but can be turned off.

The intention is still to remove it (and the `?` glob).

**Comment by bobthecow** [comment]
I opened a few pull requests 😛☝️
