### ISSUE TITLE
Bad font rendering arrows in theme bobthefish

### ISSUE THREAD

**Issue by retyui** [oh-my-fish/oh-my-fish#610]
I install the theme [bobthefish](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md#bobthefish)
But I have problem with font rendering `arrows >`
![image](https://user-images.githubusercontent.com/4661784/39467563-5ac96b02-4d37-11e8-9133-d8b4e85597de.png)

```bash
uname -a                                            Вт 01 май 2018 12:04:40
Linux i 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by oranja** [comment]
Do you have powerlines font installed?
If not, search older issues here.

**Comment by retyui** [comment]
Thank you!)
```bash
sudo apt-get install fonts-powerline
```
