### ISSUE TITLE
How to use omf in a script ?

### ISSUE THREAD

**Issue by charveey** [oh-my-fish/oh-my-fish#619]
Hi, I've written a little script to automatically switch between dark and light variant of my theme according to time.
![deepin capture-ecran_zone de selection _20180617010042](https://user-images.githubusercontent.com/32280201/41506619-c2eb4158-7210-11e8-96e5-07d5e2b47810.png)
But when I try to run `fish -c omf theme theme-name` from the script, I get the following error (I also tried to use a function [see the attached screenshot]) 
![deepin capture-ecran_hyper_20180617010439](https://user-images.githubusercontent.com/32280201/41506620-ce2e6c70-7210-11e8-8459-0d77dd0f14d9.png)
Edit: Sorry I figured my mistake. I used a variable named `PATH` in my script which overwirtie the global `$PATH` variable

**Comment by bobthecow** [comment]
Ha! Yep, that would do it :)
