### ISSUE TITLE
Help with 3 OMF matters

### ISSUE THREAD

**Issue by GittyMejorado** [oh-my-fish/oh-my-fish#621]
Good day, I have the first contacts with OMF shell and I have made mistakes and I have doubts.

1. When I initially installed OMF, a green color box appears at the beginning of the prompt in the default theme, as well as in the other themes that I installed later, with the exception of Budspencer. That little box that appears to me at the beginning of the prompt, I have not seen it anywhere else. How can I solve that?

Last two issues solved, the first not yet.
Why appears the green box at the beginning of the prompt with the uppercase i in square brackets

[https://imgur.com/kRA1PGT](url)

------------------------------------------------------------------------------------------------------------------------------------
2. While using the Budspencer theme I made the mistake of choosing a theme in fish_config, and now only this message appears without allowing me to execute any command:

~ ❯❯❯ omf update omf~/.local/share/omf/themes/budspencer/fish_right_prompt.fish (line 19): switch: Expected exactly one argument, got 0

    switch $pwd_style
           ^
in function '__budspencer_prompt_pwd'
        called on line 260 of file ~/.local/share/omf/themes/budspencer/fish_right_prompt.fish

in command substitution
        called on line 258 of file ~/.local/share/omf/themes/budspencer/fish_right_prompt.fish

in function 'fish_right_prompt'
        called on standard input

in command substitution
        called on standard input

How can I solve that?. I try uninstalling and reinstalling but I can not do that. I think it's a matter of configuring some file but I do not know which file, or in what part of that file

3. How can I put a permanent function in OMF ?, that, I do not have to be putting it every time I open a terminal. for example the fish logo function.

Thanks for your attention

**Comment by sagebind** [comment]
Hi @GittyMejorado, I hope we can solve your issues getting started.

For the first issue, this is a very common confusion point with Fish Shell for new users. The box with `I` in it indicates you are using VI keybindings. See #433 for how to disable that. It doesn't help that the Budspencer readme tells everyone to enable VI keybindings without explaining...

**Comment by oranja** [comment]
For (2) you can try to get rid of the theme from `fish_config` with a simple:
```fish
mv ~/.config/fish/functions/fish_prompt.fish{,.ignore}
```

For (3) see [`funcsave`](https://fishshell.com/docs/current/commands.html#funcsave) or just create your own *.fish* files in *~/.config/fish/functions/*. It's a good practice to name the file as the name of the function it defines. If it has helper functions not shared with other functions, you can pack them in the same file.

**Comment by GittyMejorado** [comment]
@sagebind thank you very much for the answer, I have managed to disable the unicode symbol of VI insertion at the prompt, I see it has to do with fish and the relationship with VI in the insertion of bindings.

@oranja thank you very much too, I solved it in a less orthodox way, moved the folder .local/share/omf to another place and reinstalled omf. To my surprise, the reinstallation installed automatically
everything I had installed before along with the themes and pluggins, I did that because I could not write any command at all and it worked very well, although I really thought I could break things but it did not happen :P lol

To put the logo, I read that I could download omf install fish_logo and it was installed, then I created the file fish_greetings.fish and put
function fish_greeting
    fish_logo
end 
And now every time I open fish I see a nice golden carp greeting me... :v Excelente

Thank you very much to both of you again and I wish you an excellent day
