### ISSUE TITLE
"default" theme cursor has weird horizontal positioning

### ISSUE THREAD

**Issue by jokeyrhyme** [oh-my-fish/oh-my-fish#625]
Hi, firstly, I love this project! This is making my first-time user experience for `fish` so friendly :)

I have noticed that the default theme has a weird cursor positioning issue:
![image](https://user-images.githubusercontent.com/479816/42424490-c423c678-82c1-11e8-8997-c7d924c1e816.png)
In the above screenshot, I've typed "abc" without any spaces or anything, and the cursor is positioned partially over the "c", whereas I would normally expect it to occupy the space to the right of the "c" instead

I've double-checked this in `bash` and with the "pure" theme (`omf theme pure`), and those have the expected cursor positioning, so I think this is specific to the "default" theme so far

- Operating System: Google Chrome OS Version 69.0.3473.0 (Official Build) dev (64-bit)
  - Linux / Crostini container: Debian GNU/Linux 9 (stretch)
- `fish --version`: fish, version 2.4.0
- `omf --version`: Oh My Fish version 6
- `git --version`: git version 2.11.0

**Comment by jokeyrhyme** [comment]
Oddly enough, I can't reproduce this in the Terminal.app on macOS
So perhaps this is specific to Chrome OS?

**Comment by sagebind** [comment]
This is almost certainly a problem with your specific terminal emulator not handling "wide" characters very gracefully (which the little fish at the left is). Other themes that aren't using wide characters in their prompt will probably not have this problem.

Closing as there's not much OMF can do here.
