### ISSUE TITLE
Default prompt corrupted

### ISSUE THREAD

**Issue by AntoineArt** [oh-my-fish/oh-my-fish#626]
Hello, I just tried omf and a few themes and now, even after uninstalling omf, I am stuck with a weird beginning of line : 

![image](https://user-images.githubusercontent.com/26147209/42561610-d70e5782-84f9-11e8-9b60-567f788e9c0c.png)

I can't find a way to remove this weird [I] from the prompt, even in config files.
Thanks in advance for your help.

To be precise I didn't have this weird thing before trying themes and it appeared when I tried a theme, I can't remember which sorry, from this moment this thing didn't quit the prompt, even with other themes or default theme. I even tried uninstalling fish and reinstalling, no effect.

**Comment by bpinto** [comment]
It seems like you have vi mode enabled. One of the themes must have enabled it: https://fishshell.com/docs/current/commands.html#fish_vi_mode

**Comment by AntoineArt** [comment]
Problem solved, thanks a lot !
