### ISSUE TITLE
unable to install omf

### ISSUE THREAD

**Issue by mals14** [oh-my-fish/oh-my-fish#631]
I tried to reinstall omf because there was set color error that came up every time a new shell was launched. I could not decipher that error nor found it online, therefore decided to uninstall omf and reinstall.

Used the commands:
``` 
curl -L https://get.oh-my.fish > install
fish install --path=~/.local/share/omf --config=~/.config/omf
```
---
```
Uninstall complete
Installing Oh My Fish to /Users/user/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Writing bootstrap to /Users/user/.config/fish/conf.d/omf.fish...
Existent fish_prompt.fish found at /Users/user/.config/fish/functions
↳ Moving to /Users/user/.config/fish/functions/fish_prompt.1536152716.copy
Setting up Oh My Fish configuration...
mkdir: /Users/user/.config/omf: No such file or directory
An error occurred while redirecting file '/Users/user/.config/omf/bundle'
open: No such file or directory
An error occurred while redirecting file '/Users/user/.config/omf/channel'
open: No such file or directory
An error occurred while redirecting file '/Users/user/.config/omf/theme'
open: No such file or directory
Updating https://github.com/oh-my-fish/packages-main master... fatal: could not create leading directories of '/Users/user/.cache/omf/https___github.com_oh-my-fish_packages-main_master': No such file or directory
Error
Install aborted: Error installing plugins

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues
```

Directory /Users/user/.config shows up as the following when seen via ls -al. So it appears to be writable by omf installer.

```
drwxr-xr-x   8 user  staff   256 Sep  5 09:00 .
```

Installed fish using 

``` brew install fish```

Any ideas? I am prepared to uninstall fish and reinstall. 

Thank you.

**Comment by mals14** [comment]
I think I have boiled the problem down to this -- the installer is unable to create omf directory in ```/Users/user/.config```

Even when I go to the directory /Users/smalani/.config, and try to do mkdir I get the error message as follows
```mkdir: .: No such file or directory```

I get this error even after I have run rm -rf omf from within this directory. 

So I did this.
I changed directory to /Users/smalani/.config.
Ran sudo rm -rf omf. 
Then ran mkdir omf and I get the error "mkdir: .: No such file or directory".

Sounds like there is a bad file system node or something and mkdir is not creating the directory, and rm is not removing it. I am using a Mac with the OS version 10.13.6.

I hope somebody can help. Thanks!

**Comment by mals14** [comment]
So I solved the problem as follows:

I made copies of the .config directory.
Changed the name of the directory to config_to_delete.
Then opened the folder in Finder and deleted this directory. (because even sudo rm -rf <dir> could not delete this directory. Finder was able to delete.)

Then I renamed the copied directory to .config.

I don't know the technical reasoning behind why it worked but clearly omf had left some file / directory fragment which was not behaving well.

**Comment by sagebind** [comment]
Interesting, this issues sounds very familiar, in particular the fact that OMF is looking for `/Users/user`. We never did figure out why macOS would report that as `$HOME`; if that is indeed what is happening, then macOS is broken, not OMF.
