### ISSUE TITLE
How do I use the template created with 'omf new theme'?

### ISSUE THREAD

**Issue by Memphizzz** [oh-my-fish/oh-my-fish#633]
Hi,

first of all, thanks for all the hard work on OMF, its amazing!

I created a template using 'omf new theme', adjusted the files and now struggle to figure out how to activate that template as my theme. Unfortunately the Readme doesn't give an example on what to do after the template has been created/adjusted.

Is there a command like 'omf install templates/mytemplate'?

Thanks in advance!

**Comment by derekstavis** [comment]
Using `omf theme <your-theme-name>` should be sufficient.
