### ISSUE TITLE
Weird character

### ISSUE THREAD

**Issue by evenpengqnap** [oh-my-fish/oh-my-fish#635]
I got a weird character at the beginning of each new line.
Cloud anyone help to remove it?
Thanks!

I use Fira Code Retina, so it is not caused by fonts.

<img width="496" alt="screen shot 2018-09-19 at 4 54 59 pm" src="https://user-images.githubusercontent.com/40447025/45742678-1d8b0380-bc2d-11e8-94c1-4443de6bcda3.png">

**Comment by nwykes** [comment]
That shows when you have vi mode enabled

https://fishshell.com/docs/current/commands.html#fish_vi_mode

Some themes allow you customize it.

**Comment by evenpengqnap** [comment]
Thanks @nwykes  !!
After disabling vi mode using instructions in #433, it disappeared.
