### ISSUE TITLE
Different theme in different shells

### ISSUE THREAD

**Issue by asfaltboy** [oh-my-fish/oh-my-fish#638]
(I apologise if this is the wrong place to ask, please direct me if you believe I should ask elsewhere)

I sometimes run fish from two applications (one IDE, the other iTerm2). The IDE doesn't show colours really well, so I'd like to run an alternative theme for each of them. I can run `fish -C omf theme default` and then this fish shell will use my default theme. However, the issue I have is that any other shells I open start to use the last set theme.

I guess I can open them both with `fish -C omf theme <theme>` but I'm wondering if that's the best way. Is there some sort of theme settings I can set in some sort of profile?

**Comment by sagebind** [comment]
I think it has been proposed before to support using a theme temporarily by an environment variable. See #547.

**Comment by sagebind** [comment]
Closing as a duplicate.
