### ISSUE TITLE
Error "pointer being freed was not allocated" when trying to install on MacOs 10.13.4

### ISSUE THREAD

**Issue by leolara** [oh-my-fish/oh-my-fish#639]
Error message:

```
fish(31471,0x7fff930da380) malloc: *** error for object 0x1002de120: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
fish: Process 31471, 'fish' from job 1, 'curl -L https://get.oh-my.fish | fish' terminated by signal SIGABRT (Abort)
```
<img width="836" alt="screen shot 2018-09-22 at 09 09 12" src="https://user-images.githubusercontent.com/1210482/45914605-6fa77100-be47-11e8-80ae-09f55d276be1.png">

I installed fish using Homebrew.

```
fish, version 2.1.2
```

**Comment by sagebind** [comment]
That looks like a bug in Fish itself, not Oh My Fish.

Incidentally, Oh My Fish supports only Fish 2.2.0 or newer.
