### ISSUE TITLE
Problems enabling OMF in a git-managed config

### ISSUE THREAD

**Issue by NobbZ** [oh-my-fish/oh-my-fish#641]
Hi there!

I have most of my dotfiles synchronised via git through my workstations and I want to try out fish and OMF now.

Now I installed OMF on Box A, added ``~/.local/share/omf`` as a submodule (url=https://github.com/oh-my-fish/oh-my-fish.git), and also put `~/.config/fish/conf.d/omf.fish` under version control.

After checking those out on Box B and starting fish, I still get the old prompt and no OMF stuff seems to be enabled.

Have I missed adding some files to Version Control to make fish able to pick OMF up?

**Comment by NobbZ** [comment]
It seems as if oh-my-fish actually was loaded, but for some reason the theme isn't picked up, I had to `omf install default` to make it work.

What do I need to add to my VCS to synchronise those?

**Comment by sagebind** [comment]
Marking this question as closed. Feel free to reopen if you still have problems with this, or open a new issue. Thanks!
