### ISSUE TITLE
Check uses of "?" for fish 3 compatibility

### ISSUE THREAD

**Issue by faho** [oh-my-fish/oh-my-fish#644]
Howdy,

it appears OMF uses the "?" glob in a few places. Fish 3 deprecates that one and allows users to disable it via a "feature flag" (like the `^` stderr redirection).

Going through the ones I've found via `git grep '\?' | grep -v .md:`:

These should presumably just use `*` instead:

```fish
init.fish:  set -l key_bindings $OMF_CONFIG/key_binding?.fish \
init.fish:                      {$OMF_CONFIG,$OMF_PATH}/themes/$theme/key_binding?.fish
pkg/omf/functions/themes/omf.theme.set.fish:    and test (count {$OMF_CONFIG,$OMF_PATH}/key_binding?.fish) -gt 0
```

These read the part after the "=" into a variable immediately afterwards, and the variable defaults to empty, so the `?` can presumably simply be dropped:

```fish
pkg/omf/functions/index/omf.index.query.fish:      case '--name=?*'
pkg/omf/functions/index/omf.index.query.fish:      case '--text=?*'
```

I'd probably just drop the `-?` and `/?` way of saying "--help":

```fish
bin/install:      case --help -h '/?'
pkg/omf/functions/omf.fish:      case '-h' '--help' '-\?' '/\?'
```

If you must offer it, matching a literal `?` here is a bit more involved than I'd like it, but since it doesn't happen often.... This is the code we use:

```fish
    # A literal "?" for use in `case`.
    set -l q '\\?'
    if status test-feature qmark-noglob
        set q '?'
    end

    # ...
    case "$q"
```

This is just an error for an unknown option, so it's probably also okay to trigger on just a "-":

```
pkg/omf/functions/omf.fish:      case '-?*'
```

(Alternatively, catch `case -` before, and then use `case '-*'`)

**Comment by sagebind** [comment]
Is there an alternative for the `?*` construct in a switch statement? This pattern is "match one or more characters", whereas just `*` is "zero or more characters.

**Comment by faho** [comment]
Like I said:

>catch case - before, and then use case '-*'

The idea is that `*` is equivalent to ? plus a none-case, where there's no character there.

The none-case would then have to have the same code as the catch-all `case '*'`.

**Comment by faho** [comment]
Okay, so let me expand a bit more since I'm not on a phone anymore:

> This pattern is "match one or more characters", whereas just * is "zero or more characters".

Which means that the latter is "zero characters" + the old one. So if ensure that zero characters never reach the new pattern by matching them in another case, it can only match what the old one did.

E.g. 

```fish
switch $token
    case '-?*'
       echo matches
    case '*'
       echo default
end
```

Here, `-?*` will match anything that starts with a "-" and then has at least one character.

So, we need to get the `?` out of here. If we replace `-?*` with `-*`, that would match one additional thing: `-`, which is exactly when `*` expands to nothing, which `?*` can't.

So we just match `-` explicitly before trying `-*`, and handle it just like the case that would have caught it after `-?*`:

```fish
switch $token
    case `-`
        echo default # because case '*' would have caught this
    case '-*'
       echo matches
    case '*'
       echo default
end
```

This also works if there are more than one `?*` in there, only it grows exponentially. With two, like in `?*/?*`, there are four cases:

- `/` - both `*` expand to nothing
- `*/` - the right `*` expands to nothing
- `/*` - the left does
- `*/*` - both expand to something

(Obviously you don't _have_ to handle them separately - `case / '*/' '/*'` and `case '*/*'` are often what you want)

(with three `?*`, there'd be 8 cases, four -> sixteen and so on)

---------------------

Alternatively, if you don't want to do this kind of glob arithmetic, you can use e.g. `string match -r` with things like `.+` to confirm that there is a character somewhere, either separately or _inside_ the `case`.

**Comment by scorphus** [comment]
Howdy! 👋

Status: I'm running a bunch of tests against various versions of Fish.

**Comment by scorphus** [comment]
Done with the tests, finally.
