### ISSUE TITLE
Plugin Hulk is no longer exist

### ISSUE THREAD

**Issue by SanCoder-Q** [oh-my-fish/oh-my-fish#645]
For some reason, the plugin `hulk` has been removed from Github. So the following reference is no longer valid.
https://github.com/oh-my-fish/packages-main/blob/master/packages/hulk#L2

Doing an `omf update` will hang and lead a failure.

**Comment by bobthecow** [comment]
Fisherman has been rewritten (is now Fisher) and the two themes listed from there no longer exist. 

Fixed https://github.com/oh-my-fish/packages-main/pull/68
