### ISSUE TITLE
[Question] Support for plugins that autoload with `conf.d`?

### ISSUE THREAD

**Issue by jethrokuan** [oh-my-fish/oh-my-fish#646]
Does omf support plugins with scripts in the `conf.d` directory? For context, a plugin I maintain has to move a script from `conf.d` to the root `init.fish` to support omf. https://github.com/jethrokuan/fzf/pull/76

I'm not familiar enough with omf to comment on whether this was necessary, but I'd very much like to keep scripts that are autorun in `conf.d` which is the canonical way of doing it in fish now.

**Comment by derekstavis** [comment]
This should be now fixed by #653. To test it please switch to the dev channel (see omf help for how to switch channels).
