### ISSUE TITLE
Default theme normal/success colors are highlighted

### ISSUE THREAD

**Issue by KevinParnell** [oh-my-fish/oh-my-fish#647]
Operating System: macOS Mojave 10.14.1
Fish Version: fish, version 2.7.1
Oh My Fish Version: Oh My Fish version 6-17-g17c1726
Git version: git version 2.19.1

In the default theme on iTerm2, the normal color and success color is highlighted instead of just being the text colored. Incorrect does not have this issue. Screenshot - https://i.imgtc.com/N1fb2SB.png

**Comment by KevinParnell** [comment]
Never mind, I fixed it. https://i.imgtc.com/EzH5ock.png

**Comment by zhangyuteng** [comment]
@KevinParnell I have same probelm. Could you tell me how you fix it?
