### ISSUE TITLE
Not working with powerline on FreeBSD

### ISSUE THREAD

**Issue by dubbadubbadubbacha** [oh-my-fish/oh-my-fish#661]
I get this error when I install oh my fish with powerline installed in FreeBSD.

<code>
Checking for a sane environment...
Installing Oh My Fish to /home/jamie/.local/share/omf...
Writing bootstrap to /home/jamie/.config/fish/conf.d/omf.fish...
Setting up Oh My Fish configuration...
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package powerline
✔ powerline successfully installed.
Installing package agnoster
✔ agnoster successfully installed.
Installing package default
✔ default successfully installed.
Installation successful!
/home/jamie/.local/share/omf/pkg/powerline/init.fish (line 1): 
pip show powerline-status 2>/dev/null | grep Location | awk '{ print $2 }'
^
in command substitution
	called on line 0 of file /home/jamie/.local/share/omf/pkg/powerline/init.fish

in function “init”
	called during startup
	with parameter list “/home/jamie/.local/share/omf/pkg/powerline”

in event handler: handler for generic event “init_powerline”

Please install powerline
</code>

**Comment by nbrown9** [comment]
Same issue on MacOS 10.14.2

**Comment by bobthecow** [comment]
I'm not very familiar with powerline, but it looks like you need to `pip install powerline-status` to use this plugin.

To get better support, you could open an issue on the [powerline plugin's repo](https://github.com/iamruinous/plugin-powerline) :)

**Comment by nbrown9** [comment]
Looks like it was a config error on my end. After installing power line fonts and enabling them in my terminal I have no more issues.

**Comment by sagebind** [comment]
Glad it is working! Feel free to re-open this issue if you're still having trouble.
