### ISSUE TITLE
Error returned when running "omf reload"

### ISSUE THREAD

**Issue by 98thpixel** [oh-my-fish/oh-my-fish#664]
**Below is the omf reload output:**

✔︎ ~ omf reload
There are still jobs active:

   PID  Command
     0  omf.reload
     0  omf.cli.reload $argv
     0  __omf_last_command $argv
     0  omf reload

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.

**Below is my omf doctor output:**

✔︎ ~ omf doctor
Oh My Fish version:   6
OS type:              Darwin
Fish version:         fish, version 3.0.0
Git version:          git version 2.17.2 (Apple Git-113)
Git core.autocrlf:    no
Your shell is ready to swim.

**Comment by lukasmalkmus** [comment]
Yes, can confirm. This occurred after updating to fish 3.0.0.

**Comment by nonissue** [comment]
Yah, iterm2 hangs on startup macOS after updating to fish 3.0.0 with OMF 6.0. 

I wonder if the changes described in [#644](https://github.com/oh-my-fish/oh-my-fish/issues/644) would resolve the issues. If I have time, I'll implement them tomorrow and report back.

**Comment by scorphus** [comment]
Meanwhile, you can use `exec fish` instead of `omf reload`.

**Comment by scorphus** [comment]
> Yah, iterm2 hangs on startup macOS after updating to fish 3.0.0 with OMF 6.0.
> 
> I wonder if the changes described in [#644](https://github.com/oh-my-fish/oh-my-fish/issues/644) would resolve the issues. If I have time, I'll implement them tomorrow and report back.

@nonissue maybe oh-my-fish/plugin-vcs#6 helps you?

**Comment by scorphus** [comment]
Thanks to @faho, who kindly fixed the issue upstream, we just need to wait for the next Fish Shell release. Until then, `exec fish` is your friend.

**Comment by scorphus** [comment]
Let's keep an eye on fish-shell/fish-shell#5520.

**Comment by scorphus** [comment]
Tested against 1-day-old [Fish 3.0.1](https://github.com/fish-shell/fish-shell/releases/tag/3.0.1) It works! YAY!!
