### ISSUE TITLE
Some of the git.io URLs I've seen in the UI don't appear to resolve to this repository

### ISSUE THREAD

**Issue by nelsonjchen** [oh-my-fish/oh-my-fish#67]
Instead they resolve to a repository under the `fish-shell` organization.

Take this URL which is found in `omf --help`:

https://git.io/oh-my-fish

Or the message mentioned in issue #60. 

https://git.io/omf-issues

Was this working before the DMCA request?

**Comment by bpinto** [comment]
Nope, we forgot to update those links, could you open a PR fixing them? It would be very welcome!

**Comment by nelsonjchen** [comment]
I'm curious if @github would be willing to modify the short URLs and fix it *that* way.

**Comment by nelsonjchen** [comment]
Let me see if I can gather a list of them.

**Comment by nelsonjchen** [comment]
Oh it looks like the message in #60 was just updated to not use `git.io` but the full link.

**Comment by nelsonjchen** [comment]
That leaves:

* https://git.io/omf :arrow_right: https://github.com/fish-shell/oh-my-fish/raw/master/bin/install
  * in Travis (WTF! Why isn't CI failing left and right?!)
* https://git.io/oh-my-fish :arrow_right: https://github.com/fish-shell/oh-my-fish
  * `-h`

**Comment by nelsonjchen** [comment]
I think the former should be fixed up by one of the many PRs that will be applied to `.travis.yml`. That leaves the latter. I'll contact GitHub and see if they would be willing to change that short URL.

**Comment by nelsonjchen** [comment]
Or the alternative, setup fish-shell/oh-my-fish to redirect here.

**Comment by derekstavis** [comment]
Perhaps @bucaran could help us with the redirect?

**Comment by nelsonjchen** [comment]
If the repository is transferred, it would have already setup a redirect. I don't think you can make redirects other than with transferring.

**Comment by nelsonjchen** [comment]
GitHub support was able to delete the original URL. I was able to reregister a new vanity URL. Unfortunately, I had to append a `#` to the end of the URL as someone had already put the https://github.com/oh-my-fish/oh-my-fish URL to another git.io URL.

**Comment by derekstavis** [comment]
Awesome!! Thanks man!!

**Comment by bucaran** [comment]
@nelsonjchen Thanks. There is no way to remove git.io URLS, other than contacting GitHub.

`git.io/oh-my-fish` points to `https://github.com/oh-my-fish/oh-my-fish#`

**Comment by bpinto** [comment]
Great work on contacting github!

**Comment by bobthecow** [comment]
looks like /omf still points to fish-shell?

**Comment by nelsonjchen** [comment]
It does but it looks like the only use of that in the codebase is in Travis. It's not in a user facing GUI.

**Comment by bucaran** [comment]
Nope, `git.io/omf` should point to the raw of `https://github.com/oh-my-fish/oh-my-fish/blob/master/bin/install`, which lets you `curl -L git.io/omf`.

**Comment by nelsonjchen** [comment]
I'll just reopen this issue then. It does seem pretty convenient but it should probably be documented in the readme once that URL is fixed.

**Comment by nelsonjchen** [comment]
Another formed fill and sent to GitHub support.

**Comment by bucaran** [comment]
It was there originally, as you can see it's also [here](https://github.com/wa/wahoo/#install). I am not really sure why it was removed!

**Comment by nelsonjchen** [comment]
Github Support deleted the original short URL at `omf`.

https://git.io/omf now points to the URL @bucaran says it should be. :+1: :)

**Comment by bucaran** [comment]
:+1:
