### ISSUE TITLE
CD waits "something"

### ISSUE THREAD

**Issue by Augustolopez** [oh-my-fish/oh-my-fish#679]
Hi everyone!
After update to **fish 3.0.0** when i used _cd_  the shell is left waiting and the only way to continue is with _ctrl + c_.
Someone has a solution to this?

**Comment by bobthecow** [comment]
It’s probably this one: https://github.com/fish-shell/fish-shell/issues/5541

Which will be available in 3.0.1?

**Comment by radovandelic** [comment]
@Augustolopez 
Runnning `source $OMF_PATH/lib/autoload.fish; source $OMF_PATH/lib/require.fish` and restarting the terminal worked for me.
If that doesn't work, you can try adding a before.init.fish file to the $OMF_PATH directory containing the same source command:
```
source $OMF_PATH/lib/autoload.fish
source $OMF_PATH/lib/require.fish
```

**Comment by radovandelic** [comment]
It's also possible that one of your plugins or themes is incompatible with fish3, so if it still doesn't work you can try commenting out the lines `set -l core_function_path $OMF_PATH/lib{,/git}` and
`set -l theme_function_path {$OMF_CONFIG,$OMF_PATH}/themes*/$theme{,/functions}`, and then `omf reload`. If it works now, then you need to find the incompatible plugin/theme(s) in the $OMF_PATH/pkg and $OMF_PATH/themes folders and remove them.
