### ISSUE TITLE
Installing custom themes from repository

### ISSUE THREAD

**Issue by mmartinortiz** [oh-my-fish/oh-my-fish#684]
Hi,

Is it possible to install custom themes (I forked the chain theme) from a repository using `omf`?

I tried with `omf repo add <url>` and the URL of my repo. If I try to install the `chain` theme, it gets the "official", as expected, but the search does not show my alternative.

If I try with `omf install <url>`, I get a `successfully installed` but the package is not installed under themes.

**Comment by kfkonrad** [comment]
On my machine your theme was installed as if it were a package. I'm no entirely sure, but I think if you install a package via URL, OMF assumes it's a package, not a theme. You can mv the theme by moving it to the theme folder like this:
```
omf cd
mv pkg/my-chain themes/
```
And with this, OMF will now treat my-chain like the theme it is. Activate the theme as you normally would with `omf theme my-chain`.

You could also add your own repository of custom themes/packages for personal use. This way you can update your themes/packages with `omf update`. It's a rather simple process and the format for the files and directories can be taken from the main package repository for OMF: https://github.com/oh-my-fish/packages-main.

Let me know if that fixes your problem.

**Comment by sagebind** [comment]
Currently `omf install` tries to guess whether the repository is a theme or a plugin based on whether a `fish_prompt.fish` file exists in the root directory of the repository.

The distinction between theme packages and plugin packages has kinda bitten us, and in retrospect a distinction should not have been made so deep in the framework. Ideally packages would be installed in the same directory and any package with a `fish_prompt.fish` file could be chosen as the current theme.

**Comment by f1337** [comment]
Here's a work-around that is working for me. YMMV:

```
omf cd
cd themes
git clone https://github.com/f1337/theme-bobthefish.git ./bobthefish
omf theme bobthefish
```

**Comment by mmartinortiz** [comment]
Thanks for you answers. So far, I got comfortable using the "bob the fish" theme and my own fork does not add anything of value to my current "likes/needs".

We can consider this issue closed since you already gave some nice answers on how to deal with custom themes.

Thanks guys!
