### ISSUE TITLE
Installer script checksum is out of sync

### ISSUE THREAD

**Issue by tiborsimon** [oh-my-fish/oh-my-fish#687]
You forgot to update the installer checksum in the latest install script update.

The new hash should be

```
bbace7ef16956d87fd40bff91cd1992a90621e7931ac3055f16b7f6d679e8fff  install
```
as @foxcpp mentioned too under the [commit](https://github.com/oh-my-fish/oh-my-fish/commit/a4b2f1cfaac12a614c491e3b8c7ea7e0b8842eee).

**Comment by sagebind** [comment]
Oops! Thanks for making an issue, we'll take care of it as soon as we can.

**Comment by tkossak** [comment]
It still doesn't match.

**Comment by ltxitai** [comment]
High priority since February... Any idea when this will be addressed?

**Comment by tkossak** [comment]
It means this projects needs a new maintainer :)

**Comment by derekstavis** [comment]
We definitely need more contributors to the project. Unfortunately the core team isn't currently having much time to actively address issues, but we are glad do review and merge pull requests. This is a great start to become a maintainer and we welcome anybody willing to help the project!

**Comment by kfkonrad** [comment]
I am willing to help. Not just with this but in general. I've been a fish user (and contributor) and maintainer of a few of my own omf plugins and themes for quite some time, so why not also help maintain omf^^

I'll hand in a PR to solve this issue later today. How do you feel about using a PR template to remind people to update the checksum?
