### ISSUE TITLE
batman & pure theme preview images are broken

### ISSUE THREAD

**Issue by elenigen** [oh-my-fish/oh-my-fish#688]
The link to the image is broken

https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md

**Comment by dharif23** [comment]
I have encountered the same problem. After installing Batman and then switching between `batman` and other themes is not possible. It breaks every other theme's link also. Basically, you get stuck to one theme. So, now I just reinstalled `fish` and I avoid `batman` theme.

**Comment by kfkonrad** [comment]
After all I've learned and seen about the batman theme I consider it broken. Sure, the image in the Themes.md is missing, but maybe we shouldn't advertise a wildy broken theme anyway.

Also after I install `pure` on any of my systems, I get a wild array of errors but no prompt. I don't know if anyone else is experiencing similar problems with `pure`, but afaik `pure` is broken, too. At least uninstalling pure is easier...

I'd suggest removing `batman` and `pure` from Themes.md for now, we can always add a new entry for `batman` and `pure` when/if they become usable again.

**Comment by scorphus** [comment]
Fixed by ac1c980a76116bcaccb75b010b02f3b44c6bb8be
