### ISSUE TITLE
Can't test OMF install

### ISSUE THREAD

**Issue by edouard-lopez** [oh-my-fish/oh-my-fish#695]
**related:** #693

---

I'm testing `pure` using [`fishtape`](https://github.com/fisherman/fishtape) installation with `fisher`, `omf` and manually. 

### Fisher
With fisher I only install and do my test:

    fisher add rafaelrinaldi/pure >/dev/null

    fish -c 'fish_prompt | grep -c "❯"' 

### OMF

With `OMF`, I need to do lot of plumbing before being able to run my test:
* in a first subprocess
  * install `pure`
  * then link various files
* then on a second process check `fish_prompt` output

```
curl -L https://get.oh-my.fish > install
and fish install --noninteractive >/dev/null

set --global OMF_PURE_PATH $HOME/.local/share/omf/themes/pure
fish -c "omf install pure; \
        ln -sf $OMF_PURE_PATH/fish_*.fish $HOME/.config/fish/functions/; \
        ln -sf $OMF_PURE_PATH/functions/*.fish $HOME/.config/fish/functions/; \
        ln -sf $OMF_PURE_PATH/conf.d/* $HOME/.config/fish/conf.d/" > /dev/null
fish -c "fish_prompt" | grep -c '❯'
```

### Question

* Why do I need to symlink manually?
* How can I use only a single subprocess?

**Comment by kfkonrad** [comment]
It seems this issue's been fixed with PR 163, can we close this?
