### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by bpinto** [oh-my-fish/oh-my-fish#7]
OMF supported `Theme 'default'` and `Plugin 'rbenv'` commands on `config.fish` file. This was much easier to use than the current way (split in two different files).

As restoring the old functionality entirely will break compatibility again, we should add support for the behaviour described above as a wrapper around the current solution.

In a future issue, we could discuss removing the current solution for good.

**Comment by zacheryph** [comment]
Yeah, this goes along with everything constantly breaking.  Now its the git repo doesn't even exist and i'm updating the .git/config file manually. lets see if this works.  debating going back to oh-my-zsh; at least its update command worked more than once.

**Comment by bobthecow** [comment]
Sorry about that. The git repo disappearing was a bit beyond our control :(

**Comment by derekstavis** [comment]
I'm sorry about that @zacheryph. Our original repo got messed up (wahoo merged + 2 force pushes) and then hijacked by a contributor with owner privileges. As @bobthecow mentioned, it was beyond our control.

Anyway, the best way to do a upgrade is:

1. `mv ~/.config/fish/config{,_old}.fish`
2. `rm -rf ~/.config/fish/config.fish`
3. `rm -rf  ~/.oh-my-fish`
4. Do a clean Oh My Fish install
5. Copy all `Plugin "name"` and `Theme "name"` from `~/.config/fish/config_old.fish`
6. Paste it into `$OMF_CONFIG/bundle` file. If it doesnt exist, create it
7. Convert all `Plugin "name"` lines to `plugin name`
8. Convert all `Theme "name"` lines to `theme name`
9. `omf install`
10. Disco!

We are very busy migrating plugins to the new structure, fixing bugs in the core framework, documenting things, so a solution for backwards compatibility may not land very soon. Altough, feel free to contribute with improvements on both framework and plugins/themes. You are welcome!

**Comment by zacheryph** [comment]
Thank you both of you.  My apologize for sounding hostile, not my intention.  I can get a bit carried away sometimes.  I was unaware of all the "fun" you guys have been having lately.  I have gotten everything all working again, after a little bit of a bumpy ride.  Though I will admit I am thankful for all the updates that have been coming through.  It is a lot more friendly than it was when I first started using it.

Thank you for all your hard work on this.

**Comment by WandersonCF** [comment]
I would like to know if there are any workaround for installing some of the plugins that are not still available in the new standard. I need to use my vi-mode again, so handy!. Thanks for all your good work guys.

**Comment by bobthecow** [comment]
You can install directly via URL, but it's likely the plugin won't work out if the box. You could help update it, though :)

**Comment by derekstavis** [comment]
A generalist approach is to rename `*.init` to `*.fish` and split every function in a file with its name. We encourage people to fork the plugin in interest and contribute the fixes in the main repository. Some examples of plugin ports are:

- https://github.com/oh-my-fish/plugin-jump/pull/3/files

**Comment by WandersonCF** [comment]
I can try to help of course! :D 

@derekstavis When you say to split every function in a file with its name, I need to open the file *.load (in my case https://github.com/oh-my-fish/plugin-vi-mode) and create a file like on this example:

https://github.com/oh-my-fish/plugin-functional

There is a file *.py which is used once inside the *.load file. Still need to understand better all this coding.

**Comment by bpinto** [comment]
Mind you open a PR with the updates?

**Comment by WandersonCF** [comment]
@bpinto Done! Please help me out if I did something wrong, it's my first time using github and updating a project.

**Comment by rominf** [comment]
@bpinto 
Can you make a stable branch? I broke oh-my-fish installation again. I like the idea of separate commands `omf install ...`, etc., but it's better to warn users that it's not ready yet.

**Comment by rominf** [comment]
Also, please! don't touch my `config.fish`. I love it, it contains my stuff too.
I would better `sed` `Plugin` lines and append `source` line to appropriate place.

**Comment by bpinto** [comment]
I will be back from vacations next Tuesday, I might have a chance to review it before then. :(

**Comment by bpinto** [comment]
@rominf we want to use semver what do you think?

**Comment by derekstavis** [comment]
@rominf there's also #50 which removes `Plugin` and `Theme` from `config.fish`. We can also work on adding a single line into `config.fish` to load Oh My Fish.

**Comment by rominf** [comment]
> we want to use semver what do you think?

I think it would be nice. Actually I would use git branch names for that. `update` call checkout uptates omf and plugins to latests branches. No need to write versions somewhere else.

**Comment by bpinto** [comment]
Home brew requires versioning, I think being able to install omf using brew is quite convenient.

**Comment by bpinto** [comment]
So much time has passed, I think we don't need this anymore.

**Comment by bobthecow** [comment]
:+1:
