### ISSUE TITLE
Powerline glyphs not working despite having powerline font installed in iTerm2

### ISSUE THREAD

**Issue by jby** [oh-my-fish/oh-my-fish#703]
I've been using the inconsolata-powerline font for a couple of years in my iTerm2 with zsh and powerline, but when switching to fish and oh-my-fish all powerline themes gives broken glyphs:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/1584888/58253121-fa8a9380-7d67-11e9-8a0b-dcb51914ef1d.png">
The above example is from the "bobthefish" theme
What am I doing wrong?

**Comment by bobthecow** [comment]
powerline used different codepoints for their glyphs a couple of years ago. you might have an older patched version of the font which uses the old codepoints?

**Comment by jby** [comment]
Ok, I'll try and download new versions then.

**Comment by jby** [comment]
Yes! That solved the problem - thanks @bobthecow!
