### ISSUE TITLE
env: shell: No such file or directory

### ISSUE THREAD

**Issue by jby** [oh-my-fish/oh-my-fish#705]
I originally logged this at fish-shell, but have since realised it's omf that's causing it somehow.

```
omf doctor
Oh My Fish version:   6
OS type:              Darwin
Fish version:         fish, version 3.0.2
Git version:          git version 2.21.0
Git core.autocrlf:    false
Your shell is ready to swim.
env: shell: No such file or directory
```

```
fish --version
fish, version 3.0.2
```

I have 3 Macs, all running the same version of macOS (10.14.5) and all setup the same way.
On 2 I have no problem, but on my main workstation in the office I get this every time I start a new fish from the command line or if I ssh into it:

```
fish
Darwin HOSTNAME 18.6.0 x86_64
18:39  up 13 days,  4:18, 9 users, load averages: 1.56 1.59 1.49
env: shell: No such file or directory
env: shell: No such file or directory
```
I have the exact same fish and omf config on all three.

What could be causing this? How do I troubleshoot it?

And, yes, of course the test without third-part customisations does NOT show this...

**Comment by jby** [comment]
After trying out the tip in this comment: https://github.com/fish-shell/fish-shell/issues/5898#issuecomment-496612864

I found this:

```
env: shell: No such file or directory
in function 'env'
        called on line 11 of file -
        with parameter list 'shell right --last-exit-code=0 --last-pipe-status=0 --jobnum=       0 --renderer-arg=client_id=24830 --width=207 --renderer-arg=mode=default --renderer-arg=default_mode=default'

in function 'fish_right_prompt'
        called on standard input

in command substitution
        called on standard input
```

**Comment by faho** [comment]
>But that doesn't really help me. It'd seem that it gets something from '<stdin>', "file -", but I can't find what that might be.

Most likely that's because of `source` (or `eval`).

So you'd have `fish_right_prompt` (what's your theme?) calling `something | source`, and that `something` prints `env shell`.

**Comment by jby** [comment]
Theme seems to be irrelevant, I've tried 'default', 'bobthefish', 'batman' and 'agnoster' and this happens regardless of which of those I try...

'batman' gives me a whole page of error:
```
omf t batman
env: shell: No such file or directory
env: shell: No such file or directory
omf t agnoster
set --erase: Expected 1 args, got 2
~/.local/share/omf/lib/autoload.fish (line 85):
    and set -e fish_function_path[$function_indexes]
        ^
in function '__autoload_erase'
	called on line 6 of file ~/.local/share/omf/lib/autoload.fish
	with parameter list '/Users/jonasb/.config/omf/themes/batman /Users/jonasb/.local/share/omf/themes/batman /Users/jonasb/.config/omf/themes/batman/functions /Users/jonasb/.local/share/omf/themes/batman/functions'

in function 'autoload'
	called on line 25 of file ~/.local/share/omf/pkg/omf/functions/themes/omf.theme.set.fish
	with parameter list '-e /Users/jonasb/.config/omf/themes/batman /Users/jonasb/.local/share/omf/themes/batman /Users/jonasb/.config/omf/themes/batman/functions /Users/jonasb/.local/share/omf/themes/batman/functions'

in function 'omf.theme.set'
	called on line 18 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.theme.fish
	with parameter list 'agnoster'

in function 'omf.cli.theme'
	called on line 3 of file -
	with parameter list 'agnoster'

in function '__omf_last_command'
	called on line 51 of file ~/.local/share/omf/pkg/omf/functions/omf.fish

in function 'omf'
	called on standard input
	with parameter list 't agnoster'


       set - display and change shell variables.

   Synopsis
       set [SCOPE_OPTIONS]
       set [OPTIONS] VARIABLE_NAME VALUES...
       set [OPTIONS] VARIABLE_NAME[INDICES]... VALUES...
       set ( -q | --query ) [SCOPE_OPTIONS] VARIABLE_NAMES...
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME[INDICES]...
       set ( -S | --show ) [SCOPE_OPTIONS] [VARIABLE_NAME]...

set: Type 'help set' for related documentation

env: shell: No such file or directory
env: shell: No such file or directory
```

**Comment by jby** [comment]
Theme seems to be irrelevant, I've tried 'default', 'bobthefish', 'batman' and 'agnoster' and this happens regardless of which of those I try...

'batman' gives me a whole page of error:
```
omf t batman
env: shell: No such file or directory
env: shell: No such file or directory
omf t agnoster
set --erase: Expected 1 args, got 2
~/.local/share/omf/lib/autoload.fish (line 85):
    and set -e fish_function_path[$function_indexes]
        ^
in function '__autoload_erase'
	called on line 6 of file ~/.local/share/omf/lib/autoload.fish
	with parameter list '/Users/jonasb/.config/omf/themes/batman /Users/jonasb/.local/share/omf/themes/batman /Users/jonasb/.config/omf/themes/batman/functions /Users/jonasb/.local/share/omf/themes/batman/functions'

in function 'autoload'
	called on line 25 of file ~/.local/share/omf/pkg/omf/functions/themes/omf.theme.set.fish
	with parameter list '-e /Users/jonasb/.config/omf/themes/batman /Users/jonasb/.local/share/omf/themes/batman /Users/jonasb/.config/omf/themes/batman/functions /Users/jonasb/.local/share/omf/themes/batman/functions'

in function 'omf.theme.set'
	called on line 18 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.theme.fish
	with parameter list 'agnoster'

in function 'omf.cli.theme'
	called on line 3 of file -
	with parameter list 'agnoster'

in function '__omf_last_command'
	called on line 51 of file ~/.local/share/omf/pkg/omf/functions/omf.fish

in function 'omf'
	called on standard input
	with parameter list 't agnoster'


       set - display and change shell variables.

   Synopsis
       set [SCOPE_OPTIONS]
       set [OPTIONS] VARIABLE_NAME VALUES...
       set [OPTIONS] VARIABLE_NAME[INDICES]... VALUES...
       set ( -q | --query ) [SCOPE_OPTIONS] VARIABLE_NAMES...
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME[INDICES]...
       set ( -S | --show ) [SCOPE_OPTIONS] [VARIABLE_NAME]...

set: Type 'help set' for related documentation

env: shell: No such file or directory
env: shell: No such file or directory
```

**Comment by sagebind** [comment]
This error message:

```
env: shell: No such file or directory
```

Looks like some bit of code is trying to run the command `env shell` to no avail. My guess is there is a bit of code running `env $arg` and there's some weird configuring such a variable to expand to `shell`. There's some digging needed here.

**Comment by sagebind** [comment]
I can't find any usages of `env` inside OMF proper. What packages do you have installed? (`omf list`)

**Comment by jby** [comment]
None at the moment, since it quickly becomes unusable spewing out a page of errors for each command I try to run...
But -
```
Installation successful!
Welcome to fish, the friendly interactive shell
env: shell: No such file or directory
env: shell: No such file or directory
omf list
Plugins
fish-spec	fonts		omf		powerline

Themes
agnoster	batman		bobthefish	clearance	default		emoji-powerline
env: shell: No such file or directory
env: shell: No such file or directory
```

**Comment by jby** [comment]
And, still, after cleaning up:
```
env: shell: No such file or directory
env: shell: No such file or directory
omf list
Plugins
omf

Themes
default
env: shell: No such file or directory
env: shell: No such file or directory
```

**Comment by jby** [comment]
After re-starting (just the shell) and re-installing omf and bobthefish it now looks more like it:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/1584888/58881129-cdc86b80-86d9-11e9-8f9a-17d4542c9570.png">

Still - the previous behavior was not the _glorious experience_ that most converts (to fish) express...

**Comment by sagebind** [comment]
Thanks for providing the list of plugins. I bet you this is almost certainly the cause of the error message:

https://github.com/powerline/powerline/blob/4c5b02d236007b04039c32b91fa8b6efee480566/powerline/bindings/fish/powerline-setup.fish#L67

And based on what the `powerline` plugin does:

https://github.com/iamruinous/plugin-powerline/blob/master/init.fish

It looks like it overrides the definitions of `fish_prompt` and `fish_right_prompt` after it initializes. Which is why changing themes had no effect because `powerline` was forcibly overriding any theme. It is also why the error message would only go away by (1) removing `powerline`, then (2) restarting Fish, because the function overrides persist for the life of the current process.

Why does powerline throw this error? 🤷‍♂ Again, it could be a bug on their end, or in [the `powerline` package](https://github.com/iamruinous/plugin-powerline). I'm not familiar with powerline, but it looks like by the time the prompt is rendered, the `$POWERLINE_COMMAND*` variables are either empty or not set, resulting in the exact error message you experienced.

**Comment by jby** [comment]
Ok, thanks!
