### ISSUE TITLE
Fish does not remain as the default shell.

### ISSUE THREAD

**Issue by GittyMejorado** [oh-my-fish/oh-my-fish#712]
Hello
I installed fish and ohmyfish in kubuntu 18.04, I installed the root in an SSD and the home in an HDD.
What happens is that after having installed both with the theme budspencer I write the command $ chsh -s /usr/bin/fish and when restarting it is not by default the fish prompt, only the entire black terminal appears with the symbol $ and nothing more. If I write fish I see the fish shell if I write bash too, but when I open a new terminal, nothing more that the symbol $ appears.
If I write the command $ which fish I get /usr/bin/fish, as I think it should be,
omf doctor say: 
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 2.7.1
Git version:          git version 2.17.1
Git core.autocrlf:    no
your shell is ready to swim
I mean I can not put fish as my shell by default, this had not happened to me before and I do not know why it happens now and how I can fix it.
By the way when I write the command $ fish_config, Chrome browser say ERR_FILE_NOT_FOUND, but the file exist, I created it in ~/.config/fish/config.fish.
I have noticed that some applications as qBittorrent can not access the home folder installed on HDD and fish has its configuration there. And I do not really know if it's because the root on a disk different than home or because I'm using firejail sandbox
How can I solve both?
Thank you

Describe the problem you are having and how to reproduce it. Include any other additional context that can help us troubleshoot.

**Environment report**

Run the command `omf doctor` and paste the output here. Example:

```
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 2.7.1
Git version:          git version 2.17.1
Git core.autocrlf:    no
Your shell is ready to swim.
```

**Comment by develop7** [comment]
off-topic

also please refer https://fishshell.com/docs/current/tutorial.html#tut_switching_to_fish and https://github.com/fish-shell/fish-shell/ project

**Comment by kfkonrad** [comment]
fish is not in `/etc/shells` per default. Your login shell needs to be in `/etc/shells`. To add fish to that file execute:

```
echo /usr/local/bin/fish | sudo tee -a /etc/shells
```

**Comment by ColtonIdle** [comment]
@GittyMejorado have you thought of closing this issue? Fish not staying as your default shell is likely an issue on your machine and is not at the fault of omf.
