### ISSUE TITLE
Default theme does not meet the sample

### ISSUE THREAD

**Issue by phuwn** [oh-my-fish/oh-my-fish#714]
The default theme looks so cool
please help.. how can i change the default theme layout from this
![image](https://user-images.githubusercontent.com/37581250/62460341-f50be980-b7ab-11e9-86af-c676670e8b89.png)
to this....
![image](https://user-images.githubusercontent.com/37581250/62460240-abbb9a00-b7ab-11e9-9c3a-9904cbb1d60a.png)

Thank you!

```
my omf.fish

# Path to Oh My Fish install.
set -q XDG_DATA_HOME
  and set -gx OMF_PATH "$XDG_DATA_HOME/omf"
  or set -gx OMF_PATH "$HOME/.local/share/omf"

# Load Oh My Fish configuration.
source $OMF_PATH/init.fish

set -g theme_powerline_fonts yes
set -g theme_nerd_fonts yes
```

```
Oh My Fish version:   6
OS type:              Darwin
Fish version:         fish, version 3.0.2
Git version:          git version 2.22.0
Git core.autocrlf:    input
Your shell is ready to swim.
```

**Comment by ColtonIdle** [comment]
@phuwn I noticed this issue as well, but all I did was `omf theme default` and everything reset to the right values. Hope that helps

**Comment by ColtonIdle** [comment]
You might actually be running into this: https://github.com/oh-my-fish/oh-my-fish/issues/671

**Comment by phuwn** [comment]
Thank you guys but I'm no longer using fish so I'm gonna close this ticket. Thank you tho, I'll try it out.

**Comment by ColtonIdle** [comment]
@phuwn I'm trying out all different shells also. just out of curiosity. what shell did you go for?

**Comment by phuwn** [comment]
> @phuwn I'm trying out all different shells also. just out of curiosity. what shell did you go for?

I'm currently using zsh prezto and it seems to be simpler than fish. Here's my latest CLI.

![image](https://user-images.githubusercontent.com/37581250/102185748-1f170500-3ee4-11eb-8579-43b5b51e25cf.png)

**Comment by ColtonIdle** [comment]
@phuwn cool. Fish definitely seems to have issues for me but I love the auto complete. Does zsh have something like that?
