### ISSUE TITLE
Failed to read from tty

### ISSUE THREAD

**Issue by Lockna** [oh-my-fish/oh-my-fish#716]
Hey when I try to install omf, I get the error "Install aborted: Failed to read from tty" Has anyone an Idea what can be the error?

**Comment by Lockna** [comment]
Nevermind installed it via git clone^^

**Comment by arufian** [comment]
@Lockna I got the same issue, because of the installation folder already exist. Try to remove that folder, and restart your installation again

```bash
rm -rf ~/.local/share/omf
curl -L https://get.oh-my.fish | fish
```
