### ISSUE TITLE
How to know when plugins have finished loading?

### ISSUE THREAD

**Issue by luisgregson** [oh-my-fish/oh-my-fish#730]
I'm using tmuxinator to open tmux sessions with a specific layout of panes. Each pane runs a different command (eg, one could be vim, another starts a server up etc)

The issue is that tmuxinator is trying to run a command which relies on a fish plugin (nvm) but i get an intermittent error that fnm is not defined, because the plugins haven't loaded, and i'm not sure how to prevent whatever race condition is causing this

**Environment report**

I haven't provided an Environment report as the command is being run before omf has finished loading. Happy to provide debug information, but just not sure where to start?

**Comment by pantuza** [comment]
Hi, Luis. I think pasting here a report or precisely the steps you took in order to see the error would be a good start. What do you think, can you share it in this issue?

**Comment by faho** [comment]
Reporter never replied, this should be closed.
