### ISSUE TITLE
Git unable to track packages-main on fresh install

### ISSUE THREAD

**Issue by Nagefire** [oh-my-fish/oh-my-fish#731]
I was getting an error while trying to update omf so I tried a reinstall and got the following:
```
Updating https://github.com/oh-my-fish/packages-main master... There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> master

Error
```
It looks like the installer is using `git pull` instead of `git clone` to me but I haven't been able to find where the repository is stored in `~/.local/share/omf/` so I can't resolve it. I haven't been able to reproduce the error on any other computer, omf installs normally on my laptop and raspberry pi

**Environment report**
```
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 3.0.0
Git version:          git version 2.24.0
Git core.autocrlf:    no
Your shell is ready to swim.
```

**Comment by scorphus** [comment]
Check in `~/.cache/omf/` to see if `https___github.com_oh-my-fish_packages-main_master` is there. If so, you can remove (or fix) it.

**Comment by faho** [comment]
Also stale and should be closed. Sorry!
