### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by vacheli** [oh-my-fish/oh-my-fish#732]
Describe the problem you are having and how to reproduce it. Include any other additional context that can help us troubleshoot.

**Environment report**

Run the command `omf doctor` and paste the output here. Example:

```
OS type:              Linux
Fish version:         fish, version 3.0.2
Git version:          git version 2.24.0
Git core.autocrlf:    no
Your shell is ready to swim.
```
![image](https://user-images.githubusercontent.com/5040231/71049753-5bebd700-217e-11ea-963b-6fcb85e7f265.png)

I was installed vi-mod and fzf plugins with omf, but don't work at all.

**Comment by faho** [comment]
Sorry, this one has gone stale. I have no idea what should be happening here, and I assume the reporter has long moved on.

**Comment by scorphus** [comment]
Yeah, powerline strikes again.
