### ISSUE TITLE
Powerline symbols not being picked up on windows.

### ISSUE THREAD

**Issue by DanielFabian** [oh-my-fish/oh-my-fish#735]
I've just recently installed omf on my WSL2 install. And for whatever reason, I the powerline symbols don't get picked up. I've tried out various different nerd fonts as well as a vanilla powerline font and they don't seem to make any difference. Currently, I use `FiraCode NF` as my usual font.

![image](https://user-images.githubusercontent.com/1929340/74233127-09ccbb00-4cc2-11ea-8be3-eec00a988cd8.png)

Ironically, when I open vim, everything works fine. I'm at a loss. Any idea?

![image](https://user-images.githubusercontent.com/1929340/74233191-223cd580-4cc2-11ea-8081-61160ac37854.png)

**Environment report**

Run the command `omf doctor` and paste the output here. Example:

```
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 3.0.2
Git version:          git version 2.25.0
Git core.autocrlf:    no
Your shell is ready to swim.
```

**Comment by mIcHyAmRaNe** [comment]
try with cascadia fonts: https://github.com/microsoft/cascadia-code/releases
then in the terminal preview settings: `"fontFace" : "Cascadia Code PL"`

**Comment by faho** [comment]
This has been awaiting reply for six months now, I think it should be closed.
