### ISSUE TITLE
Valid value "input" for git autocrlf is not handle properly in sanity check

### ISSUE THREAD

**Issue by frederickjh** [oh-my-fish/oh-my-fish#738]
After trying to install via the url piped directly to fish failed. I download the installer script and ran: `./install --help`. Seeing that there was a "system readiness check" I then ran:

```bash
./install --check
Checking for a sane environment...
```
Seeing as that provided very little information I then tried:

```bash
./install --check --verbose
DEBUG: verbose turned on
Checking for a sane environment...
DEBUG: Command 'awk' is /usr/bin/gawk
DEBUG: Command 'basename' is /usr/bin/basename
DEBUG: Command 'cp' is /bin/cp
DEBUG: Command 'cut' is /usr/bin/cut
DEBUG: Command 'date' is /bin/date
DEBUG: Command 'dirname' is /usr/bin/dirname
DEBUG: Command 'env' is /usr/bin/env
DEBUG: Command 'fish' is /usr/bin/fish
DEBUG: Command 'fold' is /usr/bin/fold
DEBUG: Command 'head' is /usr/bin/head
DEBUG: Command 'mkdir' is /bin/mkdir
DEBUG: Command 'mv' is /bin/mv
DEBUG: Command 'readlink' is /bin/readlink
DEBUG: Command 'rm' is /bin/rm
DEBUG: Command 'sed' is /bin/sed
DEBUG: Command 'sort' is /usr/bin/sort
DEBUG: Command 'tar' is /bin/tar
DEBUG: Command 'tr' is /usr/bin/tr
DEBUG: Command 'which' is /bin/which
DEBUG: Checking for a sane 'head' implementation
DEBUG: Checking for a sane 'sort' implementation
DEBUG: Checking for a working AWK interpreter
DEBUG: Verifying Git implementation is not buggy Git for Windows
DEBUG: Verifying Git autocrlf is not enabled
fatal: bad numeric config value 'input' for 'core.autocrlf' in /home/fhenderson/.gitconfig: invalid unit
```
I then checked my setting for git core.autocrlf:
```bash
git config core.autocrlf                                                                                                     209ms  [Die Feb 25 15:46:56]
input
```

Checking the Git documentation for [Formatting and Whitespace](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace), core.autocrlf has three possible values: `true`, `false` and `input`.

Examing the code in `install` 

https://github.com/oh-my-fish/oh-my-fish/blob/b2d7a444fb5f459cf4ee3354e0b52c9a116defbf/bin/install#L483-L487

we see that it is not handling the possible value `input` properly and this is what is aborting the install.

I believe that what should be tested for here is if the value of core.autocrlf is set to **false** with something like this:
```fish
 if test (cmd git config core.autocrlf) = false
    echo "Please disable core.autocrlf in your Git configuration."
  end
```

Thanks for looking into this!
Frederick

----

**Environment report**

I am trying to install a newer version after uninstalling a very old version and the install is failing, so omf is not installed.

```
$ omf doctor                                                                                                                           [Die Feb 25 15:26:28]
omf: command not found
```

    Operating System: Ubuntu 16.04.6 LTS
    Fish Version: 3.1.0
    Oh My Fish Version: not yet reinstalled
    Git version: 2.7.4

**Comment by frederickjh** [comment]
I would be willing to work on a pull request for this and test it. Just let me know if what I propose above looks like I am headed in the correct direction with this fix.

**Comment by bobthecow** [comment]
Yep, your assessment looks correct!
