### ISSUE TITLE
Missing Highlight for Autocomplete and Directory Selection

### ISSUE THREAD

**Issue by fitrh** [oh-my-fish/oh-my-fish#747]
![Screenshot_20200313_171131](https://user-images.githubusercontent.com/55179750/77500612-8392bf80-6e90-11ea-9c00-c5644179456d.png)
After some experiment. i think the problem is with OMF
Usually when i press Tab for completion or directory selection, there are some highlight that indicate my current selection, but now it is missing
In my screenshot, i show fish using root (without omf) and regular user (with omf), my root user look fine

**Comment by fitrh** [comment]
Found the problem, I don't know why, but after change prompt color, everything is work

**Comment by fitrh** [comment]
Fix by run this command
```fish
set -U fish_color_history_current --bold
set -U fish_color_search_match ffff00 --background=brblack
set -U fish_color_selection c0c0c0 --bold --background=brblack
```

**Comment by bobthecow** [comment]
You shouldn’t _need_ to set those. There should be defaults :-/
