### ISSUE TITLE
OhMyFish portable error: omf.command: command not found

### ISSUE THREAD

**Issue by anki-code** [oh-my-fish/oh-my-fish#748]
Hello!

I'm trying to add Oh My Fish plugin to [xxh project](https://github.com/xxh/xxh). The plugin should be run in "portable" mode from special directory and using XDG environment variables is not the way. I'm facing with `omf.command: command not found` error.

What I do in short:
1. I checkout the OMF:
```
git clone https://github.com/oh-my-fish/oh-my-fish oh-my-fish
cd oh-my-fish && git checkout v6
```
2. I create standard bundle, channel, theme files in `omf-conf` directory
3. Then I have `pluginrc.fish` file:
```
set CURRENT_DIR (dirname (realpath (status current-filename)))
set -gx OMF_PATH "$CURRENT_DIR/oh-my-fish"
set -gx OMF_CONFIG "$CURRENT_DIR/omf-conf"
source $OMF_PATH/init.fish
```
4. As result I have directories and files:
```
oh-my-fish
omf-conf
pluginrc.fish
```
5. Then I got the error when try to use omf:
```
# fish -C 'source pluginrc.fish' -i
> echo $OMF_PATH
/home/ubuntu/.xxh/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/oh-my-fish
> echo $OMF_CONFIG 
/home/ubuntu/.xxh/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/omf-conf

> omf
omf.command: command not found
in command substitution
        called on line 40 of file ~/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/oh-my-fish/pkg/omf/functions/omf.fish
in function 'omf'
~/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/oh-my-fish/pkg/omf/functions/omf.fish: Unknown error while evaluating command substitution
in function 'omf'
omf.cli.: command not found
- (line 2): 
    omf.cli. $argv
    ^
in function '__omf_last_command'
        called on line 50 of file ~/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/oh-my-fish/pkg/omf/functions/omf.fish
in function 'omf'
```
6. I tried to repeat sourcing manually but had the same error:
```
> echo $OMF_PATH
/home/ubuntu/.xxh/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/oh-my-fish
> echo $OMF_CONFIG 
/home/ubuntu/.xxh/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/omf-conf
> source oh-my-fish/init.fish
> omf
omf.command: command not found
```

7. You can repeat this by using xxh:
```
# xxh +RI xxh-shell-fish +RI xxh-plugin-fish-ohmyfish
# xxh myhost +s fish
> omf
omf.command: command not found
...
```

Could you please check my steps and advice how to debug or fix it?

Thanks!

**Comment by frederickjh** [comment]
@anki-code you are running the wrong file to [install](https://github.com/oh-my-fish/oh-my-fish#installation) oh-my-fish in `pluginrc.fish`. Use `bin/install` to install from the git repository to install.

`init.fish' is used for [startup](https://github.com/oh-my-fish/oh-my-fish#startup) which will auto install packages.

If it is anything like Fisher, this does not run when installing the plugin but runs the next time the user xxhes in.

**Comment by anki-code** [comment]
@frederickjh I did install in plugin build. The question is about init and how to debug the error:
```
> omf
omf.command: command not found
in command substitution
        called on line 40 of file ~/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/oh-my-fish/pkg/omf/functions/omf.fish
in function 'omf'
~/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/oh-my-fish/pkg/omf/functions/omf.fish: Unknown error while evaluating command substitution
in function 'omf'
omf.cli.: command not found
- (line 2): 
    omf.cli. $argv
    ^
in function '__omf_last_command'
        called on line 50 of file ~/.xxh/plugins/xxh-plugin-fish-ohmyfish/build/oh-my-fish/pkg/omf/functions/omf.fish
in function 'omf'
```
When I repeat the steps to init manually this error is not appearing. But when I do similar using xxh this error is appears and I don't know how to debug it.

**Comment by anki-code** [comment]
I've found that `functions/core` was missing. Will fix.
