### ISSUE TITLE
omf reload fix

### ISSUE THREAD

**Issue by Itailevi420** [oh-my-fish/oh-my-fish#749]
command: `omf reload`
expected result: reload the shell
actual result:  fish error
```
Expected a string, but instead found a '&' (lline3) at /home/itai/.local/share/omf/pkg/omf/functions/cli/omf.cli.reload.fish
```
fix: just change to valid redirect syntax
instead of this line 3:  
```
  1 function omf.cli.reload
  2   if not contains -- --force $argv
  3     if count (jobs) >/dev/null ^&1
  4       __omf.cli.reload.job_warning
  5       return 1.......
```
change line 3 to:
```
  1 function omf.cli.reload
  2   if not contains -- --force $argv
  3     if count (jobs) >/dev/null 2>&1
  4       __omf.cli.reload.job_warning
  5       return 1.......
```
this is because ' ^ ' character is no longer used to redirect stderr.
reference: [fish redirect tutorial](https://fishshell.com/docs/current/index.html#redirects)

**Comment by Humandoodlebug** [comment]
This has already been fixed in the dev channel:
```fish
omf channel dev
omf update
omf reload
```
That should fix it ;)

**Comment by Itailevi420** [comment]
Thank's
