### ISSUE TITLE
fish: Unknown command “source” & “omf”

### ISSUE THREAD

**Issue by yvan-sraka** [oh-my-fish/oh-my-fish#75]
Hello,

My terminal output speaks for itself:

    $ curl -L github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | sh
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    100   140  100   140    0     0    203      0 --:--:-- --:--:-- --:--:--   203
    100  4295  100  4295    0     0   4606      0 --:--:-- --:--:-- --:--:--  4Installing Oh My Fish...
    606
    Resolving Oh My Fish path → /home/ysr/.local/share/omf
    Cloning Oh My Fish → https://github.com/oh-my-fish/oh-my-fish.git
    Oh My Fish revision id → 9f3ab25515e1e10bdaff2c7218bede3c94eeeea8
    Adding Oh My Fish bootstrap → /home/ysr/.config/fish/config.fish
    fish: Unknown command “source”
    /home/ysr/.config/fish/config.fish (line 13): source $OMF_PATH/init.fish
                                                  ^
    in . (source) call of file “/home/ysr/.config/fish/config.fish”,
	    called on standard input,

    fish: Unknown command “omf”
    Standard input: omf install
                    ^
    Oh My Fish couldn't install, but you can complain here → github.com/oh-my-fish/oh-my-fish/issues

Does anyone have an idea about what might cause this issue?

Thank you,

**Comment by jeremiejig** [comment]
Hi there,

Seems to me that you have an older version of fish.
Omf need to have at least fish 2.1.0.
Check out http://fishshell.com/ on how to install the latest.

**Comment by yvan-sraka** [comment]
I confirm this fixes the problem.

**Comment by jasdeepsingh** [comment]
I'm having this same issue
```
➜ ~>fish -v
fish, version 2.1.2
➜ ~>omf
```

**Comment by derekstavis** [comment]
Please describe it better @jasdeepsingh, possibly pasting the error transcript.
