### ISSUE TITLE
omf considerably slowing down fish

### ISSUE THREAD

**Issue by tomrcht** [oh-my-fish/oh-my-fish#752]
Hey,

fish recently became almost unusable because of a weird performance issue I have. After testing different configurations, it seems that omf is the source of the problem.
Basically, I'm having a **1 to 3 seconds lag** on almost all commands, especially on startup or on `cd`. You can find the numbers below:

**LS WITH OMF**
```
~
⟩ time fish -c 'ls /'
Applications  bin  cores  dev  etc  home  Library  opt  private  sbin  System  tmp  Users  usr  var  Volumes
________________________________________________________
Executed in    1.73 secs   fish           external
   usr time  1116.22 millis  116.00 micros  1116.10 millis
   sys time  568.51 millis  470.00 micros  568.04 millis
```

**LS WITHOUT OMF**
```
tom@Toms-MacBook-Pro ~> time fish -c 'ls /'
Applications  bin  cores  dev  etc  home  Library  opt  private  sbin  System  tmp  Users  usr  var  Volumes

________________________________________________________
Executed in  154.06 millis    fish           external
   usr time  111.05 millis   92.00 micros  110.96 millis
   sys time   40.19 millis  397.00 micros   39.79 millis
```

**CD WITH OMF**
```
~
⟩ time fish -c 'cd ~/source'

________________________________________________________
Executed in    2.28 secs   fish           external
   usr time    1.48 secs  116.00 micros    1.48 secs
   sys time    0.77 secs  597.00 micros    0.77 secs
```

```
⟩ time fish -c 'cd'

________________________________________________________
Executed in    2.30 secs   fish           external
   usr time    1.48 secs  127.00 micros    1.48 secs
   sys time    0.77 secs  505.00 micros    0.77 secs
```

**CD WITHOUT OMF**
```
tom@Toms-MacBook-Pro ~> time fish -c 'cd ~/source'

________________________________________________________
Executed in  149.14 millis    fish           external
   usr time  108.95 millis  104.00 micros  108.85 millis
   sys time   37.77 millis  479.00 micros   37.29 millis
```

```
tom@Toms-MacBook-Pro ~> time fish -c 'cd'

________________________________________________________
Executed in  143.07 millis    fish           external
   usr time  105.44 millis   75.00 micros  105.36 millis
   sys time   35.70 millis  339.00 micros   35.37 millis
```

---

Here's the details, works with the `stable` or `dev` channel of omf; tested after a clean install:
```
MacBook Pro (2017)
iTerm Build 3.3.9
fish, version 3.1.0
```

**Comment by maxchang** [comment]
Same issue here, which seems to involve svn somehow. 

My workaround was to remove svn from `vcs.name.fish` in `~/.local/share/omf/pkg/vcs/functions/`.

**Comment by atiyo** [comment]
I had similarly heavy slowdowns recently too. I found it was not OMF at fault, but the theme I was using. I had been using this theme for years without issue beforehand, but it only slowed down with some recent upgrades.

Swapping out to a different theme solved my issues.

**Comment by faho** [comment]
This isn't really *actionable* as such. If there's a specific theme that slows things down that should be fixed, but this doesn't seem to mention any?

Also it was reported quite a while ago so things might have already changed in the meantime.

**Comment by scorphus** [comment]
Yeah, probably an overloaded prompt. Certainly related to a specific theme and should therefore be either moved or closed. In the absence of the theme where to move this one to, let's close it.
