### ISSUE TITLE
Lots of white space between entries/not outputting to newline

### ISSUE THREAD

**Issue by Kenney-G** [oh-my-fish/oh-my-fish#757]
![WindowsTerminal_Mr50pcyVg4](https://user-images.githubusercontent.com/39413174/80246414-5f1a3680-863a-11ea-8ba8-ef2146ef9e39.png)

I've had this problem before and managed to fix it, but I can't remember the cause and I can't seem to find the solution again.

**Comment by Kenney-G** [comment]
Never mind, it is working normally now. Not sure what I did...

**Comment by bobthecow** [comment]
At one point, I believe I had a similar problem. Reloading fish after upgrade would cause this, but closing the terminal tab and starting over would fix it.
