### ISSUE TITLE
Export PATH

### ISSUE THREAD

**Issue by fredo-wunder** [oh-my-fish/oh-my-fish#76]
Hei, 

i can't find a way of adding dirs to the $PATH. Adding them to the ~/.config/fish/config.fish doesn't seem to work: 

ex: 

export PATH="$HOME/.composer/vendor/bin:$PATH"

how can i get it there?

thanks

**Comment by bpinto** [comment]
This would be the syntax expected by fish-shell: `set PATH $HOME/.composer/vendor/bin $PATH`.

P.S.: You might be interested on using the plugin called [composer](https://github.com/oh-my-fish/plugin-composer).

**Comment by derekstavis** [comment]
Fish paths are separated by spaces, not : like Bash/Zsh. Also `export` does not work. This should work:

`set -x PATH $HOME/.composer/vendor/bin $PATH`

**Comment by pioneerskies** [comment]
I'd advice you to consider a Fish matter, before an OMF one. Take a look (here)[http://fishshell.com/docs/current/tutorial.html#tut_path] if you're interested :)
