### ISSUE TITLE
total mess

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [oh-my-fish/oh-my-fish#760]
after a fresh install i run `ls` command and tried other commands like `omf update` & i got this:

![omf](https://user-images.githubusercontent.com/17873513/81504779-79673c00-92eb-11ea-8860-7c2008954d20.PNG)

i dont understand why all those spaces between files & words
**Environment report**

```
Oh My Fish version:   7
OS type:              WSL (Linux)
Fish version:         fish, version 3.1.0
Git version:          git version 2.26.2
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

**Comment by bobthecow** [comment]
I used to see a similar thing immediately after updates (but haven't in a while). Try closing the tab and opening a new one?

**Comment by mIcHyAmRaNe** [comment]
thank you for the fast reply.
after closing it 3 times & reinstalling it then reclosing 2 times, it works as it should 
i close this even if we dont know what was the problem behind that
