### ISSUE TITLE
How can I hide this letter "I"?

### ISSUE THREAD

**Issue by xinianteam** [oh-my-fish/oh-my-fish#762]
![image](https://user-images.githubusercontent.com/54789676/82108098-d2592900-975e-11ea-9b76-f090a20d181f.png)

**Comment by bobthecow** [comment]
That’s your fish mode prompt. Are you intentionally using git bindings and insert mode?

Are you asking “how do I hide the prompt thing saying I’m in insert mode?” or “how do I get out of insert mode?”

**Comment by xinianteam** [comment]
> That’s your fish mode prompt. Are you intentionally using git bindings and insert mode?
> 
> Are you asking “how do I hide the prompt thing saying I’m in insert mode?” or “how do I get out of insert mode?”

yes, please tell me how do I hide the prompt thing saying I’m in insert mode?

**Comment by bobthecow** [comment]
fish adds that by default from a function called `fish_mode_prompt`. they changed how it interacts with the rest of your prompt in fish 3.x. some themes have updated to do reasonable things with it, others still haven't :) 

if you don't want the mode prompt at all, you can disable it by adding an empty `fish_mode_prompt` function to your config somewhere.

**Comment by xinianteam** [comment]
> fish adds that by default from a function called `fish_mode_prompt`. they changed how it interacts with the rest of your prompt in fish 3.x. some themes have updated to do reasonable things with it, others still haven't :)
> 
> if you don't want the mode prompt at all, you can disable it by adding an empty `fish_mode_prompt` function to your config somewhere.

Great！Thanks

**Comment by xinianteam** [comment]
![image](https://user-images.githubusercontent.com/54789676/82141827-f013b480-986a-11ea-9e6d-1f2a81b6a48a.png)
Successful！
