### ISSUE TITLE
Fixing OMF theme install

### ISSUE THREAD

**Issue by nipunarora** [oh-my-fish/oh-my-fish#764]
I installed OMF using the standard curl script described in the readme. I'm trying to get some of the themes to work, but I see the following in my iterm2 shell after install. Installing any of the themes doesn't seem to change anything. Can anyone help figure out what I am doing wrong? 

![image](https://user-images.githubusercontent.com/6579650/84100270-830ebd00-a9d9-11ea-921a-0f2912666149.png)

This is with `iTerm Build 3.3.11` and the latest Oh My Fish version 7

**Comment by OakNinja** [comment]
Are you talking about the strange glyphs? 

Activate powerline glyphs in iTerm: `Preferences` -> `Profiles` -> `Text` and then check `Use built-in powerline glyphs`

Or download (and use) a powerline compatible font, like `Menlo for powerline` or `Jetbrains Mono`

**Comment by nipunarora** [comment]
thanks @OakNinja ... installed nerd fonts and set that in my `iTerm` and it worked!
