### ISSUE TITLE
Broken output after installation

### ISSUE THREAD

**Issue by adgai19** [oh-my-fish/oh-my-fish#766]
Describe the problem you are having and how to reproduce it. Include any other additional context that can help us troubleshoot.
weird output in alacritty on typing omf [command]
![omf](https://user-images.githubusercontent.com/29275245/85360869-0aab0e80-b538-11ea-9bbc-e1047d20eaaa.png)

**Environment report**
terminal: Alacritty
os: ubuntu 20.04

Run the command `omf doctor` and paste the output here. Example:

```
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.1.0
Git version:          git version 2.25.1
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.

```

**Comment by ldbo** [comment]
Hi, I have had the same issue after installing omf, but it was solved as soon as I opened a new terminal window.

I use Alacritty, and `omf doctor` outputs

```
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.1.2
Git version:          git version 2.27.0
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

**Comment by pakdev** [comment]
Same experience as @ldbo

**Comment by oranja** [comment]
Linking potentially related discussions:
https://github.com/fish-shell/fish-shell/issues/7491
https://github.com/alacritty/alacritty/issues/4419

**Comment by faho** [comment]
This looks like OPOST was disabled in the terminal modes. Fish now resets that, since version 3.2.0. See https://github.com/fish-shell/fish-shell/issues/7133.

I don't believe there is anything for oh-my-fish to do.

**Comment by scorphus** [comment]
Great to know. This is easily reproducible. I'm gonna test it again with 3.2.0

**Comment by scorphus** [comment]
Confirmed. Thanks, @faho 🙌
