### ISSUE TITLE
set: Tried to change the read-only variable “SHLVL” 

### ISSUE THREAD

**Issue by touhidulShawan** [oh-my-fish/oh-my-fish#769]
I am new at the fish shell. I setup fish shell and oh my fish plugin manager in my arch machine. When I worked with nvm then shell give this same message set: Tried to change the read-only variable “SHLVL” I am not understanding it. The last line says not sourcing .config/fish/config.fish but the configuration is being loaded from `~/.config/fish/conf.d/omf.fish` file. How can I solve it
The output of `fish -d4` here
```
<2> fish: exec_path: '/usr/bin/fish', argv[0]: 'fish'
<2> fish: Using compiled in paths:
<2> fish: determine_config_directory_paths() results:
paths.data: /usr/share/fish
paths.sysconf: /etc/fish
paths.doc: /usr/share/doc/fish
paths.bin: /usr/bin
<2> fish: curses var TERM='xterm-256color'
<2> fish: curses var TERMINFO missing or empty
<2> fish: curses var TERMINFO_DIRS missing or empty
<2> fish: 256 color support enabled for TERM=xterm-256color
<2> fish: default emoji width: 2
<2> fish: sourcing /usr/share/fish/config.fish
<2> fish: 256 color support enabled for TERM=xterm-256color
<2> fish: 'fish_term24bit' preference: 24-bit color enabled
<2> fish: sourcing /etc/fish/config.fish
<2> fish: not sourcing /home/shawan/.config/fish/config.fish (not readable or does not exist)
```

**Comment by mrclrchtr** [comment]
Same issue here.. :/

**Comment by scorphus** [comment]
Could you please describe it in more detail? Is it reproducible?

**Comment by lesterfernandez** [comment]
I had this same issue. I fixed it by running
`omf remove nvm`
restarting the terminal
`omf install https://github.com/fabioantunes/fish-nvm`
`omf install https://github.com/edc/bass`
then installed the desired version of node and run
`nvm use <installed version>`
