### ISSUE TITLE
How do I disable the python virtual environment name?

### ISSUE THREAD

**Issue by IgnisDa** [oh-my-fish/oh-my-fish#772]
![error4](https://user-images.githubusercontent.com/60938164/89917999-1ef5b880-dc17-11ea-948c-5788ac72aa5b.png)

The currently activated python virtual environment is shown twice, I think it is because `fish` shows it once and then the omf-theme is outputting it again (`cmorrell`). How can I disable this behaviour so that I can see the currently activated virtual environment only once?

**Comment by bobthecow** [comment]
`set -x VIRTUAL_ENV_DISABLE_PROMPT 1` somewhere in your fish config should disable the virtualenv-provided bit.
