### ISSUE TITLE
install to OpenWRT have some problem

### ISSUE THREAD

**Issue by 8MiYile** [oh-my-fish/oh-my-fish#776]
```
root@8Mi-HomeWLAN ~ [0|1|1]# curl -L https://get.oh-my.fish | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0     44      0  0:00:04  0:00:04 --:--:--    47
100 19035  100 19035    0     0   3497      0  0:00:05  0:00:05 --:--:-- 1327k
fish: Unknown command: fold
fish: 
  printf "$message\n" | command fold -s -w 80
                                ^
in function 'say' with arguments 'Checking\ for\ a\ sane\ environment...'
in function 'sane_environment_check'
in function 'main'
Install aborted: Missing required command: fold
root@8Mi-HomeWLAN ~# opkg install fold
Unknown package 'fold'.
Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_core https://openwrt.proxy.ustclug.org/snapshots/targets/ramips/mt7621/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_base https://openwrt.proxy.ustclug.org/snapshots/packages/mipsel_24kc/base). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_luci https://openwrt.proxy.ustclug.org/snapshots/packages/mipsel_24kc/luci). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_packages https://openwrt.proxy.ustclug.org/snapshots/packages/mipsel_24kc/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_routing https://openwrt.proxy.ustclug.org/snapshots/packages/mipsel_24kc/routing). Skipping.
 * opkg_install_cmd: Cannot install package fold.
```
My Router using fish version
```
root@8Mi-HomeWLAN ~# fish --version
fish, version 3.1.2
```
and Git version
```
root@8Mi-HomeWLAN ~# git --version
git version 2.27.0
```
and cURL version
```
root@8Mi-HomeWLAN ~# curl --version
curl 7.71.1 (mipsel-openwrt-linux-gnu) libcurl/7.71.1 mbedTLS/2.16.6
Release-Date: 2020-07-01
Protocols: file ftp ftps http https 
Features: IPv6 Largefile SSL
```
so idk how install oh-my-fish to OpenWRT in router , If you can help me or tell me how to solve the problem, thank you

**Comment by markusressel** [comment]
I would like to use oh my fish on an OpenWRT router as well, but the installer script is probably not aware of the different package names. F.ex. the `fold` package is called `coreutils-fold` on OpenWRT. Others may not even be part of the official repos.

**Comment by scorphus** [comment]
What happens if you alias `fold` to `coreutils-fold` before installing? Or even better, make it a function in `~/.config/fish/functions/fold.fish`

**Comment by markusressel** [comment]
@scorphus It is not the command that is differently named, but the package that it is contained in. I just tried the installer again and it simply failed to use the `find` command, since it was not installed.

So I went ahead and manually installed the packages required for the installer and it did work.

```
opkg install coreutils-fold git git-http
curl -L https://get.oh-my.fish | fish
```

Since my last comment is about 3 months old now, I cannot remember if I did install any other packages in the meantime, but I am pretty sure this is all that is needed. No alias of custom function override needed.

**Comment by scorphus** [comment]
After making `fold` available were you able to install Oh My Fish to the OpenWRT router?

**Comment by scorphus** [comment]
Meanwhile, https://openwrt.org/packages/start could be helpfu for those with a similar issue. There you can learn how to search for and install packages on OpenWRT.

**Comment by markusressel** [comment]
> After making `fold` available were you able to install Oh My Fish to the OpenWRT router?

Yes. As I have mentioned in my previous comment, I needed to install three packages, after that the official installer script worked.

**Comment by scorphus** [comment]
Cool! Thanks for the tips, @markusressel. I also managed to install it on a docker [container](https://hub.docker.com/r/openwrtorg/rootfs). I had to install not only `coreutils-fold` and `git` but also `git-http`. At all times the error messages were clear enough. I guess this issue will remain as a reference to whoever run into such issues.

Could you please try again, @8MiYile?

**Comment by 8MiYile** [comment]
> Cool! Thanks for the tips, @markusressel. I also managed to install it on a docker [container](https://hub.docker.com/r/openwrtorg/rootfs). I had to install not only `coreutils-fold` and `git` but also `git-http`. At all times the error messages were clear enough. I guess this issue will remain as a reference to whoever run into such issues.
> 
> Could you please try again, @8MiYile?

Happy New Year, bro, i will try it

**Comment by scorphus** [comment]
Awesome!

I'm leaving this issue open until I add those notes to the README and/or the Wiki.

Thanks, @8MiYile! Happy new year too! Let's hope for a better one this time!

**Comment by scorphus** [comment]
Done! https://github.com/oh-my-fish/oh-my-fish/wiki/Common-issues#oh-my-fish-fails-to-install-on-openwrt
