### ISSUE TITLE
Can't Submit My Theme

### ISSUE THREAD

**Issue by Gourob-Dev** [oh-my-fish/oh-my-fish#779]
Hey omf team, 
I made a theme for Oh-My-Fish and I wanted to submit it using omf so I did,
```
omf submit themes/sdev https://github.com/Gourob-Dev/SDEV
```
But, it gave me this error,
```
Unknown command: submit
```

According to [this](https://libraries.io/github/joseluisq/oh-my-fish) it should've worked.

Please help.

**Comment by bobthecow** [comment]
The readme you linked to is an outdated version from three and a half years ago.

To submit a theme, open a pull request against https://github.com/oh-my-fish/packages-main 🙂

**Comment by Gourob-Dev** [comment]
Thanks for that 😊
