### ISSUE TITLE
CentOS7 install breaking

### ISSUE THREAD

**Issue by mooneye14** [oh-my-fish/oh-my-fish#780]
~> fish install --path=~/.local/share/omf --config=~/.config/omf
install (line 1): Expected a command, but instead found a redirection
<!DOCTYPE html>
^
<W> fish: Error while reading file install

Fish shell is reading first character of install file as redirect now. Same result when trying the one liner to pipe to fish.

**Comment by bobthecow** [comment]
It looks like your download failed!

Your `install` starts with `<!DOCTYPE html>`, which means it's an HTML file and not a shell script. Give re-downloading it a try?

**Comment by faho** [comment]
This is marked `closeme`, and should be closed.
