### ISSUE TITLE
Slow fish on teminal startup

### ISSUE THREAD

**Issue by touhidulShawan** [oh-my-fish/oh-my-fish#784]
Fish slow on startup because of oh my fish. But I have to use oh my fish, what can I do?

**Comment by bobthecow** [comment]
You can do a profiling run to see what's slowing down startup. It's often theme-related, in my experience.

```fish
fish --profile foo.prof --command exit
```

**Comment by touhidulShawan** [comment]
Thanks but I have already fixed that.

**Comment by scorphus** [comment]
Would you be kind to share your findings so other users might benefit from your experience?

**Comment by touhidulShawan** [comment]
Actually I only need nvm wrapper for my nodejs and vf wrapper from omf. So I remove the omf and using those wrapper as sperate function in fish.

**Comment by touhidulShawan** [comment]
Recently I have seen that it was not wrong with oh my fish itself that causes slow startup. I have to use the nvm wrapper to manage multiple nodejs. This nvm wrapper causes this slow startup about 5 or 10 sec on terminal launched.
