### ISSUE TITLE
How can I use conda packages in omf ?

### ISSUE THREAD

**Issue by harshakp06** [oh-my-fish/oh-my-fish#785]
When I use with bash it's working. Any way to use conda commands in omf.

![Screenshot from 2020-10-10 12-03-35](https://user-images.githubusercontent.com/48921568/95648008-b3827700-0af1-11eb-9121-95d0d6ace2cd.png)

**Comment by bobthecow** [comment]
It sounds like maybe there are issues with conda + fish?

https://github.com/conda/conda/issues/9059

Regardless, it's not really OMF-related, just fish shell in general, right?

**Comment by harshakp06** [comment]
It's been few days using OMF and I never used fish shell before.

**Comment by scorphus** [comment]
@harshakp06 I hope you found the reason why conda does not work properly. I see a few other issues out there, such as https://stackoverflow.com/questions/42871313/cannot-run-source-activate-with-conda-in-fish-shell. I'll close this for the time being. Please feel free to reopen if that's still an issue and if you beliebe it's related to OMF.
