### ISSUE TITLE
How do I show the full path instead of fish showing the first letter of the directory?

### ISSUE THREAD

**Issue by Joe23232** [oh-my-fish/oh-my-fish#786]
THe problem is that with `fish` it shows the current directory like this:

`~/D/t/test1`

I want it to show this instead:
`~/Desktop/testing/test1`.

Is there a way to achieve this?

**Comment by bobthecow** [comment]
This is a fish-wide setting. Set `fish_prompt_pwd_dir_length` to `0` to stop shortening parent directory names, or any other number to show 2, 3, 4 characters.

**Comment by Joe23232** [comment]
Where would I go exactly, do I modify the `~/.config/fish/fish_variables` file?

**Comment by bobthecow** [comment]
Add `set -gx fish_prompt_pwd_dir_length 0` to `~/.config/fish/config.fish` (or any other config file that's sourced when starting your shell, e.g. `~/.config/omf/init.fish`, or any file at all in fish `conf.d`).

**Comment by Joe23232** [comment]
THanks mate.
