### ISSUE TITLE
Issue with fish prompt using OMF themes

### ISSUE THREAD

**Issue by VanillaBase1lb** [oh-my-fish/oh-my-fish#796]
This is a fresh install of fish and OMF on Arch linux. On installing OMF, any theme like agnoster or bobthefish show `?` as the prompt but it corrects itself on executing `su -l $USER`. I suspect this is something to do with fish or OMF being installed in a non-default directory, but I did install fish from pacman and omf from the official repo.

https://imgur.com/a/ph5TrWb

```
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.1.2
Git version:          git version 2.29.2
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.

```

**Comment by scorphus** [comment]
Looks like you're either not using a powerline font or your locale is not set correctly. If you're using a powerline font, try setting your [locale](https://wiki.archlinux.org/index.php/Locale). (e.g. `LANG=en_US.UTF-8`)

**Comment by VanillaBase1lb** [comment]
Thanks you. The issue was with my locales were different in home and etc locale.conf, which would explain why it worked on executing su -l.

**Comment by scorphus** [comment]
You're welcome. Glad that it now works for you 🖖
