### ISSUE TITLE
Failed to install omf in docker 20.10 version

### ISSUE THREAD

**Issue by sheeaza** [oh-my-fish/oh-my-fish#798]
```
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.1.0
```
```Dockerfile
Dockfile:
 RUN curl -L https://get.oh-my.fish | fish
```
`build with: docker build .`

error output:
```
✔ default successfully installed.
Installation successful!
<W> fish: An error occurred while redirecting file '/dev/tty'
open: No such device or address
Error processing tar file(exit status 1): lchown /tmp/fish.root/fish_universal_variables.notifier: no such file or directory
```

Note: omf can be normally installed on docker version 19, but not version 20, is this fish or omf or docker issue?

**Comment by simonkeng** [comment]
I also see this:

```bash
Step 10/13 : RUN sudo curl -L https://get.oh-my.fish | fish
 ---> Running in 481d645c5d1b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0    234      0 --:--:-- --:--:-- --:--:--   233
100 19035  100 19035    0     0  15744      0  0:00:01  0:00:01 --:--:-- 15744
<W> fish: An error occurred while redirecting file '/dev/tty'
open: No such device or address
```
Running `Docker version 20.10.2`, in centos 8 container. 

Any suggestions?

**Comment by scorphus** [comment]
Could you please share the exact docker command that you used so we can try to reproduce the error?

Meanwhile, you can try installing OMF non-interactively: 

```
$ curl -L https://get.oh-my.fish > install
$ fish install --noninteractive
```

**Comment by scorphus** [comment]
Ah!

> `Step 10/13 : RUN curl -L https://get.oh-my.fish | fish`

You're building the container. That explains why it failed. Could you please share the `Dockerfile` being used?

**Comment by simonkeng** [comment]
Yes, I was seeing if I could automate every setup step in the Dockerfile 😄 

Using `fish install --noninteractive` works but oddly `omf` is still not found.

```dockerfile
RUN curl -L https://get.oh-my.fish > install_omf
RUN fish install_omf --noninteractive
RUN fish && omf install bobthefish
```
```bash
Step 8/16 : RUN fish install_omf --noninteractive
 ---> Running in 328b8d4b8d3d
Checking for a sane environment...
Installing Oh My Fish to /root/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Writing bootstrap to /root/.config/fish/conf.d/omf.fish...
Setting up Oh My Fish configuration...
Updating https://github.com/oh-my-fish/packages-main master... Done!

Installation successful!
Removing intermediate container 328b8d4b8d3d
 ---> 8bda8fcbed0b
Step 9/16 : RUN /usr/bin/fish && omf install bobthefish
 ---> Running in a9823d340d5c
/bin/sh: omf: command not found
The command '/bin/sh -c /usr/bin/fish && omf install bobthefish' returned a non-zero code: 127
```

I added `RUN fish && omf install ...` because I noticed after `fish install --noninteractive` the omf version of fish shell still isn't initialized, but this didn't seem to work in the dockerfile anyways

Here was my Dockerfile initially:

```dockerfile
FROM centos

RUN yum update -y && \
    yum install -y \
        sudo \
        wget \
        git \
        vim

RUN cd /etc/yum.repos.d/ && \
    wget https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_8/shells:fish:release:3.repo

RUN yum install -y \
    fish \
    && yum clean all

RUN curl -L https://get.oh-my.fish | fish
RUN omf install bobthefish
```

fwiw there are other ways to do what I am trying to do (e.g. next I might try to run a setup shell script from `CMD` or `ENTRYPOINT`, or I could always do this provisioning as a user after the image is built with Makefile), but this error 
```
<W> fish: An error occurred while redirecting file '/dev/tty'
``` 
brought me here so I thought I'd see if there was an easy fix.

**Comment by sheeaza** [comment]
https://github.com/moby/moby/issues/41803

This is caused by docker not omf,so close it

**Comment by scorphus** [comment]
Sorry for the extra noise, @sheeaza.

@simonkeng, once installed, `omf` is nota command, but a function, only available in the context of fish. That's why `RUN omf install bobthefish` doesn't work. You should use `RUN fish -c "omf install bobthefish"` instead.
