### ISSUE TITLE
Plugin solution is not fishy

### ISSUE THREAD

**Issue by bpinto** [oh-my-fish/oh-my-fish#8]
Instead of having every `function` define inside the `PACKAGE.fish` file, let's split the functions into individual files:

```
init.fish
uninstall.fish
PACKAGE.fish
```

It's not only a recommended way of doing it by [fish shell](http://fishshell.com/docs/current/tutorial.html#tut_autoload) but also more efficient because we won't load a function unnecessarily.

**Comment by coderstephen** [comment]
That sounds cleaner to me. Reminds me of the old way of `*.load` files.

**Comment by scorphus** [comment]
Absolutely, I was going to suggest this! It totally makes sense!

**Comment by Gaelan** [comment]
:+1:

**Comment by bobthecow** [comment]
if we're going this route, should't we move 'em to `/functions/*.fish` in the package directory?

**Comment by bpinto** [comment]
@coderstephen 
Indeed it is, but changing the extension from `.load` to `.fish`. :+1: 

@bobthecow 
My initial thought was backwards compatibility, but it's doable.
Later I thought about most plugins that only have one function, and we would now have an extra directory for a single function.

Well, I think it's going to be well structured if we go this route. So, let's do it. The `init.fish` and `uninstall.fish` should not go into the `functions` dir, right?

**Comment by derekstavis** [comment]
>Later I thought about most plugins that only have one function, and we would now have an extra directory for a single function.
I also think that we would like to implement a package description file (or function), where plugins can declare dependencies, so I think that this extra directory isn't a problem, it's a solution for the plugin infrastructure.

**Comment by derekstavis** [comment]
Syntesizing what @bpinto is proposing + `package.fish` idea, a sample plugin directory structure would look like:

```
- plugin-foobar
  * init.fish
  * uninstall.fish
  * package.fish
  - functions
    *foo.fish
    *bar.fish
```

By only adding `functions` directory to autoloading paths we avoid loading unnecessary functions that are only used on load/init/uninstall.

**Comment by bpinto** [comment]
That's it @derekstavis :+1:

**Comment by derekstavis** [comment]
Hm, looks like it's identical, apart from just one file in `functions`

**Comment by bpinto** [comment]
No `package.fish` file.

**Comment by derekstavis** [comment]
Now that we revived this discussion, what about this:

- plugin-foobar
  * init.fish
  * uninstall.fish
  * package.fish
  - lib
    * foobar.fish
    * foo.fish
    * bar.fish

In the future `package.fish` can be used for declaring dependencies, like `package.json`.

What about that approach?

**Comment by bobthecow** [comment]
if we leave `$PACKAGENAME.fish` support in, plugins will work whether they've updated or not.

**Comment by bpinto** [comment]
I think adding support for `$PACKAGENAME.fish` is a temporary solution, but we should migrate them to improve loading time.

**Comment by bobthecow** [comment]
Agreed.

**Comment by coderstephen** [comment]
Nice. :+1:

**Comment by bpinto** [comment]
Time to migrate yours @coderstephen ? :+1:

**Comment by coderstephen** [comment]
Indeed. In the next few days.
