### ISSUE TITLE
Installation of omf fails

### ISSUE THREAD

**Issue by anujva** [oh-my-fish/oh-my-fish#801]
Describe the problem you are having and how to reproduce it. Include any other additional context that can help us troubleshoot.

Ran installation script (which fails with certificate error, I see there is already an issue opened for it):
command: curl -L --insecure https://get.oh-my.fish | fish

Installing package default
✔ default successfully installed.
Installing package hulk
fatal: repository 'hulk' does not exist
Could not install hulk.
Installing package numist
✔ numist successfully installed.
Install aborted: Error installing plugins

Hulk theme seems to have been removed.

Oh My Fish installation failed.
**Environment report**
Ubuntu 20.04 but I don't think there is an issue with the environment.

**Comment by pip182** [comment]
Same

**Comment by scorphus** [comment]
I couldn't reproduce any of the two cases, at least not with a fresh Ubuntu 20.04.

@anujva: Could you please provide any clue as to the reason `hulk` was being installed during OMF installation? Could you please check the contents of `.config/omf/bundle`? That's the only way I could reproduce your issue: having `theme hulk` in `.config/omf/bundle`. Please confirm that's the case.

@pip182: Could you please try again?

Thanks.

**Comment by anujva** [comment]
Yeah.. I think you hit the nail on the head there. I had a previous omf installation with hulk theme installed and the new version has it removed. That's what caused the failure in my case. Btw I did do a `omf destroy` before trying the install again but it looks like that doesn't clean up the configs. Not sure if you want to fix that.
