### ISSUE TITLE
Glyphs display as a "?" in JetBrains Terminal in macOS Big Sur

### ISSUE THREAD

**Issue by iebb** [oh-my-fish/oh-my-fish#802]
Agnoster Theme works normally in macOS Terminal and iTerm 2, but glyphs display as a "?" in JetBrains Terminal.

Interestingly, Oh-My-Zsh works pretty fine in both environments with glyphs displayed correctly, so I guess it's not a powerline issue.

![JetbrainsTerm](https://user-images.githubusercontent.com/2127498/104704864-2421db00-5754-11eb-8b60-b22c2ef0f1db.png)

It worked well previously (in macOS 10.15), however when I upgraded macOS to Big Sur today, these glyphs broke suddenly in Jetbrains.

**Environment report**

Run the command `omf doctor` and paste the output here. Example:

```
Oh My Fish version:   7
OS type:              Darwin
Fish version:         fish, version 3.1.2
Git version:          git version 2.24.3 (Apple Git-128)
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.

```

**Comment by scorphus** [comment]
This is related to JetBrains. Please check if your issue is solved in the same manner as https://youtrack.jetbrains.com/issue/IDEA-192522. Otherwise, please check https://youtrack.jetbrains.com/ for a similar issue or open a new one.

**Comment by iebb** [comment]
After some investigation, I found the problem is related to locale settings.

My current locale setting is `en_HK.UTF-8`, which is a built-in option for iOS/macOS (English / Hong Kong), however omf seems doesn't support it.

https://gist.github.com/jacobbubu/1836273

both LC_CTYPE=`en_US.UTF-8` and `UTF-8` works correctly in fish and zsh, but `en_HK.UTF-8` only works in oh-my-zsh.

additionally, other similar locales such as `en_IN.UTF-8` and `en_MT.UTF-8` doesn't work either.

![screenshot-20210201-074334](https://user-images.githubusercontent.com/2127498/106428687-577a9e80-64a4-11eb-9e14-85dd490a6146.png)

Seems this issue is the same as https://github.com/oh-my-fish/oh-my-fish/issues/410, however since `en_HK.UTF-8` is a completely valid locale - alongside with other valid locales such as `en_IN.UTF-8`, they should be supported.

**Comment by bobthecow** [comment]
This might be an issue with JetBrains, or an issue with Fish Shell itself, but it is unrelated to OMF. You should be able to confirm this by printing a few powerline characters. You'll get the same result with or without OMF installed:

```fish
echo \uE0B0 \uE0B1
```

A good next step might be opening an issue with Fish Shell?

https://github.com/fish-shell/fish-shell

**Comment by iebb** [comment]
Seems it's an issue with fish shell, since zsh / en_HK works in Jetbrains.
