### ISSUE TITLE
Travis branch name is wrong

### ISSUE THREAD

**Issue by bpinto** [oh-my-fish/oh-my-fish#81]
On our [test setup](https://github.com/oh-my-fish/oh-my-fish/blob/master/.travis.yml), when installing Oh My Fish, we call `bin/install` with `OMF_REPO_BRANCH="$TRAVIS_BRANCH"`.

This environment variable is misleading, as we think travis would return the Pull Request branch name but it returns `master` instead.

> TRAVIS_BRANCH: For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master).

As we are using `master` instead, it's likely that PRs that break the install script will not have broken tests before they are merged. Does anyone know a solution for this?

Ref: http://docs.travis-ci.com/user/environment-variables/

---

On the PR #80, there are two builds from Travis:

The one that is [successful](https://travis-ci.org/oh-my-fish/oh-my-fish/builds/82666179) has the following exported information:
```
OMF_REPO_BRANCH dockerize
OMF_REPO_URI https://github.com/oh-my-fish/oh-my-fish
```

And the one that [fails](https://travis-ci.org/oh-my-fish/oh-my-fish/builds/82666309):

```
OMF_REPO_BRANCH master
OMF_REPO_URI https://github.com/oh-my-fish/oh-my-fish
```

**Comment by jeremiejig** [comment]
In our test setup, we don't call `bin/install` we call `tools/travis_install_omf.sh`.

As you [can see](https://github.com/oh-my-fish/oh-my-fish/blob/master/tools/travis_install_omf.sh) I added a hook when the build is a PR.

**Comment by bpinto** [comment]
Inside `travis_install_omf.sh` we call `bin/install`:
https://github.com/oh-my-fish/oh-my-fish/blob/master/bin/install#L33-L34

Am I missing something?

**Comment by jeremiejig** [comment]
Yep I override `git` in `travis_install_omf.sh` and treat clone differently. 

See here https://github.com/oh-my-fish/oh-my-fish/blob/master/tools/travis_install_omf.sh#L7

You should keep tools/travis_install_omf.sh for docker. It normally work everywhere as on a non-travis environment there isn't any `TRAVIS_env` variable.

**Comment by bpinto** [comment]
That only changes the git travis does, not the git `bin/install` does. See comment above.

**Comment by bpinto** [comment]
Closing it as it's only a bug on #80

**Comment by derekstavis** [comment]
You won a :star: for this git override thing haha
