### ISSUE TITLE
Port 443 connection refused

### ISSUE THREAD

**Issue by JLepp82** [oh-my-fish/oh-my-fish#814]
Hi there.
I'm experiencing a problem I haven't experienced before and I have having trouble finding an answer on google. I tried using the curl download and install and I'm getting this error.
`joey@pop-os ~/D/oh-my-fish-7> curl -L https://get.oh-my.fish | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to get.oh-my.fish port 443: Connection refused`

Is this correct format? I've never asked a question like this before.

**Comment by oranja** [comment]
My bad. I was trying to do some maintenance on the server and botched it. :/
While I'm getting it fixed, please replace https://get.oh-my.fish with https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install

**Comment by JLepp82** [comment]
No worries! I very much appreciate what you and the rest of the git community does for me and offers to me on a daily basis.

**Comment by oranja** [comment]
Should be fixed now.

**Comment by JLepp82** [comment]
You're great, thanks!

**Comment by scorphus** [comment]
Thanks, @oranja 👍
