### ISSUE TITLE
Question mark in shell prompt instead of > graphic

### ISSUE THREAD

**Issue by SCCOBN** [oh-my-fish/oh-my-fish#817]
I have oh-my-fish on Arch, patched powerline and nerd fonts, in terminal tried several different patched fonts, both powerline and nerd, and in theme set them to use and not use powerline and nerd fonts, in different combinations. With themes agnoster and bobthefish I'm seeing question mark on the prompt instead of > graphic. 

No working tips found using google search. All the tips with patched fonts, do not work.

AT THAT, I also have zsh and I don't have issues with question mark in zsh. Thus it is not fonts issue. I really don't know what to do and ready to give up. Point me to the right direction.

**Comment by scorphus** [comment]
We can only help you identify the problem on your end. Glyphs work for many users in very different setups, so quite likely it to be either an issue with the terminal app with Fish Shell or a misconfiguration.

Can you please share:
- Fish Shell version
- Font used
- Terminal app and version

Also:
- OMF theme used, if any
- A screenshot of the output of `echo \uE0B0 \uE0B1`

**Comment by faho** [comment]
The OP never answered, this issue should probably be closed.

**Comment by scorphus** [comment]
Let's close it for now, then. Thanks, @faho.

**Comment by LawrenceLiu023** [comment]
Try `echo $LANG` in your terminal. If the output doesn't ends with "UTF-8", like "en_US.UTF-8", maybe you could try adjusting the locale settings.

**Comment by LawrenceLiu023** [comment]
Try `echo $LANG` in your terminal. If the output doesn't ends with "UTF-8", like "en_US.UTF-8", maybe you could try adjusting the locale settings.
