### ISSUE TITLE
Support no theme

### ISSUE THREAD

**Issue by KotlinIsland** [oh-my-fish/oh-my-fish#820]
What if i want to go back to no theme without uninstalling omf

**Comment by touhidulShawan** [comment]
Just use the default `omf theme default`

**Comment by KotlinIsland** [comment]
![image](https://user-images.githubusercontent.com/65446343/108642825-303b4e00-74f3-11eb-9dcd-0f8895a25227.png)

This is just the default theme, I don't want a theme.

**Comment by touhidulShawan** [comment]
I don't think you can go fish default theme without destroying oh my fish. In that case, you can use  starship prompt
![2021-02-22-122228_341x156_escrotum](https://user-images.githubusercontent.com/37136490/108670184-a8603e80-7508-11eb-8e1b-edc8ba070146.png)

**Comment by KotlinIsland** [comment]
Can you add support for it?

**Comment by touhidulShawan** [comment]
You have to install starship in your environment. Then source it ou you omf.fish config file.  You can find details about how to install and configure starship prompt [here](https://starship.rs/guide/)

**Comment by scorphus** [comment]
Starship is an overkill in this case. You can simply override `fish_prompt` function with Fish's stock default:

    ~> mkdir -p ~/.config/fish/functions
    ~> ln -s /usr/local/share/fish/functions/fish_prompt.fish ~/.config/fish/functions/

Same for the `fish_right_prompt` function, reset it to Fish's default (empty):

    ~> echo "function fish_right_prompt; end" > ~/.config/fish/functions/fish_right_prompt.fish

Then, reload your shell to instantly apply the changes (if they're not applied already):

    ~> omf reload

**Comment by AuHau** [comment]
Is this still applicable for Fish 3.*? It is not working as expected...
