### ISSUE TITLE
Shell does not show the hostname and computer name

### ISSUE THREAD

**Issue by carrotfarmer** [oh-my-fish/oh-my-fish#825]
OhMyFish does not show the hostname and computer name by default.
![image](https://user-images.githubusercontent.com/66675022/111353854-b2aace00-86ab-11eb-985d-da12c3c0e6de.png)

Is there any way to change this setting so that it shows the hostname and computer name like how it is shown in the default `fish` shell?
![image](https://user-images.githubusercontent.com/66675022/111354097-f4d40f80-86ab-11eb-97ca-8ecf993017f1.png)

**Environment report**
![image](https://user-images.githubusercontent.com/66675022/111354211-133a0b00-86ac-11eb-916c-8d28b2b2c003.png)

**BTW I am using the default terminal which comes with Ubuntu 20.04 (Focal Fossa)**

Thanks!

**Comment by scorphus** [comment]
Hey! 👋

That is the default behaviour of OMF's default theme. Take a look at other themes here: https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md. You can check how to change your theme here: https://github.com/oh-my-fish/oh-my-fish#getting-started 

Alternatively, you can customize your prompt by changing the `fish_prompt` function. Here's the documentation: https://fishshell.com/docs/current/cmds/fish_prompt.html

**Comment by carrotfarmer** [comment]
Thanks!
