### ISSUE TITLE
Failed to swith theme

### ISSUE THREAD

**Issue by guluo2016** [oh-my-fish/oh-my-fish#826]
**Environment report**   
```
Oh My Fish version:   master
OS type:              Linux
Fish version:         fish, version 3.2.0
Git version:          git version 2.30.1
```

**problem**  
when theme-zish and theme-agnoster are installed , I failed to switch from zish to agnoster and vice versa. I executed `omf doctor` and found the following information：
```
Warning: fish_prompt.fish is overridden.
  fish_config command persists the prompt to ~/.config/fish/functions/fish_prompt.fish
  That file takes precedence over Oh My Fish's themes. Remove the file to fix it:
  rm ~/.config/fish/functions/fish_prompt.fish
````

**debug**
After debuging , I found that zish and agnoster have different structure. So the location of fish_prompt.fish also is different，This will cause to fail  to load fish_prompt.fish file.  
![zish](https://user-images.githubusercontent.com/19660320/111621779-58347d80-8823-11eb-8688-eb5cc759c950.png) 
![ago](https://user-images.githubusercontent.com/19660320/111621841-697d8a00-8823-11eb-9727-34a450dd3a6d.png)

**Comment by lnx-soul** [comment]
I see the same problem each time `fish` is updated with Homebrew.  Thanks for the fix!

**Comment by addictedtolinux** [comment]
Also related to #671 .
