### ISSUE TITLE
Unable to Use Different Color Themes

### ISSUE THREAD

**Issue by Akshay-Manke** [oh-my-fish/oh-my-fish#830]
Hi,

I am using Kali 2021.1 build and i have installed Fish. To do more customization i installed OMF and trying to use colorizer to change the color of the output. However i am not able to do that. I tried installing grc but every time i get message 'You need to install grc'.

Below the OS details.

OS: Kali GNU/Linux Rolling x86_64 
Kernel: 5.10.0-kali3-amd64 
Packages: 2902 (dpkg) 
Shell: fish 3.2.1 
 
I am also attaching a snap which i took from Luke Smith's video from here. [https://www.youtube.com/watch?v=C2a7jJTh3kU](url)

I am just trying to apply similar to the attached snap. 

Can anyone please help me for the same?

Many Thanks in Advance.

Regards,
Akshay
![Snip](https://user-images.githubusercontent.com/64018825/115520708-10809600-a2a8-11eb-910d-0a64efb4140a.JPG)

**Comment by lnx-soul** [comment]
@Akshay-Manke So the installation was unsuccessful or was it successful but setting the `grc` theme is failing?

**Comment by Akshay-Manke** [comment]
Hello @lnx-soul , yes the installation is successful but only failing in setting up gracy theme.

Thanks

**Comment by lnx-soul** [comment]
You're getting that error because you need to install `grc` on your system as well.  There is a package for the plugin that you need.  Using apt or brew will solve your problem.

```sh
sudo apt install grc -y
```

**Comment by Akshay-Manke** [comment]
Thanks Brian, I will try that and will get back with the results. @lnx-soul

**Comment by faho** [comment]
Reporter didn't get back with the results, but since the question is answered this can be closed.
