### ISSUE TITLE
Slack status badge not shown properly in Readme.md

### ISSUE THREAD

**Issue by corneliusroemer** [oh-my-fish/oh-my-fish#839]
Slack status badge not shown properly in Readme.md on Github, see screenshot:

<img width="1191" alt="Screenshot 2021-06-27 at 13 06 27" src="https://user-images.githubusercontent.com/25161793/123542232-bfc66700-d748-11eb-9052-1eb9aaa725b4.png">

**Comment by scorphus** [comment]
Fixed in #883
