### ISSUE TITLE
Invisible path

### ISSUE THREAD

**Issue by ICHx** [oh-my-fish/oh-my-fish#841]
Today is my first install of omf and fish.
Using fish alone is okay, but with omf, the path disappear, with any themes.

I am using Ubuntu on aarch64 chroot, on Android.

![image](https://user-images.githubusercontent.com/11556527/123831285-c1ee1880-d936-11eb-8816-58cc58918b75.png)

![image](https://user-images.githubusercontent.com/11556527/123830906-56a44680-d936-11eb-8cf6-b5c04b773a94.png)

**Environment report**

Run the command `omf doctor` and paste the output here. Example:

```
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.1.0
Git version:          git version 2.25.1
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```
```bash
lsb_release -av                                                                                            00:02:19
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**Comment by ICHx** [comment]
![image](https://user-images.githubusercontent.com/11556527/123832217-b0594080-d937-11eb-8773-84fbb3f4b7cf.png)

**Comment by faho** [comment]
>Fish version:         fish, version 3.1.0

This is a bug in fish 3.1.0, please upgrade to at least fish 3.1.1 - https://github.com/fish-shell/fish-shell/issues/6736.

The workaround is to fix your locale - you're using a C (ascii-only) locale with non-ascii characters, which is basically broken.

(this isn't omf related and can therefore be closed)

**Comment by scorphus** [comment]
Thank you, @faho!
