### ISSUE TITLE
Custom greeting messsage does not print

### ISSUE THREAD

**Issue by parasbhanot** [oh-my-fish/oh-my-fish#843]
Hello everyone , 

i am facing issue with greeting message when i start the terminal . it prints following default greeting message although i have the set fish_greeting variable in **init.fish** file but when i use omf reload command in the terminal it prints the correct output . 

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

Following are the contents of my init.fish

```
starship init fish | source

alias ls="lsd"
alias lsl="exa -al --group-directories-first"

function fish_user_key_bindings
	fzf_key_bindings
end

#set -x EDITOR nvim
export EDITOR=nvim

alias bat="bat --theme gruvbox"
alias yay="paru"

set fish_greeting "hello parasbhanot"

alias rn="ranger"
alias ydl="youtube-dl"
```

Am i doing something wrong here ?

Note : 

```
Oh My Fish version:   7
OS type:              Linux , (Arch)
Fish version:         fish, version 3.3.1
Git version:          git version 2.32.0
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

**Comment by scorphus** [comment]
Please, try exporting it — i.e. `set -e fish_greeting "hello parasbhanot"`.

**Comment by parasbhanot** [comment]
> Please, try exporting it — i.e. `set -e fish_greeting "hello parasbhanot"`.

i tried doing that but received the following error :

```
set: Variable name 'hello parasbhanot...' is not valid. See `help identifiers`.

~/.config/omf/init.fish (line 4): 
set -e fish_greeting "hello parasbhanot..."
^
from sourcing file ~/.config/omf/init.fish
	called on line 75 of file ~/.local/share/omf/lib/require.fish
in function 'require' with arguments '--no-bundle --path /home/parasbhanot/.config/omf'
	called on line 49 of file ~/.local/share/omf/init.fish
from sourcing file ~/.local/share/omf/init.fish
	called on line 7 of file ~/.config/fish/conf.d/omf.fish
from sourcing file ~/.config/fish/conf.d/omf.fish
	called on line 253 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
	called during startup

(Type 'help set' for related documentation)
blocks1
```

**Comment by parasbhanot** [comment]
For anyone who is facing the same issue . 

i have solved it by using the export command instead of set in init.fish  like this : 

`export fish-greeting="Hello parasbhanot"` 

But it is still a bug in oh my fish /fish

**Comment by faho** [comment]
@parasbhanot What is your `fish_greeting` function?

Fish now only prints the variable in the default greeting function, if that was replaced the variable won't have an effect.

So the output of `type fish_greeting` would be useful.

**Comment by parasbhanot** [comment]
sorry for the late reply , here are the contents of fish_greeting function 
```
~ ❯ type fish_greeting                                                       22:23:45
fish_greeting is a function with definition
# Defined in /usr/share/fish/functions/fish_greeting.fish @ line 1
function fish_greeting
    if not set -q fish_greeting
        set -l line1 (_ 'Welcome to fish, the friendly interactive shell')
        set -l line2 \n(printf (_ 'Type %shelp%s for instructions on how to use fish') (set_color green) (set_color normal))
        set -g fish_greeting "$line1$line2"
    end

    if set -q fish_private_mode
        set -l line (_ "fish is running in private mode, history will not be persisted.")
        if set -q fish_greeting[1]
            set -g fish_greeting $fish_greeting\n$line
        else
            set -g fish_greeting $line
        end
    end

    # The greeting used to be skipped when fish_greeting was empty (not just undefined)
    # Keep it that way to not print superfluous newlines on the old configuration
    test -n "$fish_greeting"
    and echo $fish_greeting
end
```

I have also observed that 'set var value' syntax is not working in init.fish file . I have also tested with neovim as my default editor . 

The following syntax does not work in init.fsh file --> 

`set EDITOR nvim`

but the following normal export syntax works for some reason --> 

`export EDITOR=nvim`

**Comment by faho** [comment]
Ah, I think I got it. Try this:

```fish
set -gx EDITOR nvim
set -gx fish_greeting  "hello parasbhanot"
```

This makes the variables *global*. The normal fish configuration file is config.fish, there's probably something in oh-my-fish that opens a new scope in the process of sourcing `init.fish` (which was always a really awkward super special omf thing).

However, it's recommended to make variables global explicitly anyways.

**Comment by scorphus** [comment]
My apologies for the wrong command suggestion earlier. I always get confused with `-e` vs. `-x` for exporting variables.

I fixed that message for the sake of a future reader.

**Comment by parasbhanot** [comment]
Thanks , setting the variables in the global scope fixed the issue .
