### ISSUE TITLE
`omf theme use <theme-name>` returns inaccurate error message

### ISSUE THREAD

**Issue by thompsonbrian** [oh-my-fish/oh-my-fish#852]
I am coming from zsh and ohmyzsh.  In ohmyzsh, the user sets a theme with `omz theme use <theme-name>`.  I ran the same command in omf, which should have been `omf theme <theme-name>`.  However, the error message reported that I should have used `omf use <theme-name>`, which is inaccurate. 

**Environment report**

This occurs in the master branch and I have a fix ready to go.

```
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.1.0
Git version:          git version 2.25.1
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

**Comment by scorphus** [comment]
Thanks for reporting and for willing to fix it, @thompsonbrian! 👍
