### ISSUE TITLE
themes not applying

### ISSUE THREAD

**Issue by superstefan420** [oh-my-fish/oh-my-fish#856]
i have installed multiped themes and tried to apply them but only the left side after the prompt shows with themes like bobthefish. I tried removing my existing fish prompt with functions --erase fish_prompt but nothing will work

**Comment by Vistaus** [comment]
I currently have the same issue. Worked fine for months, but not anymore.

**Comment by scorphus** [comment]
I'm sorry you're having this issue. Could you please inform what themes are you having that issue with?

This seems like a duplicate of #671. Please check there for possible workarounds.

**Comment by Vistaus** [comment]
With every theme.

**Comment by scorphus** [comment]
1. What does `type fish_prompt` give as output?
2. What does `ls -lh (type -p fish_prompt)` give as output?
