### ISSUE TITLE
Strange symbol before prompt

### ISSUE THREAD

**Issue by Akash-S1999** [oh-my-fish/oh-my-fish#858]
Hi, I installed ohmyfish and then applied a theme listed in https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md. 
After installing i am getting this green strange symbol infront of the prompt. Does anyone know how to fix it?

![Screenshot 2021-09-18 181229](https://user-images.githubusercontent.com/52990376/133889218-80d18174-ba5a-4d82-9848-4df7d7120f02.png)

**Comment by scorphus** [comment]
Please, refer to fish-shell/fish-shell#3201.
