### ISSUE TITLE
Constantly getting git error as greeting or every time I run omf

### ISSUE THREAD

**Issue by mityakoval** [oh-my-fish/oh-my-fish#87]
I'm just constantly getting
`fatal: Not a git repository (or any of the parent directories): .git`
whatever I do. This is my greeting when I open iTerm and when I run:
`omf install [whatever]`
this command succeeds but then it gives me this git error.

**Comment by derekstavis** [comment]
What's your current theme?

**Comment by mityakoval** [comment]
just a default one

**Comment by bpinto** [comment]
Do you have any plugins? Could you remove each plugin with `omf remove PACKAGE_NAME` and see if it was one of the plugins?

**Comment by mityakoval** [comment]
Well, I've just reinstalled fish and the error was still there. But then I've reinstalled oh-my-fish and it disappeared. Thank you for your quick answers! That is awesome!

**Comment by bpinto** [comment]
I'm glad it has been solved!
