### ISSUE TITLE
'omf destroy' fails

### ISSUE THREAD

**Issue by n4ff4h** [oh-my-fish/oh-my-fish#882]
⋊> ~ omf destroy                                                        14:20:43
Checking for a sane environment...
This will uninstall Oh My Fish and all plugins and themes from
/Users/naffah/.local/share/omf.
read> y
Uninstalling from /Users/naffah/.local/share/omf...
rm: /Users/naffah/.local/share/omf/tools/generate-authors.fish: Permission denied
rm: /Users/naffah/.local/share/omf/tools/generate-themes-doc.fish: Permission denied
rm: /Users/naffah/.local/share/omf/tools/travis-github-pr-integration.sh: Permission denied
rm: /Users/naffah/.local/share/omf/tools/travis-install-fish.sh: Permission denied
rm: /Users/naffah/.local/share/omf/tools/travis-install-git.sh: Permission denied
rm: /Users/naffah/.local/share/omf/tools: Permission denied
rm: /Users/naffah/.local/share/omf/LICENSE: Permission denied
rm: /Users/naffah/.local/share/omf/bin/install: Permission denied
rm: /Users/naffah/.local/share/omf/bin/install.sha256: Permission denied
rm: /Users/naffah/.local/share/omf/bin: Permission denied
rm: /Users/naffah/.local/share/omf/CHANGELOG.md: Permission denied
rm: /Users/naffah/.local/share/omf/AUTHORS: Permission denied
rm: /Users/naffah/.local/share/omf/Dockerfile: Permission denied
rm: /Users/naffah/.local/share/omf/CODEOWNERS: Permission denied
rm: /Users/naffah/.local/share/omf/tests/run.fish: Permission denied
rm: /Users/naffah/.local/share/omf/tests: Permission denied
rm: /Users/naffah/.local/share/omf/repositories: Permission denied
rm: /Users/naffah/.local/share/omf/docs/es-ES/FAQ.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/es-ES/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/es-ES/Packages.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/es-ES: Permission denied
rm: /Users/naffah/.local/share/omf/docs/ru-RU/FAQ.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/ru-RU/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/ru-RU/Packages.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/ru-RU: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/cd.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/new.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/version.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/theme.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/search.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/destroy.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/reload.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/channel.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/repositories.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/doctor.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/describe.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/remove.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/list.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/help.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/omf.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/update.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli/install.adoc: Permission denied
rm: /Users/naffah/.local/share/omf/docs/cli: Permission denied
rm: /Users/naffah/.local/share/omf/docs/zh-CN/FAQ.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/zh-CN/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/zh-CN/Packages.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/zh-CN: Permission denied
rm: /Users/naffah/.local/share/omf/docs/logo.png: Permission denied
rm: /Users/naffah/.local/share/omf/docs/Themes.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/pt-BR/FAQ.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/pt-BR/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/pt-BR/Packages.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/pt-BR: Permission denied
rm: /Users/naffah/.local/share/omf/docs/en-US/FAQ.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/en-US/Packages.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/en-US: Permission denied
rm: /Users/naffah/.local/share/omf/docs/uk-UA/FAQ.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/uk-UA/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/uk-UA/Packages.md: Permission denied
rm: /Users/naffah/.local/share/omf/docs/uk-UA: Permission denied
rm: /Users/naffah/.local/share/omf/docs/logo.svg: Permission denied
rm: /Users/naffah/.local/share/omf/docs: Permission denied
rm: /Users/naffah/.local/share/omf/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/.gitignore: Permission denied
rm: /Users/naffah/.local/share/omf/CONTRIBUTING.md: Permission denied
rm: /Users/naffah/.local/share/omf/init.fish: Permission denied
rm: /Users/naffah/.local/share/omf/.github/PULL_REQUEST_TEMPLATE.md: Permission denied
rm: /Users/naffah/.local/share/omf/.github/ISSUE_TEMPLATE/bug_report.md: Permission denied
rm: /Users/naffah/.local/share/omf/.github/ISSUE_TEMPLATE: Permission denied
rm: /Users/naffah/.local/share/omf/.github: Permission denied
rm: /Users/naffah/.local/share/omf/.gitattributes: Permission denied
rm: /Users/naffah/.local/share/omf/lib/completions/.gitkeep: Permission denied
rm: /Users/naffah/.local/share/omf/lib/completions: Permission denied
rm: /Users/naffah/.local/share/omf/lib/autoload.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/lib/prompt_segments.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/require.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/git/git_is_staged.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/git/git_ahead.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/git/git_is_repo.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/git/git_is_touched.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/git/git_untracked.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/git/git_is_dirty.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/git/git_branch_name.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/git/git_is_stashed.fish: Permission denied
rm: /Users/naffah/.local/share/omf/lib/git: Permission denied
rm: /Users/naffah/.local/share/omf/lib: Permission denied
rm: /Users/naffah/.local/share/omf/templates/config.fish: Permission denied
rm: /Users/naffah/.local/share/omf/templates: Permission denied
rm: /Users/naffah/.local/share/omf/.git/config: Permission denied
rm: /Users/naffah/.local/share/omf/.git/objects/pack/pack-01a5dfe4adcd8c843ec7e3182b7cf7961f733c43.idx: Permission denied
rm: /Users/naffah/.local/share/omf/.git/objects/pack/pack-01a5dfe4adcd8c843ec7e3182b7cf7961f733c43.pack: Permission denied
rm: /Users/naffah/.local/share/omf/.git/objects/pack: Permission denied
rm: /Users/naffah/.local/share/omf/.git/objects/info: Permission denied
rm: /Users/naffah/.local/share/omf/.git/objects: Permission denied
rm: /Users/naffah/.local/share/omf/.git/HEAD: Permission denied
rm: /Users/naffah/.local/share/omf/.git/info/exclude: Permission denied
rm: /Users/naffah/.local/share/omf/.git/info: Permission denied
rm: /Users/naffah/.local/share/omf/.git/logs/HEAD: Permission denied
rm: /Users/naffah/.local/share/omf/.git/logs/refs/heads/master: Permission denied
rm: /Users/naffah/.local/share/omf/.git/logs/refs/heads: Permission denied
rm: /Users/naffah/.local/share/omf/.git/logs/refs/remotes/origin/HEAD: Permission denied
rm: /Users/naffah/.local/share/omf/.git/logs/refs/remotes/origin: Permission denied
rm: /Users/naffah/.local/share/omf/.git/logs/refs/remotes: Permission denied
rm: /Users/naffah/.local/share/omf/.git/logs/refs: Permission denied
rm: /Users/naffah/.local/share/omf/.git/logs: Permission denied
rm: /Users/naffah/.local/share/omf/.git/description: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/commit-msg.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/pre-rebase.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/pre-commit.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/applypatch-msg.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/fsmonitor-watchman.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/pre-receive.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/prepare-commit-msg.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/post-update.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/pre-merge-commit.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/pre-applypatch.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/pre-push.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/update.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks/push-to-checkout.sample: Permission denied
rm: /Users/naffah/.local/share/omf/.git/hooks: Permission denied
rm: /Users/naffah/.local/share/omf/.git/refs/heads/master: Permission denied
rm: /Users/naffah/.local/share/omf/.git/refs/heads: Permission denied
rm: /Users/naffah/.local/share/omf/.git/refs/tags: Permission denied
rm: /Users/naffah/.local/share/omf/.git/refs/remotes/origin/HEAD: Permission denied
rm: /Users/naffah/.local/share/omf/.git/refs/remotes/origin: Permission denied
rm: /Users/naffah/.local/share/omf/.git/refs/remotes: Permission denied
rm: /Users/naffah/.local/share/omf/.git/refs: Permission denied
rm: /Users/naffah/.local/share/omf/.git/index: Permission denied
rm: /Users/naffah/.local/share/omf/.git/packed-refs: Permission denied
rm: /Users/naffah/.local/share/omf/.git: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/LICENSE: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/functions/fish_prompt.fish: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/functions/fish_right_prompt.fish: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/functions: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/config: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/objects/pack/pack-72507e3a689d2ae046405fd78c9fc2c7c46791a3.pack: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/objects/pack/pack-72507e3a689d2ae046405fd78c9fc2c7c46791a3.idx: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/objects/pack: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/objects/info: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/objects: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/HEAD: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/info/exclude: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/info: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/logs/HEAD: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/logs/refs/heads/master: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/logs/refs/heads: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/logs/refs/remotes/origin/HEAD: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/logs/refs/remotes/origin: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/logs/refs/remotes: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/logs/refs: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/logs: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/description: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/commit-msg.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/pre-rebase.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/pre-commit.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/applypatch-msg.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/fsmonitor-watchman.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/pre-receive.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/prepare-commit-msg.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/post-update.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/pre-merge-commit.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/pre-applypatch.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/pre-push.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/update.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks/push-to-checkout.sample: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/hooks: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/refs/heads/master: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/refs/heads: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/refs/tags: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/refs/remotes/origin/HEAD: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/refs/remotes/origin: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/refs/remotes: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/refs: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/index: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git/packed-refs: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default/.git: Permission denied
rm: /Users/naffah/.local/share/omf/themes/default: Permission denied
rm: /Users/naffah/.local/share/omf/themes: Permission denied
rm: /Users/naffah/.local/share/omf/.travis.yml: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/omf.packages.name.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/omf.repo.pull.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/omf.packages.install.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/omf.bundle.install.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/completions/omf.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/completions: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/spec/basic_spec.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/spec: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/omf.update.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/init.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/compat/.gitkeep: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/compat/refresh.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/compat/available.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/compat: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core/omf.xdg.config_home.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core/omf.reload.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core/omf.command.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core/omf.channel.set.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core/omf.channel.get.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core/omf.destroy.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core/omf.doctor.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core/omf.core.update.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core/omf.version.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/core: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/util/omf.check.fish_prompt.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/util/omf.check.version.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/util: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/bundle/omf.bundle.add.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/bundle/omf.bundle.install.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/bundle/omf.bundle.remove.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/bundle: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.install.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.update.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.cd.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.doctor.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.themes.list.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.remove.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.repositories.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.channel.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.reload.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.destroy.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.help.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.theme.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.new.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.list.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.version.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.search.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli/omf.cli.describe.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/cli: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/omf.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.update.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.name.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.install.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.path.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.cd.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.run_hook.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.remove.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.valid_name.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.new.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages/omf.packages.list.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/packages: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/index/omf.index.stat.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/index/omf.index.repositories.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/index/omf.index.query.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/index/omf.index.update.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/index/omf.index.path.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/index: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/themes/omf.theme.set.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/themes: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/repo/omf.repo.pull.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/repo/omf.repo.clone.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions/repo: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/functions: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/themes/LICENSE: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/themes/fish_prompt.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/themes/fish_greeting.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/themes/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/themes/fish_right_prompt.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/themes/fish_title.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/themes: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/pkg/uninstall.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/pkg/LICENSE: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/pkg/completions/{{NAME}}.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/pkg/completions: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/pkg/README.md: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/pkg/init.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/pkg/functions/{{NAME}}.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/pkg/functions: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates/pkg: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/templates: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf/omf.packages.list.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/omf: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/spec/assert_error_message_spec.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/spec/results_spec.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/spec: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/utils/epoch.osx: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/utils/epoch.c: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/utils/epoch.linux: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/utils: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/basic_formatter.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/functions/fish-spec.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/functions/assert.error_message.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/functions/assert.expand_operator.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/functions/assert.fish: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec/functions: Permission denied
rm: /Users/naffah/.local/share/omf/pkg/fish-spec: Permission denied
rm: /Users/naffah/.local/share/omf/pkg: Permission denied
rm: /Users/naffah/.local/share/omf: Permission denied
Install aborted: Uninstall failed

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues

**Comment by naffah-me** [comment]
⋊> ~ omf install agnoster                                               14:23:42
Updating https://github.com/oh-my-fish/packages-main master... error: cannot open .git/FETCH_HEAD: Permission denied
Error

I am using macos on an m1 macbook
