### ISSUE TITLE
how to remove the {I} symbol?

### ISSUE THREAD

**Issue by smartfellafartsmella69** [oh-my-fish/oh-my-fish#893]
this symbol is really annoying me
its been appearing in every single theme
sometimes breaking the theme
tried uninstalling omf
tried uninstalling fish
nothing worked

for example:
[I] # dan64
$

OS type:             endeavour os Linux
Fish version:       fish, version 3.4.1
Git version:         git version 2.35.1
omf version :      omf version 7

```

**Comment by faho** [comment]
https://fishshell.com/docs/current/faq.html#why-does-my-prompt-show-a-i

This means you have vi-mode enabled and fish enabled the mode prompt. If you didn't pick vi-mode, some plugin "helpfully" picked it for you. To disable vi-mode, run `fish_default_key_bindings`.

To change the mode prompt change the `fish_mode_prompt` function.

**Comment by smartfellafartsmella69** [comment]
> https://fishshell.com/docs/current/faq.html#why-does-my-prompt-show-a-i
> 
> This means you have vi-mode enabled and fish enabled the mode prompt. If you didn't pick vi-mode, some plugin "helpfully" picked it for you. To disable vi-mode, run `fish_default_key_bindings`.
> 
> To change the mode prompt change the `fish_mode_prompt` function.

thanks! it worked!, it was probably a theme that needed vi mode enabled, thanks again!
