### ISSUE TITLE
omf remove doesn't remove non omf plugins

### ISSUE THREAD

**Issue by bdmorin** [oh-my-fish/oh-my-fish#901]
I installed a custom plugin `omf install https://github.com/wfxr/forgit` works fine.
I installed grc `omf install grc`
`grc` now has some conflicts.
```
type -a grc                                                                                                                Sun May 22 12:04:51 2022
grc is a function with definition
# Defined via `source`
function grc --wraps=forgit::revert::commit --description 'alias grc forgit::revert::commit'
  forgit::revert::commit $argv;
end
grc is /usr/local/bin/grc
```
this is fine, I could just remove the forgit grc function.
However I decided to not use forgit, so I wanted to uninstall it.
```
 ~ omf remove forgit                                                                                                              forgit could not be found.
 ~ omf remove https://github.com/wfxr/forgit                                                                                  https://github.com/wfxr/forgit is not a valid package/theme name
```
I uninstalled it manually and removed it from bundle.

I don't know if this is a bug or working as intended, I'd assumed that omf would be able to uninstall a non-omf plugin.

**Environment report**
```
Sun May 22 12:01:53 2022
Oh My Fish version:   7
OS type:              Darwin
Fish version:         fish, version 3.4.1
Git version:          git version 2.36.1
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

**Comment by scorphus** [comment]
Interesting issue. Thanks for reporting.

So, when installing `https://github.com/wfxr/forgit`, the following is displayed:

```
Installing package fo       
✔ fo successfully installed.
```

It seems like there's some gremlins messing around in there when the repo name ends in `git`. That's worth investigating.

In the meantime, `omf remove fo` is your friend.

**Comment by bdmorin** [comment]
well that works like a charm. Thanks!

**Comment by faho** [comment]
The issue is here:

https://github.com/oh-my-fish/oh-my-fish/blob/0b1396ad7962073fa25615bf03c43b53eddc2d56/pkg/omf/functions/packages/omf.packages.name.fish#L2

Try

```fish
echo forgit | sed -E 's/^(omf-)?((plugin|pkg|theme)-)?//;s/.git$//'
```

This will print "fo", because the `.git$` has the `.` as the "one character" metacharacter. It should be `s/\.git$`.
