### ISSUE TITLE
How to install local in-development package

### ISSUE THREAD

**Issue by tennox** [oh-my-fish/oh-my-fish#906]
I read through all the docs & FAQ but didn't find a way to easily "install" a local package during development so that changes to functions are easily reloaded.

I thought to run `set fish_function_path ~/dev/fish-functions/functions $fish_function_path` which would at least work for functions, but seems hacky and I'm sure you guys know&use a better way...?

**Comment by scorphus** [comment]
Hey, @tennox.

One way is to change the contents of the installed package. Plugins reside in `~/.local/share/omf/pkg/` and themes in `~/.local/share/omf/themes/`.

You can either directly change files in those directories or you can create symbolic links, e.g.:

```
ln -s ~/src/github.com/user/plugin-foo ~/.local/share/omf/pkg/foo
```

You may also need to use `omf reload` while changing the contents of the packages.

**Comment by tennox** [comment]
Oh, thanks a bunch! <3

**Comment by tennox** [comment]
Note: If you have installed the plugin already via omf install, you need to remove it first:
```bash
rm -rf $OMF_PATH/pkg/<your-plugin-name> || true
ln -s $PWD $OMF_PATH/pkg/<your-plugin-name>
```
