### ISSUE TITLE
Stuck git repo

### ISSUE THREAD

**Issue by Wdavery** [oh-my-fish/oh-my-fish#909]
I have a stuck git repo that follows me everywhere, the only time it disappears is if a navigate above my user DIR or if I enter an actual git repo. Where could this be pulling from, and how can I try clearing it?

<img width="154" alt="Screen Shot 2022-07-12 at 15 26 26" src="https://user-images.githubusercontent.com/12989893/178577599-28bcee86-d926-4a40-b833-42794cfa87a2.png">

```
Oh My Fish version:   7
OS type:              Darwin
Fish version:         fish, version 3.5.0
Git version:          git version 2.24.3 (Apple Git-128)
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

**Comment by scorphus** [comment]
Check to see if there's a `.git` directory in your "user DIR".
