### ISSUE TITLE
Packaging omf for a Custom Arch ISO/AUR

### ISSUE THREAD

**Issue by Ruturajn** [oh-my-fish/oh-my-fish#910]
Hi,
I am trying to package up oh-my-fish for a custom Arch ISO, and also for the AUR, if possible. But, I am not able to get it installed in the right place. I am not sure, where I am making a mistake, so, I would really appreciate it if I could get some help. This is the link to what I have in the `PKGBUILD`, as of now: [https://controlc.com/d6d45324](https://controlc.com/d6d45324).

Thanks

**Comment by scorphus** [comment]
Oh My Fish is meant to be installed in the user's home directory, not system-wide.

**Comment by Ruturajn** [comment]
Hi,
Thanks for your reply. Yeah, I meant is there a way to do that? i.e. install `omf` to a user's home directory using a `PKGBUILD`.
