### ISSUE TITLE
Installation failure from curl on Pop-os

### ISSUE THREAD

**Issue by Diogenesoftoronto** [oh-my-fish/oh-my-fish#921]
Hey just checked some of the issues and didnt see anyone i could see with my problem so decided to make an issue. 

after running 

```curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | fish```

pipping to fish fails as I get the error: 

fish: Expected a string, but found a redirection
<!DOCTYPE html>

So it seems like this might be solved by parsing the std as a string before pipping it to fish but i really don't know how fish would even parse this html.

**Comment by faho** [comment]
Your link is about 7 years [out of date](https://github.com/oh-my-fish/oh-my-fish/commit/886660d177d7bffbd4acaf4fe055eb3e42818336). Check the [README](https://github.com/oh-my-fish/oh-my-fish/blob/master/README.md), the actual link is:

https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install

**Comment by Diogenesoftoronto** [comment]
That's really strange I got that link from what I thought was the read me. But when I click on your link that clearly is not the case. Hmm

**Comment by Diogenesoftoronto** [comment]
Anyway thanks

**Comment by scorphus** [comment]
Thanks, @faho
