### ISSUE TITLE
'omf install powerline' responding with "Please install powerline" and not being usable

### ISSUE THREAD

**Issue by TheMemeSniper** [oh-my-fish/oh-my-fish#922]
**Environment report**

Run the command `omf doctor` and paste the output here. Example:

```
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.5.1
Git version:          git version 2.38.1
Git core.autocrlf:    no
Please install powerline
Checking for a sane environment...
Your shell is ready to swim.
```

Whenever I install the 'powerline' theme, omf claims the theme is installed and prints "Please install powerline" and does not switch to it with `omf theme powerline`

**Comment by scorphus** [comment]
You need to install [this powerline](https://github.com/powerline/powerline) too.

Quick fix:

- Install [powerline](https://github.com/powerline/powerline) with `pip install powerline-status` (more info on powerline installation [here](https://powerline.readthedocs.io/en/latest/installation.html#pip-installation))
- Reload your shell with `omf reload`

I agree that it's confusing. Would you be kind to open an issue in https://github.com/iamruinous/plugin-powerline? Hopefully the maintainers can make it a bit more clear.
