### ISSUE TITLE
I just install OMF and installed the cyan theme and this happened

### ISSUE THREAD

**Issue by kay5421** [oh-my-fish/oh-my-fish#936]
i also have my language set as polish
`Oh My Fish version:   7-54-gd427501
OS type:              Linux
Fish version:         fish, wersja 3.6.1
Git version:          git version 2.40.1
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
fish: Unknown command: hostname
~/.local/share/omf/themes/cyan/functions/fish_prompt.fish (linia 1):
hostname -s
^~~~~~~^
w zastępstwie polecenia
	called on line 59 of file ~/.local/share/omf/themes/cyan/functions/fish_prompt.fish
in function 'fish_prompt'
w zastępstwie polecenia
~/.local/share/omf/themes/cyan/functions/fish_prompt.fish (linia 59): Unknown command
    echo -n -s $normal $cyan (whoami) '@' $normal $blue (hostname -s) $normal ' ' $cwd ' '  $git_info $yellow' ✗ '$normal
                                                        ^~~~~~~~~~~~^
in function 'fish_prompt'
w zastępstwie polecenia`

**Comment by faho** [comment]
You have installed a theme that calls the `hostname` command and you don't have a `hostname` command.

You can fix this by either installing a hostname command or making a function:

```fish
function hostname
    echo $hostname
end
```

(fish sets the $hostname variable itself)

-----

This happens in [the theme](https://github.com/oh-my-fish/theme-qing) and if you want to ask them to replace the `hostname` call with `$hostname` you should open an issue *there*.

This has nothing to do with oh-my-fish itself.

As a sidenote: oh-my-fish is basically unmaintained and I would recommend you find an alternative. This issue and one comment I made in another represent the sum total activity in this entire repository in the last month.

**Comment by kay5421** [comment]
understood. thanks
