### ISSUE TITLE
Prompt Encoding as Question Mark

### ISSUE THREAD

**Issue by retu2libc** [oh-my-fish/oh-my-fish#941]
A clean install for the first time on a 2020 m1 macbook air with Sonoma

**Environment report**

Run the command `omf doctor` and paste the output here. Example:

```
Oh My Fish version:   7
OS type:              Darwin
Fish version:         fish, version 3.7.0
Git version:          git version 2.39.0
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

My locale:
```
% locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```
I have utf-8 selected in my terminal profile and Terminal is currently Version 2.14. FWIW fish works fine inside my vscode integrated terminal.

For reference:
<img width="564" alt="Screenshot 2024-01-05 at 2 09 28 PM" src="https://github.com/oh-my-fish/oh-my-fish/assets/39571085/47dc35e5-1d7f-49ce-ae75-957a46328348">

**Comment by bobthecow** [comment]
This is probably due to missing Powerline glyphs in your terminal font. See the note in bobthefish's readme: https://github.com/oh-my-fish/theme-bobthefish#installation

**Comment by retu2libc** [comment]
> This is probably due to missing Powerline glyphs in your terminal font.

Indeed that's what it was. Thanks!
