### ISSUE TITLE
Default theme calls hostname without checking or requiring

### ISSUE THREAD

**Issue by SirMaxwellSmart** [oh-my-fish/oh-my-fish#945]
**Description**
While connected to a system with fish installed through SSH, the default theme calls 'hostname' without ever checking if it exists, or listing it as required.

 At the beginning of each new line the terminal spits out an error, trying to fill-in the hostname of the ssh host.

```
fish: Unknown command: hostname
~/.local/share/omf/themes/default/functions/fish_prompt.fish (line 1): 
hostname -s
^~~~~~~^
in command substitution
	called on line 34 of file ~/.local/share/omf/themes/default/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution
 ~
```

**Workaround**
Install a hostname function
or
create hostname as a function to `echo $hostname`
or
set `$theme_ignore_ssh_awareness = yes`

**Environment report**

Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.7.1
Git version:          git version 2.45.2
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.

**Comment by SirMaxwellSmart** [comment]
I just realised this should be opened in the default theme repo, I will move my issue there.

**Comment by MaeuRodrig** [comment]
I like actual default theme, just want to hide username.
it is not available to be edited/customized.
I didn't find **default prompt** in docs or source code.
