### ISSUE TITLE
Can't get 'omf list', 'theme', etc.. It says "fish: Unknown command: column"

### ISSUE THREAD

**Issue by dukelex** [oh-my-fish/oh-my-fish#946]
Hi! Just install omf on Debian WSL2
OS: Debian GNU/Linux 12 (bookworm) on Windows 10 x86_64
Kernel: 5.15.153.1-microsoft-standard-WSL2

I'm trying to list plugins or themes and getting next output:

⋊> ~/.c/omf omf theme                                                                          16:13:14
Installed:
fish: Unknown command: column
~/.local/share/omf/pkg/omf/functions/cli/omf.cli.theme.fish (line 12):
    omf.packages.list --theme | column | sed -E "$highlight_current"
                                ^~~~~^
in function 'omf.cli.theme'
        called on line 2 of file -
in function '__omf_last_command'
        called on line 50 of file ~/.local/share/omf/pkg/omf/functions/omf.fish
in function 'omf' with arguments 'theme'

Available:
fish: Unknown command: column
~/.local/share/omf/pkg/omf/functions/cli/omf.cli.theme.fish (line 15):
    omf.index.query --type=theme | column
                                   ^~~~~^
in function 'omf.cli.theme'
        called on line 2 of file -
in function '__omf_last_command'
        called on line 50 of file ~/.local/share/omf/pkg/omf/functions/omf.fish
in function 'omf' with arguments 'theme'

omf doctor output:

Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.7.1
Git version:          git version 2.39.2
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.

At the same time, the installation of plugins and themes is going well.

**Comment by scorphus** [comment]
You're likely using a minimal distro version. It apparently does not include the `column` command. It's part of the `bsdextrautils` package that you can install with `apt install bsdextrautils`.

**Comment by dukelex** [comment]
Oh, Thanks!!
